- .gitignore
- spikeinterface/toolkit/preprocessing/remove_bad_channels.py
- spikeinterface/toolkit/preprocessing/tests/test_remove_bad_channels.py
If a recording was passed to the remove_bad_channel preprocessor, the resulting object got the recording and probe properties destroyed. Reordering the inheritance and changing some arguments seems to correct this issue.
> Reorder inheritance of RemoveBadChannelsRecording and the arguments.

- spikeinterface/core/waveform_extractor.py
- spikeinterface/toolkit/postprocessing/template_tools.py
When `max_spikes_per_unit` is `None`, all waveforms should be extracted.
This was also failing due to an `int()` parsing in the set params.
> Handle waveform extraction when max_spikes_per_unit_is None

- spikeinterface/widgets/rasters.py
The rasterwidget throws an error when given a segment_index. The usage of get_unit_spike_trains is not including the segment_index yet.
> Rasterwidget: use segment index for extracting unit spike trains

- spikeinterface/core/baserecording.py
- spikeinterface/core/tests/test_waveform_extractor.py
- spikeinterface/core/waveform_extractor.py
- spikeinterface/toolkit/qualitymetrics/misc_metrics.py
- spikeinterface/toolkit/tests/test_utils.py
- spikeinterface/toolkit/utils.py
Add option to `extract_waveforms` to return scaled waveforms. This is Tru by default, as waveforms and templates are usually retrieved in uV
> Add return_scaled params to WaveforExtractor

- spikeinterface/exporters/report.py
- spikeinterface/sorters/runsorter.py
This PR fixes the `modify_input_folder` function to make it work with preprocessed recordings.
In addition, a [full] installation on the docker side is always performed.
> Fix docker sorting for processed recordings

- spikeinterface/sorters/combinato/combinato.py
Led to an Exec format error when trying to run the combinato sorter 
'# !/bin/bash'  -->  '#!bin/bash'
> Shebang for linux command had an extra uneeded space.

- spikeinterface/toolkit/qualitymetrics/pca_metrics.py
- spikeinterface/toolkit/qualitymetrics/quality_metric_calculator.py
This PR adds a new metric called isolation metric to `toolkit.qualitymetrics`. It is described in [Chung 2017](https://doi.org/10.1016/j.neuron.2017.08.030). 
* There is already an implementation of this metric in the form of `nn_hit_rate` in `nearest_neighbors_metrics` function in `misc_metrics.py`. However, this implementation has a couple of issues:
* It fails to handle the case in which `n_neighbors`=1 (returns nan).
* It is also _not the same_ as the isolation metric from Chung 2017, even though the docstring claims that it is. This difference is known and is discussed [here](https://github.com/SpikeInterface/spikemetrics#a-note-on-calculations).
* While it is true that the metric can be unreliable when comparing two clusters with a large difference in firing rate, Chung 2017 …
> [Work in progress] Add isolation metric

- spikeinterface/toolkit/qualitymetrics/pca_metrics.py
So that it is tested, see https://github.com/SpikeInterface/spikeinterface/pull/220#discussion_r701981266
Sorry for not including this in the earlier PR (https://github.com/SpikeInterface/spikeinterface/pull/220)
> Add `nn_isolation` to `_possible_pc_metric_names`

- spikeinterface/core/job_tools.py
- spikeinterface/extractors/phykilosortextractors.py
- spikeinterface/sorters/launcher.py
- spikeinterface/sorters/runsorter.py
We would like to be able to use run_sorters with docker images for some of the sorters. This should deal with that. The run_sorters command also accept docker_images = {sorter_name : docker_image}. If provided, adequate docker image are used instead of local sorters
> Path for run_sorters with docker images

- spikeinterface/comparison/groundtruthstudy.py
- spikeinterface/sorters/__init__.py
- spikeinterface/sorters/launcher.py
- spikeinterface/sorters/runsorter.py
When launching run_sorters in a study, one should not collect outputs, such that if there is a crash of any sorters, the loop keeps working. Plus, this is redondant with copy_sorters()
> with_output should be False in run_sorters

- spikeinterface/extractors/neoextractors/maxwell.py
depends on `probeinterface==0.2.5` (https://github.com/SpikeInterface/probeinterface/pull/68)
> Load maxwell electrode as property

- spikeinterface/extractors/nwbextractors.py
There is 1 bug fix and feature additions in the PR:
- Adding the functionality for the user to provide a custom electrical series name to retrieve traces using `get_traces()`. This does not assume the data is always under `nwbfile.acquisition`. 
- Bug fixes: on [line 145](https://github.com/SpikeInterface/spikeinterface/pull/263/files#diff-747bbb41d9f1d2008fae02031f082547cac21e9f9535a5be96a4cd15d4aa4d7dR145) 
fix #262
> electrical series arg handle in nwbextractors

- spikeinterface/extractors/neoextractors/openephys.py
Previously in the version 0.90, only new binary openephys format could be loaded. The legacy format were detected as new one. The problem came from this if condition.
> Fix reading of legacy OpenEphys recording format

- doc/implement_spike_sorter.rst
- doc/index.rst
- doc/install_sorters.rst
- doc/installation.rst
- doc/module_comparison.rst
- doc/module_sorters.rst
- doc/overview.rst
- doc/supported_formats_and_sorters.rst
- examples/getting_started/plot_getting_started.py
- examples/modules/comparison/generate_erroneous_sorting.py
- examples/modules/comparison/plot_1_compare_two_sorters.py
- examples/modules/comparison/plot_2_compare_multiple_sorters.py
- examples/modules/comparison/plot_3_compare_sorter_with_ground_truth.py
- examples/modules/comparison/plot_4_ground_truth_study.py
- examples/modules/comparison/plot_5_comparison_sorter_weaknesses.py
- examples/modules/core/plot_1_recording_extractor.py
- examples/modules/core/plot_3_handle_probe_info.py
- examples/modules/core/plot_4_waveform_extractor.py
- examples/modules/core/plot_5_append_concatenate_segments.py
- examples/modules/extractors/plot_1_read_various_formats.py
- examples/modules/sorters/plot_1_sorters_example.py
- examples/modules/sorters/plot_2_using_the_launcher.py
- examples/modules/sorters/plot_3_sorting_by_group.py
- examples/modules/sorters/plot_4_sorting_concatenated_recordings.py
- examples/modules/widgets/plot_1_rec_gallery.py
- examples/modules/widgets/plot_3_waveforms_gallery.py
I was reading through the documentation & examples for the new version of SpikeInterface, and noticed a few typos, etc, 
so I thought I'd do a quick sweep and offer a fix for them. 
Note: I only meant to fix the typos, but I noticed on the diffs that a setting in my text editor has also removed trailing whitespace - sorry if that's annoying.
> [DOC] - Typo fixes on documentation & examples

- examples/modules/core/plot_4_waveform_extractor.py
- spikeinterface/comparison/groundtruthstudy.py
- spikeinterface/core/tests/test_waveform_extractor.py
- spikeinterface/core/waveform_extractor.py
- spikeinterface/toolkit/postprocessing/template_tools.py
- spikeinterface/toolkit/postprocessing/tests/test_template_tools.py
- spikeinterface/toolkit/qualitymetrics/tests/test_pca_metrics.py
- spikeinterface/toolkit/qualitymetrics/tests/test_quality_metric_calculator.py
refactor waveform template cache : add disk persistency
Now templates are cache all togoether not one by one.
And they are persistent on disk.
Note that this PR do not change the API only the internal way of caching templates
> refactor waveform template cache : add disk persistency

- spikeinterface/core/baserecording.py
- spikeinterface/toolkit/preprocessing/filter.py
- spikeinterface/toolkit/preprocessing/tests/test_filter.py
uint traces must be converted to int upon retrieval before filtering and this was not done automatically.
> Fix filtering for uint signals

- spikeinterface/toolkit/qualitymetrics/pca_metrics.py
- spikeinterface/toolkit/utils.py
@alejoe91 @samuelgarcia 
This PR adds the nearest neighbor noise overlap score to quality metrics (see discussion: https://github.com/SpikeInterface/spikeinterface/issues/267#issue-997327372)
Roughly speaking, this quality metric tells you how close a target cluster is to a noise cluster (generated by randomly sampling voltage snippets from the recording). 
Initially I was under the impression that I would need to first calculate PCs for the waveforms and then project noise snippets; upon discussion with Jeremy Magland and others who created the metric, I learned that I should instead concatenate the waveform and noise snippets and then compute PCs. As such it doesn't use the WaveformPC object. There may also be other parts that could be replaced with calls to existing classes or …
> Add nearest neighbor noise overlap to pc metrics in spikeinterface.toolkit

- TODO_big_refactoring.txt
- spikeinterface/sorters/herdingspikes/herdingspikes.py
Update Herdingspikes wrapper to work both with:
- version < 0.3.99 (uses `OldAPIRecordingExtractor`)
- version >= 0.3.99 (uses new API directly)
> HS2 version>=0.3.99

- spikeinterface/toolkit/qualitymetrics/pca_metrics.py
Previous version computed the metric based on the pca over all channels. This version makes use of only the channels that have signal. Also starts from waveform extractor rather than pca object, similar to nearest neighbor noise overlap.
> Update nearest neighbor isolation metric

- doc/installation.rst
Responds to #361 - fixing the install instructions for 'core', and adding a note about needing to use quotes in Z shell.
> [DOC] - Update install instructions

- spikeinterface/toolkit/preprocessing/filter.py
- spikeinterface/toolkit/preprocessing/tests/test_filter.py
Just a WIP to discuss. related to #363 
I guess this is the simplest change to allow any filter in spikeinterface
I don't know the details of self._kwargs, should I create the dict with only the used inputs inside the if statement? (discarting filter_order, band, etc and adding coef) or just adding coeff to the current line?
> Allow any filter in spikeinterface

- spikeinterface/core/baserecording.py
- spikeinterface/core/segmentutils.py
Most of the recordings are NEO-based ans with `t_start` set to 0. Currently, this prevents concatenation. This PR relaxes the assertion on `t_start=None` to a warning and resets the `t_start` of the `ProxyConcatenateRecordingSegment` to `None` in case
> Relax requirement on t_start for concatenate_recordings

- spikeinterface/toolkit/qualitymetrics/misc_metrics.py
https://github.com/SpikeInterface/spikeinterface/issues/385 noticed that the ISI violation implementation doesn't follow the one from [Hill et al. (2011) J Neurosci 31: 8699-8705](https://www.jneurosci.org/content/31/24/8699)
Ported the [spikemetrics implementation](https://github.com/SpikeInterface/spikemetrics/blob/2e95cbaf15090b1c5e5c94586fdbb618b8acf3f1/spikemetrics/metrics.py#L569-L608) (which was in turn from the Allen implementation) to the new version!
@Yizhar-Lab could you double check it?
> ISI violation ratio as in Hill2011

- spikeinterface/extractors/phykilosortextractors.py
Fixes: https://github.com/SpikeInterface/spikeinterface/issues/382
@szbalazs98 the problem was that the PhySortingExtractor returned an extra dimension for the spik trains (e.g. `(num_spikes, 1)`) and that was messing up other stuff.
I also fixed the `id` VS `cluster_id` problem: the code looks for `cluster_id`, but if not found `id` is used. Can you test this?
> PhySorting fix spike train dimensions

- spikeinterface/extractors/nwbextractors.py
sampling frequency was computed as:
`sampling_frequency = 1. / np.median(np.diff(timestamps[samples_for_rate_estimation]))`
but `samples_for_rate_estimation` is a number rather than a range. 
I added a `:` so that the first `samples_for_rate_estimation` samples would used to estimate sampling rate.
> Fix sampling frequency computation in nwbextractor

- spikeinterface/toolkit/preprocessing/common_reference.py
This fixes the problem I have that sometimes, channel_indices are 2D arrays (tested with mearecrawio), and thus CAR is crashing because dimensions are too large. This solves my problems in sortingcomponent too, with get_chunk_with_margin
> Fix for channels_indices that are 2D sometimes

- spikeinterface/core/baserecording.py
The timestamps for nwbextractor is of type h5py Dataset which cannot be converted to numpy array by `.asarray()`. I added a line to check the type of the timestamps and use a different method to return it in the case it is a h5py Dataset.
> Handle h5py dataset timestamps

- spikeinterface/core/old_api_utils.py
what's referred to downstream is `_oldapi_sorting_extractor` not `_old_api_sorting_extractor`
> Fix minor typo

- spikeinterface/toolkit/preprocessing/common_reference.py
- spikeinterface/toolkit/preprocessing/tests/test_common_reference.py
@alejoe91
Common referencing with `reference=single` behaves incorrectly because the reference channel ID is not first converted to index prior to subtraction. This PR tries to fix it. Let me know if this is the correct use of `self.ids_to_indices`.
> Fix 'single' common referencing

- spikeinterface/core/tests/test_waveform_extractor.py
- spikeinterface/core/waveform_extractor.py
- spikeinterface/toolkit/postprocessing/principal_component.py
- spikeinterface/toolkit/postprocessing/spike_amplitudes.py
- spikeinterface/toolkit/postprocessing/tests/test_principal_component.py
- spikeinterface/toolkit/postprocessing/tests/test_spike_amplitudes.py
- spikeinterface/toolkit/qualitymetrics/quality_metric_calculator.py
- spikeinterface/toolkit/qualitymetrics/tests/test_quality_metric_calculator.py
With `we.filter_units(unit_ids, new_folder)` one can create a new `WaveformExtractor` object only with the selected units. All the registered extensions will also automatically copy the correct info about the selected units in the new folder.
> Implement filter_units() in waveform extractor and extensions

- spikeinterface/core/tests/test_waveform_extractor.py
- spikeinterface/core/waveform_extractor.py
- spikeinterface/toolkit/postprocessing/principal_component.py
There was a bug in copying the files. Now both WaveformExtractor and WaveformPrincipalComponent check for entire file names.
> Fix filtering units when units>10

- spikeinterface/core/base.py
- spikeinterface/toolkit/preprocessing/normalize_scale.py
- spikeinterface/toolkit/qualitymetrics/misc_metrics.py
- spikeinterface/toolkit/qualitymetrics/tests/test_quality_metric_calculator.py
Fixes https://github.com/SpikeInterface/spikeinterface/issues/421
Plus a small fix to make the `scale` recording object dumpable (save dtype string in kwargs)
> Fix peak sign for amplitude cutoffs

- spikeinterface/exporters/to_phy.py
- spikeinterface/extractors/phykilosortextractors.py
Partially implements suggestions in https://github.com/SpikeInterface/spikeinterface/issues/402
- when "quality_metrics" extension is present, add metrics to Phy tsv files
- save an extra tsv with "si_unit_id". This keeps track of the SI unit id (e.g. #0 in mearec) and loads unit back from this column (if existing)
> Add quality metrics and SI unit ids to phy tsv

- spikeinterface/core/waveform_extractor.py
Fixes https://github.com/SpikeInterface/spikeinterface/issues/331 and https://github.com/SpikeInterface/spikeinterface/issues/442
Added `cache` and `memmap` options for `get_waveforms`
Using the code from @Dradeliomecus [here](https://github.com/SpikeInterface/spikeinterface/issues/331#issue-1036047654) for a 300s 64-chan recording, with 60 units:
```
wvf_extractor = spikeinterface.WaveformExtractor.create(rec, sort, "test_mem", remove_if_exists=True)
wvf_extractor.set_params(ms_before=4.0, ms_after=8.0, max_spikes_per_unit=None)
wvf_extractor.run_extract_waveforms(n_jobs=4, total_memory='2G', progress_bar=True)
print("Memory usage of wvf_extractor: {0:.5f} GB\n".format(getsize(wvf_extractor) / 1024**3))
for unit_id in sort.get_unit_ids():
print("Extracting unit", unit_id)
wvfs = …
```
> Make waveform cache to memory optional

- doc/module_core.rst
- examples/modules/core/plot_6_handle_times.py
- spikeinterface/core/basesorting.py
- spikeinterface/core/frameslicesorting.py
- spikeinterface/core/tests/test_time_handling.py
- spikeinterface/core/unitsaggregationsorting.py
- spikeinterface/core/unitsselectionsorting.py
- spikeinterface/sorters/basesorter.py
Added `register_recording` to link a recording to a sorting in memory. This enables to propagate the `get_times` mechanism to the sorting object.
* The `BaseSorter` automatically registers the recording to the output sorting object
* recording object is propagated to `UnitsSelectionSorting`, but it cannot be propagated to `UnitsAggregationSorting` and `FrameSliceSorting` (as they would require more complicated times management)
* Added a `return_times` option to return spike trains as times in second (either using the registered recording or the sampling frequency)
> Add recording link to sorting

- spikeinterface/core/__init__.py
- spikeinterface/core/old_api_utils.py
Final addition (hopefully) to `old_api_utils`: added a class to make an old sorting extractor from a new sorting. Need this because old sorting doesn't have segments and some method names are different (e.g. old `get_units_spike_train` vs. new `get_all_spike_trains`). Mostly copied from `spikeextractors` repo.
> New to old sorting

- spikeinterface/core/datasets.py
- spikeinterface/sorters/runsorter.py
- spikeinterface/sorters/tests/test_runsorter.py
- Skip container tests only on github, but not locally
- Use public test file for container tests to make local test runs comparable
- Pull docker images if these are not  yet available locally
- Extend check if spikeinterface  installation in container is functional
> Enhance container handling

- .gitignore
To cleanup the version control and prevent test files to be accidentally added to the history, this PR lists all current test files in the gitignore as well as hidden PyCharm config folders
> Add test files and PyCharm config to gitignore

- spikeinterface/core/old_api_utils.py
The default for `RecordingExtractor.get_dtype()` utilizes `return_scaled=True`, making all dtypes from old extractors that have gains/offsets set upcast to float despite underlying storage. This branch fixes the issue, but keeping as draft until downstream tests (https://github.com/catalystneuro/nwb-conversion-tools/pull/384) confirm roundtrip works.
> Fix OldToNewRecording data type

- spikeinterface/sorters/runsorter.py
Multiple runs on docker-based sorters leads to accumulation of stopped containers in host machine
The proposal here is to remove the container whenever we stop the container_client
Please let me know if it's possible/relevant to do a similar thing in singularity mode
> Remove container after run sorter in docker mode

- spikeinterface/comparison/multicomparisons.py
- spikeinterface/core/base.py
- spikeinterface/core/old_api_utils.py
- spikeinterface/core/tests/test_baserecording.py
This PR allows for better control of missing values when setting properties by adding the argument `missing_value`
Note that in case the missing value and the values have different dtypes, the property dtype is set to `object`
> Add 'missing_value' to set_property

- spikeinterface/extractors/nwbextractors.py
Sampling frequency is either obtained from the NWB file or estimated during instantiation. In that case, we may as well add it to `times_kwargs` for generating the recording segment. This isn't just optional - if we don't do this, we get problems. For example, when we concatenate NWB recordings that was generated with `load_time_vector=True`, the `times` are discarded, and as a result the recording segments have no time information (both `time_vector` and `sampling_frequency` are not set).
> Add sampling freq to `times_kwarg` of NwbRecordingExtractor

- spikeinterface/sorters/ironclust/ironclust.py
Check/run compiled ironclust in docker image after internal discussions for #471
Points to discuss in this Draft PR:
- Sorter logs is supressed somewhere, I couldn't manage to show it to the end user (is this a python Docker SDK thing? Is this related to ShellScript?
- What if the user somehow has the `p_ironclust` command in shell? Should we change the approach in check_compiled function?
- We need to find a way to pass local spikeinterface to pip install [here](https://github.com/Tauffer-Consulting/spikeinterface/blob/matlab-docker-integration/spikeinterface/sorters/runsorter.py#L285)
> Matlab Compiled IronClust

- spikeinterface/core/__init__.py
- spikeinterface/core/segmentutils.py
- spikeinterface/extractors/nwbextractors.py
per our discussion @alejoe91 @samuelgarcia: This is a new class that takes a sorting with a single segment and a list of recordings and returns a sorting with multiple segments, each defined by the length of the recordings in the list. This would be useful for getting back the times of the spikes after sorting a concatenated recording, which removes time information. Please take a look.
> Add `SplitSegmentSorting`

- spikeinterface/core/waveform_extractor.py
- spikeinterface/core/waveform_tools.py
- spikeinterface/toolkit/postprocessing/principal_component.py
Hi guys, in some system like mine the following code doesn't work:
```
from pathlib import Path
np.save('test.npy',np.arange(2))
wfs = np.load(Path('casa3.npy'), mmap_mode="r+")
```
The pull request just cast to str the Path before the np.load.
In my system: 
OS: Windows 7
Python: 3.8.12 
Numpy: 1.22.2
> support for some systems

- spikeinterface/core/testing.py
- spikeinterface/extractors/nwbextractors.py
PR for the issue as described in https://github.com/catalystneuro/nwb-conversion-tools/issues/429. The idea is that when channel_name is available as a column in the `nwb_extractor` this property is the one that will get loaded as channel_ids instead of `nwb_file.electrodes.id`. 
Similar work should be done for the units table in another PR.
> Modify nwb recorder extractor for loading channel name property as channel_ids when available

- requirements.txt
- spikeinterface/core/baserecording.py
- spikeinterface/core/core_tools.py
- spikeinterface/core/testing_tools.py
- spikeinterface/core/tests/test_baserecording.py
- spikeinterface/extractors/nwbextractors.py
Based on https://github.com/SpikeInterface/spikeinterface/pull/536
- Added tests
- Added `planarize()` function in `BaseRecording`
- Improved `apply_dimensions_to_positions()` function to handle any combination of x-y-z
- Fixed `set_dummy_probe_from_locations` when locations are 3d by adding mock `plane_axes`
@magland I was not able to push directly on your fork for some reason. So let me know if this looks good for you and @lfrank
> Support rel z in nwb

- spikeinterface/toolkit/qualitymetrics/pca_metrics.py
I was processing a lot of recordings and I found a case with just one unit, in that case I got an error computing d_prime. I just set that to nan for the single unit case
> add nan to d_prime for single unit case

- spikeinterface/extractors/phykilosortextractors.py
Sometimes there are multiple Kilosort csv/tsv files with the column "KSLabel". I think this is before the user has manually assigned groups, and they are identical. In this case, one needs to be named 'KSLabel' in the extracted DataFrame, rather than naming them 'KSLabel_x' and '_y', or the keep_good_only logic won't work.
> Fixing "KSLabel" extraction in phykilosortextractor

- spikeinterface/comparison/basecomparison.py
- spikeinterface/core/__init__.py
- spikeinterface/core/baserecording.py
- spikeinterface/core/job_tools.py
- spikeinterface/core/segmentutils.py
- spikeinterface/core/tests/test_segmentutils.py
- spikeinterface/toolkit/postprocessing/template_metrics.py
New functions to split multi-segment recordings into a list of mono-segments:
- Return a list of mono-segment recordings
`recording_list = si.split_recording(rec_multi)`
- Return a single mono segment recording
`recording_mono = si.select_segment_recording(rec_multi, segment_index=1)`
> Add split recording class and function

- spikeinterface/comparison/groundtruthstudy.py
- spikeinterface/comparison/studytools.py
- spikeinterface/sorters/__init__.py
- spikeinterface/sorters/launcher.py
- spikeinterface/sorters/tests/test_launcher.py
Fixes https://github.com/SpikeInterface/spikeinterface/issues/572 and mroe
> Refactor run_sorters/run_sorter_by_group to better folders/dtypes

- spikeinterface/core/baserecording.py
- spikeinterface/toolkit/preprocessing/normalize_scale.py
- spikeinterface/widgets/timeseries.py
Fixes:
- https://github.com/SpikeInterface/probeinterface/issues/101 for loading NWBfiles with 3d location
- `scale` preprocessing would set gains to 0 if gain < 1and dtype = int16 --> moved casting to segment
- Added `**plot_kwargs` to `lot_timeseries`
> Fix Nwb 3d locs, scale preproc, and **plot_kwargs

- spikeinterface/widgets/activity.py
- spikeinterface/widgets/drift.py
- spikeinterface/widgets/probemap.py
- spikeinterface/widgets/tests/test_widgets.py
- spikeinterface/widgets/unitlocalization.py
- spikeinterface/widgets/unitprobemap.py
plot_probe can plott the contact_id and also the device_channel_index but it is sometimes more convinient to plot the also the channel_ids. 
Here a PR for this
This depend on https://github.com/SpikeInterface/probeinterface/pull/93
Plot channel_ids on the probe for:
* PeakActivityMapWidget
> Add with_channel_ids for several widgets that use plot_probe

- spikeinterface/toolkit/qualitymetrics/pca_metrics.py
- spikeinterface/toolkit/qualitymetrics/tests/test_quality_metric_calculator.py
* Add a new parameter to `nearest_neighbors_isolation` and `nearest_neighbors_noise_overlap` functions called `min_spikes_for_nn`
* Units with fewer spikes than `min_spikes_for_nn` (small clusters) are given `np.NaN` as the metric and a warning is printed
* `min_spikes_for_nn` is set to 10 by default
* Metrics are computed for units with more spikes than `min_spikes_for_nn` but after first excluding the small clusters (since nearest neighbor metrics do pairwise comparison across all clusters)
> Handle computing of nearest neighbor metrics for units with few spikes

- spikeinterface/sortingcomponents/peak_selection.py
- spikeinterface/sortingcomponents/tests/test_peak_selection.py
Adding the possibility to sub-select spikes with rejection probabilities based on locations, locations and time. This might be useful if one want to select spikes covering as uniformly as possible both space and time
> More peak selections methods

- environment_rtd.yml
- spikeinterface/core/base.py
- spikeinterface/sorters/launcher.py
- spikeinterface/toolkit/postprocessing/template_metrics.py
- Fix HS version in RTD environment
- Fix bug in retrieving rec_name and sort_name in `run_sorterd` (introduced with https://github.com/SpikeInterface/spikeinterface/pull/579)
- Check major and minor version in `load_extractor` (and use `packaging`)
- Fix column name in `template_metrics` when sparsity is used
> Various fixes

- spikeinterface/comparison/basecomparison.py
- spikeinterface/extractors/extractorlist.py
- spikeinterface/extractors/mcsh5extractors.py
- spikeinterface/toolkit/postprocessing/template_metrics.py
- spikeinterface/toolkit/qualitymetrics/misc_metrics.py
- spikeinterface/version.py
- In multicomparison, remove duplicate nodes after removing all duplicate edges. If not, removing a node also removes all associated edges, and this triggers an error when attemtping to remove the duplicate edges (this happens when multiple edges from one node needs to be removed)
- small fix to template metrics computation: half-width should return `nan` instead of `None` when not computed
> Fixes Multicomparison clean_graph and half-width

- spikeinterface/core/base.py
- spikeinterface/core/baserecording.py
- spikeinterface/core/core_tools.py
- spikeinterface/core/tests/test_baserecording.py
- spikeinterface/core/zarrrecordingextractor.py
- spikeinterface/toolkit/qualitymetrics/misc_metrics.py
- spikeinterface/toolkit/qualitymetrics/tests/test_quality_metric_calculator.py
This PR allows the `zarr_path` to be any zarr-compatible `Store` object, including cloud storages (see https://zarr.readthedocs.io/en/stable/tutorial.html#distributed-cloud-storage)
Tested with Gcloud, more testing is required for other platforms.
> Zarr modification to work with cloud object directly

- spikeinterface/comparison/groundtruthstudy.py
- spikeinterface/core/waveform_extractor.py
- spikeinterface/sorters/kilosortbase.py
- spikeinterface/toolkit/postprocessing/template_metrics.py
- spikeinterface/toolkit/postprocessing/tests/test_template_metrics.py
- spikeinterface/toolkit/utils.py
- Add `seed` for sampling waveforms in waveform extractor (useful when comparing different pre-processing)
- Remove print in Kilosort run
- Add `sparsity` option in template metrics, where one can directly specify a dictionary with a list of `channel_ids` for each `unit_id`
- Add option to `remove_sorters_folder` in `GTStudy`
> Various (small) improvements

- spikeinterface/core/base.py
- spikeinterface/core/core_tools.py
- spikeinterface/sorters/runsorter.py
Enable Docker mechanism for Windows machines.
The main idea is to modify the paths and the extractor dictionaries on the fly to switch between UNIX and Windows paths.
Tested with:
- `tridesclous-base:1.6.4-1`
- `spykingcircus-base:1.1.0`
- `ironclust-base:5.9.8`
> Docker on windows

- spikeinterface/extractors/neoextractors/spikeglx.py
@alejoe91 and I were discussing today the loading of the probe geometry for spikeglx. These are the requested changes.
> quick fix for spikeglx probe

- spikeinterface/toolkit/preprocessing/remove_artifacts.py
- spikeinterface/toolkit/preprocessing/tests/test_remove_artifacts.py
@alejoe91
We use `RemoveArtifactsRecording` to remove large transients in our recording prior to sorting. To do so, we identify the times in which these artifacts occur by applying a threshold and setting them to zero using `zeros` mode. Because we want only these times to zeroed out, we set the `ms_before` and `ms_after` parameters to zero. But if we do that, `RemoveArtifactsRecording` doesn't do anything because line 117 of `remove_artifacts.py` becomes `traces[trig:trig,  :] = 0`, which doesn't slice anything.
I added `+1` to line 117. I think this is the behavior a user would expect.
> Handle artifact removal in which padding around the triggers is zero

- spikeinterface/core/baserecording.py
Change from `List` to `Iterable`.
With possible incoming of `np.ndarray`, `List` is incompatible. On the other hand, `Iterable` is enough since it's only used as `ids` in the loop:
https://github.com/SpikeInterface/spikeinterface/blob/8143a0d057c93e4aa816f755189c159052a49df1/spikeinterface/core/base.py#L90
> Change typing of `channel_ids` in `BaseRecording.get_traces`

- spikeinterface/core/base.py
- spikeinterface/extractors/__init__.py
- spikeinterface/extractors/alfsortingextractor.py
- spikeinterface/extractors/bids.py
- spikeinterface/extractors/cbin_ibl.py
- spikeinterface/extractors/combinatoextractors.py
- spikeinterface/extractors/herdingspikesextractors.py
- spikeinterface/extractors/klustaextractors.py
- spikeinterface/extractors/mcsh5extractors.py
- spikeinterface/extractors/neoextractors/ced.py
- spikeinterface/extractors/neoextractors/maxwell.py
- spikeinterface/extractors/neoextractors/mearec.py
- spikeinterface/extractors/neoextractors/neobaseextractor.py
- spikeinterface/extractors/neoextractors/neuroscope.py
- spikeinterface/extractors/neoextractors/nix.py
- spikeinterface/extractors/neoextractors/spike2.py
- spikeinterface/extractors/nwbextractors.py
- spikeinterface/extractors/phykilosortextractors.py
- spikeinterface/extractors/shybridextractors.py
- spikeinterface/extractors/spykingcircusextractors.py
- spikeinterface/extractors/tests/common_tests.py
- spikeinterface/extractors/tests/test_bids.py
- spikeinterface/extractors/tridesclousextractors.py
- spikeinterface/extractors/yassextractors.py
- spikeinterface/sorters/runsorter.py
This attribute is used by the `run_sorter_container` function to install missing requirements in the container.
This PR also harmonized the requirements handling for the tdc extractor and renames `read_bids_folder` to `read_bids` for consistent naming with other formats.
> Add extra_requirements attribute to extractors

- spikeinterface/core/base.py
- spikeinterface/core/baserecording.py
- spikeinterface/core/tests/test_baserecording.py
This PR adds a test case in which an unconnected probe is set for a recording.
Linking an unconnected probe is not a main use case, but might occur e.g. when looping across multiple recording streams and automatically generating probes for all of them.
Previously this case raised an error.
> Don't raise error for probe with unconnected channels

- spikeinterface/extractors/neoextractors/neobaseextractor.py
@alejoe91 : we were very tired.
The bug of kwargs was still here becasue `BaseRecording.init` was called after !!!!!
Go back to your solution.
> fix the kwargs bug in neo case

- spikeinterface/core/waveform_extractor.py
Change the dtype for the templates in WaveformExtractor to be float32 for mode=average and std.
Still the same for mode=median.
> Waveform template float32 for average and std

- spikeinterface/sorters/runsorter.py
When running mountainsort4 in container, which uses multiprocessing, `RuntimeError` occours
Adding guard clause to the `in_container_sorter_script.py` solves the problem
- run mountainsort4 (without container)
- run mountainsort4 with docker_image=True
- run mountainsort4 with singularity_image=True
```
Error running mountainsort4
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/spikeinterface/sorters/basesorter.py", line 202, in run_from_folder
SorterClass._run_from_folder(output_folder, sorter_params, verbose)
File "/usr/local/lib/python3.8/site-packages/spikeinterface/sorters/mountainsort4/mountainsort4.py", line 116, in _run_from_folder
old_api_sorting = mountainsort4.mountainsort4(
File "/usr/local/lib/python3.8/site-packages/mountainsort4/mountainsort4. …
```
> Add guard into container py script

- spikeinterface/toolkit/postprocessing/__init__.py
- spikeinterface/toolkit/postprocessing/spike_amplitudes.py
- spikeinterface/toolkit/postprocessing/spike_locations.py
- spikeinterface/toolkit/postprocessing/tests/test_spike_amplitudes.py
- spikeinterface/toolkit/postprocessing/tests/test_spike_locations.py
- spikeinterface/toolkit/postprocessing/unit_localization.py
Adds a function/class to compute spike locations from waveform extractor (similar to amplitude calculator).
Internally, it uses the `localiza_peaks` form sorting components.
> Added SpikeLocationsCalculator as WaveformExtension

- .gitignore
- spikeinterface/core/__init__.py
- spikeinterface/core/base.py
- spikeinterface/core/baserecording.py
- spikeinterface/core/basesorting.py
- spikeinterface/core/binaryfolder.py
- spikeinterface/core/binaryrecordingextractor.py
- spikeinterface/core/npzsortingextractor.py
- spikeinterface/core/tests/test_basesorting.py
- spikeinterface/core/tests/test_binaryfolder.py
- spikeinterface/sorters/kilosortbase.py
- spikeinterface/sorters/klusta/klusta.py
- spikeinterface/sorters/pykilosort/pykilosort.py
- spikeinterface/sorters/tridesclous/tridesclous.py
- spikeinterface/sorters/yass/yass.py
This PR should remove a deep bug in spikeinterface core.
In some situation using dump to json could lost the propertis (and so the probe).
This should fix this.
It also add a better way to avoid copy for sorter when not needed.
> Add BinaryFolder + binary compatible

- spikeinterface/sorters/runsorter.py
`/opt` is readonly when running on singularity, removing `cp` command and installing dev si directly from binded path
The bind is set to readonly, so it's safe not to copy
> Fix install dev si for singularity

- spikeinterface/extractors/neoextractors/openephys.py
- spikeinterface/extractors/neoextractors/spikeglx.py
- spikeinterface/extractors/neuropixels_utils.py
`num_adcs` --> `num_channels_per_adc`
> Autoload of sample shifts for open-ephys NPIX and better naming

- spikeinterface/core/datasets.py
- spikeinterface/core/tests/test_datasets.py
This remove the systematic import of datalad which can be annoying in notebook for some version because it trigger lot of errors.
datalad will be now imported on demand only.
Same as here : https://github.com/NeuralEnsemble/python-neo/pull/1132
> import datatlad only when running download_dataset()remove

- spikeinterface/sortingcomponents/clustering/sliding_nn.py
This is because sliding_nn need hdbscan, and a proper try/catch import was not performed.
> hdbscan import

- spikeinterface/sorters/runsorter.py
Save sorting when running in container to not rely only on the sorter specific extractor.
This code comes specially because for now, we need to have `tridesclous` installed to run tridesclous container with `with_output = True`
> In container save sorting, getting from saved for exceptions

- spikeinterface/sortingcomponents/benchmark/benchmark_clustering.py
- spikeinterface/sortingcomponents/benchmark/benchmark_matching.py
- spikeinterface/sortingcomponents/benchmark/benchmark_peak_selection.py
- spikeinterface/sortingcomponents/clustering/clustering_tools.py
Handle the fact that MEArec recordings could be filtered. However, something is weird here, because I am supposed to generate recordings that are explicitly unfiltered (given the MEArec syntax). So either this flag is not considered, either SI always assumes MEArec recordings are filtered. I don't know
> In case recordings are already filtered

- spikeinterface/comparison/collisioncomparison.py
Somehow a line has been lost during commits, breaking the collision widget.
> Fix for collisions

- spikeinterface/core/baserecording.py
- spikeinterface/core/binaryrecordingextractor.py
- spikeinterface/core/core_tools.py
- spikeinterface/core/tests/test_baserecording.py
- spikeinterface/core/tests/test_core_tools.py
- spikeinterface/core/zarrrecordingextractor.py
The casting from unsigned to signed was scattered in the code base and not handled well in all situations (see https://github.com/SpikeInterface/spikeinterface/issues/657).
My proposal is:
- adding a `cast_unsigned` (False by default) as an additional arg to the `BaseRecording.get_traces()` that automatically does the centering and casting
- the write functions (to binary, to zarr, to memory) check the dtype:
* if None and recording dtype is unsigned --> write unsigned
* if dtype specified is int and recording is unsigned --> cast unsigned first and then cast to new dtype
This will fix https://github.com/SpikeInterface/spikeinterface/issues/657 because the intan recording is unsigned, and Kilosort writes to binary in `int16`, so this will trigger the `cast_unsigned=True` option in the …
> Add `cast_unsigned` option in get_traces() 

- spikeinterface/postprocessing/correlograms.py
- spikeinterface/postprocessing/isi.py
- spikeinterface/postprocessing/template_similarity.py
- spikeinterface/postprocessing/unit_localization.py
- spikeinterface/widgets/crosscorrelograms.py
Using fancy indexing for >=2D data returns the actual values, not the slices.
Fixes mainly are for the `_specific_select_units` and for the crosscorrelogram widget
> Do not use fancy indexing for >=2D array

- spikeinterface/sorters/launcher.py
- spikeinterface/sorters/tests/test_launcher.py
@MarineChap : I started this.
Not tested for now.
Have a look and tell me.
> slurm launcher

- spikeinterface/core/old_api_utils.py
Sampling frequency is a float according to type hints in `BaseRecording`. However, some of the old extractor from spikeextractors contain sampling_frequency as an int (!) such as `se.OpenEphysRecordingExtractor`. This simple patch should remove this issue.
> Cast sampling frequency to float when converting extractors

- requirements_extractors.txt
- requirements_test.txt
- spikeinterface/extractors/extractorlist.py
- spikeinterface/extractors/neoextractors/__init__.py
- spikeinterface/extractors/neoextractors/edf.py
- spikeinterface/extractors/tests/common_tests.py
- spikeinterface/extractors/tests/test_neoextractors.py
I am adding a recording extractor that reads the European Data Format:
https://www.edfplus.info/
This is based on neo so is a neo extractor:
https://github.com/NeuralEnsemble/python-neo/blob/f62bd73bff79d84d3f4cca653b37c86064205a4e/neo/rawio/edfrawio.py
I also added tests trying to follow the format set up in the `test_neoextractors` file. 
This is the first time that I add one extractor so let me know what else is missing or could be improved.
Related to:
https://github.com/catalystneuro/neuroconv/issues/44
> Add `EDFRecordingExtractor` 

- spikeinterface/preprocessing/deepinterpolation/deepinterpolation.py
For parallel saving to work for `DeepInterpolatedRecording` by default, its preferred mp context should be set to `spawn`. Right now `_mp_preferred_context="spawn"` is defined outside of `DeepInterpolatedRecording.__init__`. This doesn't work because `DeepInterpolatedRecording` subclasses `BasePreprocessor` and calls `BasePreprocessor.__init__(self, recording)` inside its `__init__` to get properties like `sampling_frequency` and `channel_ids`. As a result, it inherits `_mp_preferred_context` from `BasePreprocessor` as well, which is by default `None` (defined all the way back in `BaseExtractor`). So even if you define `_mp_preferred_context='spawn'` outside of `__init__` of `DeepInterpolatedRecording`, you end up re-defining it when it is instantiated. 
This PR sets …
> Move `_preferred_mp_context` inside `DeepInterpolatedRecording. __init__ `

- spikeinterface/core/waveform_extractor.py
Fixed the warning "mean of empty slice" when computing the template of an empty unit.
Sets the template to all '0' in that case.
> Fix warning when computing template of empty unit

- spikeinterface/sorters/combinato/combinato.py
- spikeinterface/sorters/waveclus/waveclus.py
Hi, the issue #892 showed me that combinato and waveclus sorters have an issue related to scales. Internally they use write_to_h5_dataset_format to handle the data input to the sorters but the trace is saved unscaled in the file. My fix uses ScaleRecording before calling write_to_h5_dataset_format .
Cheers 
Fer
> fix combinato and waveclus sorters

- spikeinterface/core/core_tools.py
When saving to ZARR with parallel writing, somehow the RAM usage of each job kept increasing, causing out-of-memory error. 
After some debugging, I found that deleting the traces and forcing garbage collection fixes it. It's a patch, but it doesn't seem to affect speed..
> Patch memory leak when saving to Zarr

- spikeinterface/extractors/neoextractors/blackrock.py
- spikeinterface/extractors/neoextractors/neobaseextractor.py
In #856 I forgot to scale the timestamps of the spikes correctly. This small PR fixes that by scaling the timestamps of neo (which are usually in seconds) to frames.
I also did some small fixes to some of the docstrings in `neobaseextractor`.
> Correct time units for `BlackrockSortingExtractor`

- spikeinterface/extractors/neoextractors/ced.py
- spikeinterface/extractors/neoextractors/edf.py
- spikeinterface/extractors/neoextractors/nix.py
- spikeinterface/extractors/neoextractors/openephys.py
Defer to neo for format-specific requirements. Instead of specifying the ced requires sonpy, say it requires neo[ced] and let neo specify sonpy. The advantage of this is that you will always be up-to-date with the requirements of neo. If a library is added or removed for a format this will be automatically reflected in spikeinterface. I am also working with neo to make sure that it provides the appropriate hooks for this:
https://github.com/NeuralEnsemble/python-neo/pull/1154
> defer to neo for extractor requirements

- spikeinterface/widgets/ipywidgets/base_ipywidgets.py
If the `ipywidgets` backend is used, but `%matplotlib widget` is not set, raise an informative error
> Check matplotlib backend when using ipywidgets

- spikeinterface/postprocessing/spike_locations.py
- spikeinterface/widgets/ipywidgets/unit_waveforms.py
- spikeinterface/widgets/matplotlib/base_mpl.py
@samuelgarcia this fixes a bug that was caused by initializing the `axes` with `np.zeros`.
In case num_axes is odd, we still have to generate all `nrows * ncols` axes and then remove the excess ones (like it's done when not passing the figure). This bug was triggering an error because in other functions we assume (correctly) that all `axes` are mpl axes.
We should merge this and release 0.95.1 otherwise the `plot_unit_templates` and `plot_unit_waveforms` is broken.
Note that it worked when num_units is divisible by ncols.
> Fix axes generation when num_axes is odd and figure is passed

- spikeinterface/core/segmentutils.py
The `split_sorting` kwargs of the `parent_sorting` was missing a `to_dict()`
> Make split_sorting dumpable

- spikeinterface/core/unitsaggregationsorting.py
- spikeinterface/sorters/launcher.py
Fixes: https://github.com/SpikeInterface/spikeinterface/issues/931
Correct propagation of recording when using `run_sorter_by_property()`
> Fix recording propagation in run_sorter_by_property

- spikeinterface/core/waveform_extractor.py
- spikeinterface/qualitymetrics/pca_metrics.py
If PC metrics computation fails for a unit, set the metric to NaN
> Catch errors in PC metrics

- spikeinterface/core/base.py
In the case where the value is of dtype `object`, the default missing value should be `None`. Especially since the user cannot tell the function that he wants `None` to be the default value, as `missing_value=None` means that the missing value is inferred from the dtype.
> Missing values for dtype object should be None

- spikeinterface/core/waveform_extractor.py
@samuelgarcia this is conveninet to mimic the behavior of the waveform extractor when selecting units
> Add 'use_relative_path' param to WaveformExtractor.select_units()

- spikeinterface/comparison/basecomparison.py
- spikeinterface/comparison/collisioncomparison.py
- spikeinterface/comparison/comparisontools.py
- spikeinterface/comparison/correlogramcomparison.py
- spikeinterface/comparison/multicomparisons.py
- spikeinterface/comparison/paircomparisons.py
- spikeinterface/comparison/tests/test_comparisontools.py
- spikeinterface/comparison/tests/test_groundtruthcomparison.py
- spikeinterface/comparison/tests/test_multisortingcomparison.py
- spikeinterface/comparison/tests/test_symmetricsortingcomparison.py
This came up when running `remove_redundant_units` (which internally uses compare_two_sorters).
It just extends the logic of comparison to multi-segment objects, by looping through segments when needed
> Extend comparison to multi-segment sortings

- spikeinterface/postprocessing/principal_component.py
- spikeinterface/postprocessing/tests/test_principal_component.py
For `by_channel_local` and `by_channel_local` modes:
- restrict waveform fit and projection to channels in sparsity for each unit id
- sparsity doesn't need to have the same number of channels for each unit
For `concatenated` mode:
- in this case we check that the number of channels on the sparsity of each unit is the same (due to concatenation).
- No sparsity: > 30 min
- Sparsity (radius - 200um): < 3 min
-
> Implement sparse PCA

- spikeinterface/widgets/template_similarity.py
- Adds the `display_diagonal_values` (default `False`) to zero out values on diagonal of similarity plot (which are all ones...)
> Hide diagonal in similarity plot

- spikeinterface/widgets/amplitudes.py
This patch makes it possible to plot the `sorting_summary` for multi-segment object before it's an available option for sortingview.
> Use segment_index=0 as default in plot_amplitudes

- spikeinterface/comparison/collisioncomparison.py
Smallest PR ever. The CollisionStudy object is not wokring anymore for 1 segment. Ideally, it could be extended to several segments, but not need for now
> Fix for segments

- spikeinterface/widgets/amplitudes.py
- spikeinterface/widgets/ipywidgets/amplitudes.py
- spikeinterface/widgets/ipywidgets/spike_locations.py
- spikeinterface/widgets/ipywidgets/unit_locations.py
- spikeinterface/widgets/ipywidgets/unit_waveforms.py
- spikeinterface/widgets/matplotlib/amplitudes.py
- spikeinterface/widgets/matplotlib/spike_locations.py
- spikeinterface/widgets/matplotlib/unit_locations.py
- spikeinterface/widgets/spike_locations.py
- spikeinterface/widgets/template_similarity.py
- spikeinterface/widgets/unit_locations.py
Previously, the `plot_unit_locations` and `plot_spike_locations` were plotting a legend with ALL units (in grey) and only selected units in color. This clealy doesn't scale up with number of units.
Now only selected units are displayed in the legend. In addition, for the `ipywidgets` backend, the first available unit is selected at initiation.
Finally, added `max_spikes_per_unit` argument in `plot_spike_locations()` and `plot_amplitudes` to keep the plots manageable with long recordings and many units
> Fix labels and unit selection in widgets

- spikeinterface/extractors/hdsortextractors.py
> Fix deprecation warning for HDsortSortingExtractor

- spikeinterface/widgets/matplotlib/spikes_on_traces.py
The spikes_on_traces function is quite often leading to crashes, so here is a fix to prevent the problems with line display
> Fix spikes_on_traces

- spikeinterface/sorters/kilosortbase.py
- spikeinterface/sorters/utils/__init__.py
- spikeinterface/sorters/utils/misc.py
Hi,
This is required when running Kilosort if the user's default shell is Fish, otherwise matlab errors when calling `copyfile` during exporting to Phy.
Best
> Set MATLAB_SHELL to bash in kilosort shell cmd to work with Fish shell

- spikeinterface/extractors/phykilosortextractors.py
If `spike_clusters.npy` exists, then there is no use in loading `spike_templates.npy`.
> Don't load templates if not necessary

- spikeinterface/widgets/tests/test_widgets.py
- spikeinterface/widgets/timeseries.py
@samuelgarcia found the bug!!! For multiple layers, we were resorting the channel ids multiple times!
The plot then [loops through the `channel_ids`](https://github.com/SpikeInterface/spikeinterface/blob/master/spikeinterface/widgets/matplotlib/timeseries.py#L29)
Closes https://github.com/SpikeInterface/spikeinterface/issues/569
> Fix order_channel_by_depth with multiple layers

- spikeinterface/widgets/matplotlib/spike_locations.py
- spikeinterface/widgets/matplotlib/unit_locations.py
The show_legend flag is not used while it should. By the way, would it make sense to have a widget showing rates as function of time, for all cells? And/or the rates as function of the positions on the probe? Such widgets do not exists, do they?
> Fix `show_legend` flag in locations plots

- doc/index.rst
Placed overview image in `Overview of SpikeInterface module` and remove "scale" so it displays well
> Fix doc index.html image

- spikeinterface/core/__init__.py
- spikeinterface/core/recording_tools.py
- spikeinterface/core/tests/test_recording_tools.py
- spikeinterface/widgets/ipywidgets/timeseries.py
- spikeinterface/widgets/matplotlib/timeseries.py
- spikeinterface/widgets/sortingview/timeseries.py
- spikeinterface/widgets/timeseries.py
- spikeinterface/widgets/utils.py
- Fix bug of ordering channels **before** getting traces with channel ids
- Added `return_scaled` option in `plot_timeseries`
- Simplified `order_channels_by_depth` by first oreding x and then y (instead of ordering by distance to an arbitrary origin)
- Fixed channel selection in ipywidgets when channels are ordered
- Flipped y when order by depth both for line and map mode: now deepest channel is at the bottom
- Set default cmap for map mode to more  intuitive `RdBu_r` (from `RdBu`): blue is negative, red is positive
- For sortingview backend, do not display timeseries in jupyter (since it doesn't display)
> Fixes to plot_timeseries

- spikeinterface/extractors/neoextractors/neobaseextractor.py
`self.annotate(k=v)` results in the letter 'k' being used as key instead of the actual content of the variable `k`. Using `set_annotation` correctly uses the content of the variable `k` instead.
> use proper annotation key instead of 'k'

- spikeinterface/core/injecttemplates.py
Fixed a bug when `nbefore` was of type `np.int64`, it wasn't recognized as an integer.
> Fix bug in InjectTemplatesRecording

- spikeinterface/core/injecttemplates.py
If `parent_recording` is given, should use this dtype first instead of the dtype of `templates`.
> Use parent recording dtype for InjectTemplates

- spikeinterface/core/basesorting.py
- spikeinterface/core/tests/test_basesorting.py
Fixed a crash where `sorting.get_all_spike_trains()` or `sorting.to_spike_vector()` would result in a crash for empty sorting objects.
> Fixed crash with empty sorting

- spikeinterface/core/tests/test_waveform_extractor.py
- spikeinterface/core/waveform_extractor.py
Fixed a crash in `WaveformExtractor.run_extract_waveforms()` with an empty sorting.
> Fix crash wvf_extractor with empty sorting

- spikeinterface/core/core_tools.py
Instead of listing `(np.int32, np.int64)`, replaced with `np.integer` (and `np.floating`) to catch all possible values (int16, uint32 etc.)
> Fix bug 'int16' is not a JSON serializable

- spikeinterface/core/testing_tools.py
in favor of `core.generate`
Should fix:  https://github.com/catalystneuro/neuroconv/pull/208
> Smoother deprecation of `core.testing_tools`

- spikeinterface/sortingcomponents/clustering/clustering_tools.py
- spikeinterface/sortingcomponents/clustering/random_projections.py
I was teaching today, and I made a notebook where all the students had to use spykingcircus2. Turned out this was crashing on windows with some PermissionDenied Error for temporary files. I guess this fix might fix it, despite the fact that I do not have windows here to test that. Weird that tests passed, I thought the sorters were tested also with windows VM. Is it not the case?
> Fix for sc2 on windows

- spikeinterface/postprocessing/principal_component.py
- spikeinterface/postprocessing/spike_locations.py
Use direct calls to `waveform_extractor` methods.
`we.recording` is still needed for `run_for_all_spikes()`
> [feat-post] Support recordingless mode for PCA

- spikeinterface/curation/auto_merge.py
- spikeinterface/postprocessing/alignsorting.py
- spikeinterface/postprocessing/principal_component.py
- spikeinterface/postprocessing/spike_amplitudes.py
- spikeinterface/postprocessing/spike_locations.py
- spikeinterface/postprocessing/template_metrics.py
- spikeinterface/postprocessing/unit_localization.py
- spikeinterface/qualitymetrics/misc_metrics.py
- spikeinterface/qualitymetrics/pca_metrics.py
Moving `template_tools` to core created a bunch of warnings in the `postprocessing` submodule.
This hopefully fixes them all.
> Fixed template_tools warning in 'postprocessing'

- spikeinterface/widgets/sorting_summary.py
- spikeinterface/widgets/sortingview/base_sortingview.py
- spikeinterface/widgets/sortingview/sorting_summary.py
New Sortingview backend features and updates:
- Removed `TemplateSimilarityView` from `plot_sorting_summary` (it's not very useful)
- Unit table now uses `similarity_score` (and can sort selected unit by it)
- Option to pass `label_choices` for curation
Example here: https://figurl.org/f?v=gs://figurl/spikesortingview-10&d=sha1://7098c74b3901c8390ca2c85d2c13e8b04dfc3aab&label=SpikeInterface%20-%20Sorting%20Summary
> [feat-widgets] Updates for SV

- spikeinterface/core/npyfoldersnippets.py
This is needed to correctly map volumes when using Docker/singularity
> [bug-core] Use absolute folder in NpySnippetsFolder

- pyproject.toml
- spikeinterface/comparison/multicomparisons.py
- spikeinterface/comparison/tests/test_groundtruthstudy.py
- spikeinterface/comparison/tests/test_multisortingcomparison.py
- spikeinterface/comparison/tests/test_studytools.py
- spikeinterface/comparison/tests/test_templatecomparison.py
Tests are failing due to a networkx deprecation error: https://github.com/SpikeInterface/spikeinterface/actions/runs/3875551062/jobs/6608245287
Also see https://networkx.org/documentation/stable/release/migration_guide_from_2.x_to_3.0.html (Deprecated code)
This PR also cleans up tests for the comparison module to properly use cache folders.
> [bug-comparison] Fix networkx deprecation and clean up comparison tests cache

- spikeinterface/postprocessing/template_metrics.py
@samuelgarcia somehow this was not caught by our tests.
Basically in the template metrics we need to retrieve all templates, otherwise it's more difficult to estimate the correct max channel index
> [bug-postprocessing] Fix template metrics for sparse waveforms

- spikeinterface/extractors/neoextractors/openephys.py
- spikeinterface/extractors/tests/test_neoextractors.py
The open-ephys system saves both the sample indices and syncrhonized timestmps across streams (in s).
NEO only loads the start time from the sample indices.
This PR offers the option to load and set syncrhonized timestamps to the recording.
> [feat-extractors] Add option to load synchronized timestamps in OpenEphys

- spikeinterface/core/globals.py
- spikeinterface/core/sparsity.py
- spikeinterface/core/tests/test_globals.py
- spikeinterface/exporters/tests/test_export_to_phy.py
- spikeinterface/postprocessing/principal_component.py
- spikeinterface/postprocessing/template_metrics.py
- spikeinterface/postprocessing/tests/common_extension_tests.py
- spikeinterface/postprocessing/tests/test_principal_component.py
- spikeinterface/postprocessing/tests/test_template_metrics.py
- spikeinterface/postprocessing/tests/test_unit_localization.py
- spikeinterface/postprocessing/unit_localization.py
- spikeinterface/qualitymetrics/misc_metrics.py
- spikeinterface/qualitymetrics/pca_metrics.py
- spikeinterface/qualitymetrics/quality_metric_calculator.py
- spikeinterface/qualitymetrics/tests/test_quality_metric_calculator.py
- spikeinterface/widgets/tests/test_widgets.py
This PR solves several issues in the postprocessing and quality metrics modules.
- `set_global_job_kwargs()` updates existing global_kwargs with new entries
- sparsity by radius can work with waveform_extractor without recording
- propagated `compute_sparsity` instead of `ChannelSparsity.from_...` for better readability
- the `compute_principal_components` and `compute_metrics` can also use a subset of `job_kwargs`.
- changed the construction of the `pca_metrics_one_unit()` to already pass unit-specific pca scores and labels (including the target unit and its neighbor) and avoid reloading several times the pca files with calls to the `get_all_projections()` function.
- the PCA metrics have been refactored to use the new sparsity approach (either sparse waveforms, or an external …
> [fix-postprocessing/qm] Quality metrics and postprocessing fixes for sparsity and global job_kwargs

- spikeinterface/sorters/pykilosort/pykilosort.py
It seems that the IBL version of pykilosort requires a probe.sample2volt argument for the preprocessing steps. Otherwise I get this error in the spikesorting logs
`{
"sorter_name": "pykilosort",
"sorter_version": "ibl_1.4.1",
"datetime": "2023-01-19T17:44:43.361326",
"runtime_trace": [],
"error": true,
"error_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\Mammoth\\miniconda3\\envs\\pykilosort\\lib\\site-packages\\spikeinterface\\sorters\\basesorter.py\", line 230, in run_from_folder\n    SorterClass._run_from_folder(sorter_output_folder, sorter_params, verbose)\n  File \"C:\\Users\\Mammoth\\miniconda3\\envs\\pykilosort\\lib\\site-packages\\spikeinterface\\sorters\\pykilosort\\pykilosort.py\", line 180, in _run_from_folder\n    run(\n  File …
> [bug-sorters] Added sample2volt for IBL version of pykilosort

- spikeinterface/extractors/neoextractors/spikeglx.py
I'm adding this argument propagation to NeuroConv for better compatibility, especially with the new NIDQ interface
We're also trying to be better about matching docstrings with upstream projects
So suggesting some minor changes for this arguments docstring
> Minor docstring improvement for SpikeGLXRecordingExtractor

- spikeinterface/curation/auto_merge.py
Another option would be to make an argument `verbose`, but I don't really see the point in printing the steps.
> Make auto_merge less verbose

- spikeinterface/qualitymetrics/quality_metric_calculator.py
If `numba` is not installed, `rp_violations` return None and this is not caught by the `QualityMetricCalculator`.
Also fixes this: https://github.com/catalystneuro/neuroconv/pull/234#issuecomment-1406731807
> Protect against QM returning None

- spikeinterface/core/core_tools.py
Fixes #1226
@vncntprvst @samuelgarcia the problem was that the `recording_list` was not correctly accessed by the recursive path modifier used to find common parent folders. This fix simply loops through lists and checks if there are extractors there
> Correctly find parent folders for concatenate recording/sorting objects

- spikeinterface/widgets/_legacy_mpl_widgets/__init__.py
- spikeinterface/widgets/tests/test_widgets_utils.py
- spikeinterface/widgets/utils.py
I discoverd that distinctipy which is great is in fact very very slow!
17s to generate 250 colors.
Since the get_unit_colors is call at almost every plots. I put back matplotlib by default.
> Promote distinctipy color as a second choice because it is slow.

- spikeinterface/qualitymetrics/tests/test_metrics_functions.py
This is related to #1240. I also added another marker so this is ran whenever there is a change in sorting components to keep track of it.
> Pausing `test_calculate_drift_metrics` test

- spikeinterface/extractors/tests/test_neoextractors.py
I would like to run the test suit on my own system without the tests failing because I can't install `sonpy`. I propose to add a simple marker to skip the tests in newer platforms that will avoid this problem for everyone that wants to run test on their own personal systems and use python that is newer than 3.10.
What do you think?
P.D. Took the solution from neuroconv. Writing link here for provenance / reference:
https://github.com/catalystneuro/neuroconv/pull/102#discussion_r952486777
> skip `CedRecordingExtractor` test in systems with python.version > 3.8

- spikeinterface/preprocessing/remove_artifacts.py
The median/average rm artefact needs all traces at the beginning. Slicing channels moved at the end
> Fix slicing channels of remove artifact median/avg modes

- .github/workflows/caches_cron_job.yml
Related to https://github.com/SpikeInterface/spikeinterface/issues/1311.
This script should allow us to create the caches on master and from there I can propagate them to any created branches (so we don't have the duplication problem that we have now).  I already tested this on #1317 and it works correctly and as I expected. To test that the caches can be propagated to the other branches I need to have this in master. That is, I need this to be merged before I can proceed to address the problems described on #1311. 
This should close #1317 and is just a clean version of that one to avoid polluting the commit history.
> Create caches on master

- .github/workflows/caches_cron_job.yml
- .github/workflows/core-test.yml
- .github/workflows/full-test-with-codecov.yml
- .github/workflows/full-test.yml
- .github/workflows/publish-to-pypi.yml
- .github/workflows/s3-nwb-test.yml
Related to #1311. 
This PR introduces two futher things:
1) The caches are not modified by PRs from the branches (only checked-out but not modified) so we don't fill the quota.
2) Everytime a PR is merged the action that creates the caches on master will check if new caches are necessary.
> Make caches on branches read only

- spikeinterface/sortingcomponents/benchmark/benchmark_motion_correction.py
- spikeinterface/sortingcomponents/matching/main.py
- spikeinterface/sortingcomponents/matching/naive.py
- spikeinterface/sortingcomponents/motion_correction.py
- spikeinterface/sortingcomponents/peak_detection.py
- spikeinterface/sortingcomponents/peak_pipeline.py
- spikeinterface/sortingcomponents/tests/test_peak_detection.py
- spikeinterface/sortingcomponents/tests/test_peak_pipeline.py
- spikeinterface/sortingcomponents/tests/test_peak_selection.py
- spikeinterface/sortingcomponents/tests/test_template_matching.py
Within the scope of #1235. 
A continuation of #1272 as rquested by @samuelgarcia 
Removing the rest of the `to_dict` mechanisms for the recording extractors
> Remove the rest of to_dict mechanisms from sorting components

- doc/conf.py
- spikeinterface/core/sparsity.py
Fixes #1332 
See [here](https://github.com/sphinx-doc/sphinx/issues/11094) for a discussion of the issue and solution.
I also cleaned up one of the docstrings that I noticed wasn't rendering properly.
> Fixes Bug that was preventing sphinx>=6.0.0 to render documentation properly

- spikeinterface/core/base.py
- spikeinterface/core/recording_tools.py
fixes #1333
there was a bug when using `ids_to_indices` with `ids=None` (which normally is not used)
> Fix ids_to_indices when channel_ids is None

- .github/workflows/caches_cron_job.yml
I forgot to fix the installation method for datalad git-annex (I was using auto which sometimes uses conda instead of the recommended method). This one line change fixes that.
> Use fix installation method for datalad git-annex

- README.md
- pyproject.toml
Sonpy is not supported for Python>=3.10. SpikeInterface requires >=3.8.
(also fixed a small typo in the README)
> Fix sonpy dependency

- spikeinterface/core/recording_tools.py
Wonder if SI would consider extending the API of `get_random_data_chunks` in some way along these lines? Use case: for instance when calling `si.zscore()`, we can exclude the border to avoid issues at the edge of the recording -- that could be helpful for other functions as well, like estimating noise levels. I also considered parameterizing by `min_frame/max_frame`, but that doesn't generalize as well across segments.
> Add a margin parameter to get_random_data_chunks

- spikeinterface/core/base.py
Some cloud storage systems do not allow to store empty folders. If a SI object without properties (quite common for sorting objects) is saved, then the `properties` sub-folder disappears.
This simple PR checks if the `properties` folder exists before looping through it
> Allow to load objects when 'properties' folder is missing

- .github/workflows/full-test-with-codecov.yml
- .github/workflows/full-test.yml
- pyproject.toml
- spikeinterface/core/tests/test_waveform_extractor.py
- spikeinterface/core/waveform_extractor.py
- spikeinterface/preprocessing/tests/test_highpass_spatial_filter.py
For the long-term project of improving coverage on core I wanted to see what type of warnings we were getting. This PR is the results of that. On it, the following things are done:
* Filter the warnings for deprecation of `distutils` and `imp` clasess which are used in some packages down the line and are non informative as we can't do anything about them (they come from datalad, setuptools and boto).
* Remove some deprecated use cases in our own library. One test is used the old testing module and the other is used a deprecated argument for the waveform extractor.
> Remove some deprecation warnings

- doc/modules/qualitymetrics/amplitude_cutoff.rst
- doc/modules/qualitymetrics/amplitude_median.rst
- doc/modules/qualitymetrics/drift.rst
- doc/modules/qualitymetrics/firing_rate.rst
- doc/modules/qualitymetrics/isi_violations.rst
- doc/modules/qualitymetrics/isolation_distance.rst
- doc/modules/qualitymetrics/l_ratio.rst
- doc/modules/qualitymetrics/nearest_neighbor.rst
- doc/modules/qualitymetrics/presence_ratio.rst
- doc/modules/qualitymetrics/sliding_rp_violations.rst
- doc/modules/qualitymetrics/snr.rst
doc/modules/qualitymetrics
I just fixed a few typos for these other than isolation distance, which used a lot of 'unit' terminology mixed with 'cluster'. In my commit for that file I explain my logic for regularizing it all to 'cluster', but let me know if that needs fixes. 
I've got a bunch of data analysis to do tomorrow, so I'll hop onto the next round of docs next week, but when I get comments I can do updates for this request this weekend.
> Improve Documentation - III

- doc/api.rst
- doc/modules/curation.rst
- spikeinterface/core/recording_tools.py
- spikeinterface/core/waveform_extractor.py
- spikeinterface/core/waveform_tools.py
- spikeinterface/curation/__init__.py
- spikeinterface/curation/remove_excess_spikes.py
- spikeinterface/curation/tests/test_remove_excess_spikes.py
Sometimes KS returns spikes outside the number of samples. 
This PR:
- asserts that this is not the case when extracting waveforms
- implements a curation function `remove_excess_spikes` that filters out these extra spikes
> Add function to remove excess spikes

- pyproject.toml
- spikeinterface/sorters/utils/misc.py
This is related to #705 and once we are done with this it probably should be closed.
This method works on dandi-hub when I tested it a while ago, the only problem is that it requires a dependency:
https://nvidia.github.io/cuda-python/overview.html
I am also not sure how to add this as a dependency.
What do you think?
> Robust method for checking gpu-nvidia availability

- spikeinterface/preprocessing/clip.py
Hi,
I found a typo while using the `preprocessing.clip`: when setting its `_kwargs`, the `a_min` property is set to `a_max` by accident. This typo has no effect when objects stay in memory; however, if the `ClipRecording` object is dumped to JSON and read from disk again (such as when we [run sorter from folder using MountainSort4](https://github.com/SpikeInterface/spikeinterface/blob/master/spikeinterface/sorters/external/mountainsort4.py#L91)), this causes the return of `get_trace()` to be a constant value.
Thanks!
> fix typo in class ClipRecording

- .github/workflows/core-test.yml
- pyproject.toml
- spikeinterface/core/baserecording.py
- spikeinterface/core/generate.py
- spikeinterface/core/tests/test_generate.py
Recently we had some memory issues: #1234
As @samuelgarcia pointed out, this is more likely the result of [known problems](https://github.com/numpy/numpy/issues/13510) with memmap in numpy and we are discussing long-term solutions to this. 
That said, memory problems come both from reading and writing. We write recorder objects for many reasons including long-term storage, serialization, marshalling and reading from docker. The aim of this PR is to introduce a testing tool for memory related problems while writing `LazyRandomRecording`. 
The `LazyRandomRecording` generates traces samples of any desired size and structure on the fly. That is, it does not read and should not keep a reference to the data. In general, it can be used to stress-test the processing and writing parts of any …
> Add `GeneratorRecording` for testing and diagnosing memory issues

- spikeinterface/postprocessing/tests/test_correlograms.py
@alejoe91 mentioned that this is a test that constantly fails. I added some determinism to the tests. Plus, I think it is easier to test for the location of the peak (which should match the delta of the injected noise) instead of the maximum of the peak (tbh, I had a hard time interpreting why should the peak_value should be around `np.median(cc_01) * 0.7 + num_injected_spikes`).
What do you think? 
I
> Refactor `test_detect_injected_correlation`

- spikeinterface/core/frameslicerecording.py
- spikeinterface/core/frameslicesorting.py
- spikeinterface/core/tests/test_frameslicesorting.py
Hi
In FrameSliceSorting:
If None (default), the end_frame is now either:
- The total number of samples, if a recording is assigned to the sorting
- The maximum spike frame + 1, otherwise
This ensures that `Sorting.frame_slice(start_frame=None, end_frame=None)` not only 
returns all the spikes (as previously), but also that the sortings' registered recording remains complete.
Note that the following configs are now legal (and return empty sortings)
- `start_frame < end_frame <= min_spike_time`
- `max_spike_time < start_frame < end_frame`
> Change default value for end_frame in FrameSliceSorting

- spikeinterface/core/recording_tools.py
- spikeinterface/preprocessing/average_across_direction.py
- spikeinterface/preprocessing/depth_order.py
- spikeinterface/preprocessing/detect_bad_channels.py
- spikeinterface/preprocessing/directional_average.py
- spikeinterface/preprocessing/directional_derivative.py
- spikeinterface/preprocessing/normalize_scale.py
- spikeinterface/preprocessing/preprocessinglist.py
- spikeinterface/preprocessing/resample.py
- spikeinterface/preprocessing/tests/test_average_across_direction.py
- spikeinterface/preprocessing/tests/test_depth_order.py
- spikeinterface/preprocessing/tests/test_directional_derivative.py
- spikeinterface/preprocessing/tests/test_resample.py
- spikeinterface/preprocessing/zero_channel_pad.py
Hi @samuelgarcia , here is a small draft PR with two preprocessing tools: a simple one (`depth_order`) which will save me a lot of typing, and one for averaging across channels at the same depth (or a dimension other than depth, `average_across_direction`). I'm curious if I have done all of the metadata bookkeeping as you would have done.
Let me know your thoughts -- once I'm going in the right direction I'll add something like a `directional_derivative(recording, direction='y', order=2)` for computing spatial derivatives.
> Add some preprocessing tools (general and LFP-oriented)

- .github/workflows/full-test.yml
- spikeinterface/core/baserecording.py
- spikeinterface/core/core_tools.py
- spikeinterface/extractors/tests/test_iblstreamingrecording.py
The full tests are failing on master. This PR is meant to address it.
The reason:
After the `__repr__` was modified to also display the memory of the full traces https://github.com/SpikeInterface/spikeinterface/pull/1452 the extractor tests were not triggered. The extractor tests for IBL has a repr tests that failed.
This PR does the following:
1) It adds a check so modifications on master trigger the extractor tests. This makes sense to me as this omission allow this failure to slip through.
2) Fixes the tests for IBL.
3) Add `dtype` to the `__repr__`, something that @samuelgarcia mentioned but I forgot in #1452 . 
4) I also expanded the docstring of the method that I used in `__repr__` I had in a commit that did not go through on #1452.
> Fix IBL tests on master

- spikeinterface/widgets/utils.py
This bug is due to a rounding of the traces shape when applying the zoom for the sortingview backend.
Fixed by grabbing the correct shapes after applying the zoom
> Fix sortingview timeseries bug

- doc/index.rst
- doc/install_sorters.rst
- doc/modules/comparison.rst
- doc/modules/curation.rst
- doc/modules/exporters.rst
- doc/modules/extractors.rst
- doc/modules/postprocessing.rst
- doc/modules/preprocessing.rst
- doc/modules/sorters.rst
- doc/modules/sortingcomponents.rst
- doc/modules/widgets.rst
As briefly mentioned in #1380 the main goal for this round was to unify capitalization of SpikeInterface and some of the other packages (the various sorters, NVIDIA, CUDA, Docker). I also tried to fix a few more typos I missed in my previous passes. Just let me know if you want to revert any of the capitalizations.
> Improve Documentation V

- spikeinterface/widgets/matplotlib/timeseries.py
Just a small suggestion, when first using plot_timeseries (matplotlib backend) I was a little confused by the y-axis numbers and their relationship to channels, until I saw the `show_channel_ids=True` option.
If I understand correctly, the y-axis values on the plots are arbitrary if channel ids are not shown. If so, it just be nice to just hide them as proposed in this PR (images below)
before PR (map):
after PR (map):
before PR (line):
after PR (line):
> Hide Y axis when plot_timeseries without channel labels

- src/spikeinterface/qualitymetrics/pca_metrics.py
Hi again,
When computing `nn_isolation`, return the nearest neighbor of each unit used to compute the isolation score
This is useful for sanity checks.
I don't think this should affect the tests.
Best
> Return `nn_unit_id` along with `nn_isolation`

- src/spikeinterface/core/datasets.py
- src/spikeinterface/sortingcomponents/peak_localization.py
- src/spikeinterface/sortingcomponents/peak_pipeline.py
- src/spikeinterface/sortingcomponents/tests/test_waveforms/test_temporal_pca.py
- src/spikeinterface/sortingcomponents/tests/test_waveforms/test_waveform_thresholder.py
- src/spikeinterface/sortingcomponents/waveforms/neural_network_denoiser.py
- src/spikeinterface/sortingcomponents/waveforms/savgol_denoiser.py
- src/spikeinterface/sortingcomponents/waveforms/temporal_pca.py
- src/spikeinterface/sortingcomponents/waveforms/waveform_thresholder.py
PR redone after synced with main. Several points:
- I can not launch test anymore with pytest, is it normal? It used to work but now it complains about conftest.py
- I think that all PipelineNode that will work on waveforms (and thus transform waveforms) should inherit from WaveformNode instead of PipelineNode, ensuring they have at least one WaveformExtractor in their parents. This make sense, and allow these nodes to inherits from the attributes of their parents (ms_before, ms_after) that might be required by downstream node. This is done here for the SavGol filter, but I think this should also be done for all the denoisers
> Adding a WaveformThresholder

- .github/actions/build-test-environment/action.yml
- .github/actions/show-test-environment/action.yml
- .github/workflows/full-test-with-codecov.yml
- .github/workflows/full-test.yml
Testing to see if this solves the non-deterministic failure to read test environment. 
Edit: OK, this works. I think that github changed his policy on where the operator points so we needed to be specific with this.
> Use context variables in github actions

- doc/installation.rst
- setup.py
Warn the user when using `setup.py` for installation as it is now the legacy way of installing SpikeInterface.
> Warning that `setup.py` is legacy

- src/spikeinterface/core/base.py
- src/spikeinterface/core/core_tools.py
- src/spikeinterface/core/tests/test_jsonification.py
Temporary branch for debugging error #1525 and possible #1526.
Edit I: OK. I am waiting for @DradeAW to confirm if this solves issue #1525 but I think it should. 
I added tests to cover the error which was generated by our encoder not going into extractors instances that are nested in other extractors and removing the numpy scalars from them. 
I added the tests, I saw that they were failing and the modified the code so they pass. Once @DradeAW confirms that this works I will remove the log and this will be ready to merge.
Edit II: OK, this is ready now.
> Add tests for json encoding of nested numpy scalars 

- src/spikeinterface/exporters/tests/test_export_to_phy.py
- src/spikeinterface/exporters/to_phy.py
Fixes a crash in `export_to_phy` when `copy_binary=False`.
> Fix crash in `export_to_phy`

- src/spikeinterface/postprocessing/spike_amplitudes.py
Without this check, there will just be a crash later on (after having created the `spike_amplitudes` folder). Thus, if the user re-runs with a correct `WaveformExtractor`, there will be a crash because the module will try to load an empty folder.
I think the simplest way to avoid problems like this is the check form the beginning if the `WaveformExtractor` object contains a recording object.
> Check wvf_extractor with recording for spike amplitudes

- doc/modules/qualitymetrics/references.rst
- doc/modules/qualitymetrics/silhouette_score.rst
- src/spikeinterface/qualitymetrics/pca_metrics.py
- src/spikeinterface/qualitymetrics/quality_metric_list.py
- src/spikeinterface/qualitymetrics/tests/test_metrics_functions.py
First Tom's PR #1499 will need to be merged before this can be done, so I can update to get rid of the merge conflicts. So I'll leave this as a draft until that's done.
Working on the docs I saw that silhouette score had not been implemented. So I implemented it two different ways and was hoping for feedback (if you guys want it implemented in SI--otherwise I can delete it). First is the simplified silhouette score proposal here: https://ieeexplore.ieee.org/document/1410321, which uses centroids rather than pairwise point calculations
Pros:
It is computationally and space-wise o(kn) rather than o(kn2). 
Cons:
Literature is less developed (and was proposed for genomics purposes) and technically doesn't use all info available
And the original silhouette score as proposed by Rousseeuw.
Pros: …
> Add silhouette score quality metric

- doc/index.rst
Adresses this point:
https://github.com/SpikeInterface/spikeinterface/discussions/1062
> Fix wrong path in read the docs 

- src/spikeinterface/comparison/multicomparisons.py
Reuse of the variable name `unit_id` in the method `_populate_spiketrains` was leading to incorrect `get_agreement_sorting` outputs which are described in issue  https://github.com/SpikeInterface/spikeinterface/issues/1547. Changing `unit_id` to `this_sorting_unit_id` in the appropriate locations should fix this. https://github.com/SpikeInterface/spikeinterface/blob/1bd169fc19673c60b7335d51ff38f758fd1fcc78/src/spikeinterface/comparison/multicomparisons.py#L97-L98
In the plots below, blue are spiketimes identified by KiloSort2, orange are from MountainSort4, and green are supposed to be the intersection of these spiketrains.
Before the fix:
After the fix:
> Fix MultiSortingComparison._populate_spiketrains to prevent overwriting agreement sorting spiketrains

- doc/contribute.rst
- doc/how_to/get_started.rst
- doc/install_sorters.rst
- doc/modules/sorters.rst
- installation_tips/full_spikeinterface_environment_mac.yml
- src/spikeinterface/sorters/external/mountainsort4.py
- src/spikeinterface/sorters/external/mountainsort5.py
- src/spikeinterface/sorters/external/tests/test_singularity_containers.py
- src/spikeinterface/sorters/runsorter.py
- src/spikeinterface/sorters/sorterlist.py
Adding a new version of mountainsort spike sorter. See https://github.com/magland/mountainsort5
The structure of the sorting parameters is a bit more complicated than for mountainsort4 because the algorithm is available in three different schemes (scheme1, scheme2, scheme3) -- see the above link. Each scheme has its own set of parameters. So for the SpikeInterface wrapper, I flattened the structure... see mountainsort5.py. Depending on which scheme is selected, different parameters will take effect (and others will be ignored).
> Add mountainsort5 sorter

- src/spikeinterface/sortingcomponents/peak_detection.py
- src/spikeinterface/sortingcomponents/tests/test_peak_detection.py
I am hunting a bug in torch but this should be changed anyway so I am pushing it now. This fixes a bug where Torch returns numpy arrays (it should be tensors) when no peaks are found at any stage of the peak detection pipeline. It also, adds logic to the `PeakDetectorWrapper` to handle this issue.
> Fix torch detector for case when non peaks are found

- src/spikeinterface/core/recording_tools.py
- src/spikeinterface/core/tests/test_recording_tools.py
The tests added in #1548 are failing on windows. I think this is because of an overly restrictive assertion here:
https://github.com/SpikeInterface/spikeinterface/blob/9ea8f92f8d14661cdd84f9569dbde24f12383e08/src/spikeinterface/core/tests/test_recording_tools.py#L40
As the trick we do with MAD is an estimation of the real std.  
However, this is not clear because the previous test was not deterministic. I have added determinism to the test and did some refactoring for cleaning. If the error persists in windows I will lower the tolerance.
EDIT: The test works as expected once determinism is added. This is ready to go.
> Fix failing noise test on windows

- src/spikeinterface/sorters/utils/misc.py
Added an helpful error message for the user in case he tries to run a sorter dockerized without `cuda-python` installed in the environment.
> Added helpful error message if `cuda` missing

- src/spikeinterface/sortingcomponents/peak_detection.py
- src/spikeinterface/sortingcomponents/tests/test_peak_detection.py
This tests indicates the error for peak detection methods that use torch. Somehow when peak_sign is equal both for this method torch comes empty handed. That is, no peaks are detected and hence the tests fail.
The tests is simple. Itcalculates peaks with positive sign, peaks with negative sign and then all peaks. It asserts that total should be the sume of positive and negative.
> Sign consistency test in peak detection

- pyproject.toml
Hey All,
I believe `numba` should be on the `[full]` section of the pyroject.toml as it is required to calculate the quality metrics after spike sorting [here](https://github.com/SpikeInterface/spikeinterface/blob/9ea8f92f8d14661cdd84f9569dbde24f12383e08/src/spikeinterface/qualitymetrics/misc_metrics.py#L26). Apologies if I have misunderstood!
Cheers,
Joe
> Update pyproject.toml to include numba in full installation

- src/spikeinterface/preprocessing/remove_artifacts.py
When removing artifacts, an IndexError error occurs if the start/end of the artifact occurs near the boundaries of the current data block. This pull request fixes the code that was supposed to account for the boundaries.
File ".../spikeinterface/core/core_tools.py", line 209, in _write_binary_chunk
traces = recording.get_traces(start_frame=start_frame, end_frame=end_frame, segment_index=segment_index,
File ".../spikeinterface/core/baserecording.py", line 160, in get_traces
traces = rs.get_traces(start_frame=start_frame, end_frame=end_frame, channel_indices=channel_indices)
File ".../spikeinterface/preprocessing/remove_artifacts.py", line 306, in get_traces
median_vals = np.median(traces[idxs, :], axis=0, keepdims=True)
File ".../numpy/core/memmap.py", line 334, in __getitem__
res = …
> Fixed IndexError when interpolating artifacts

- src/spikeinterface/postprocessing/unit_localization.py
- src/spikeinterface/sortingcomponents/matching/circus.py
- src/spikeinterface/sortingcomponents/peak_localization.py
- src/spikeinterface/sortingcomponents/tests/test_peak_localization.py
- src/spikeinterface/sortingcomponents/tests/test_waveforms/test_waveform_thresholder.py
- src/spikeinterface/sortingcomponents/tools.py
- src/spikeinterface/sortingcomponents/waveforms/waveform_thresholder.py
After discussing with Samuel, we've decided to change the name v_peak to something more explicit (peak_voltage). In addition, I've modified an util function for GridLocalization to remove a deprecation warning, and I've also modified the WaveformThresholder object to not assume data are whitened. 
@samuelgarcia @alejoe91 @h-mayorquin Regarding the noise_levels, this would really be helpful if they could be attached to the recording object, in order to avoid duplicated computations all over the places (in sparsities, in thresholder, in matching engines, ...). I know that know they can be attached to waveform_extractor, and this is a good step, but to me these noise levels are really at the recording level
> Change v_peak name and thresholder behavior

- src/spikeinterface/core/base.py
- src/spikeinterface/core/tests/test_baserecording.py
With this PR one can do:
```
recording = si.load_extractor("recording.zarr")
```
Plus, when using the `save(format="zarr")` function the output is reloaded with `read_zarr()` function, so that it gets all properties and annotations right.
> Extend load_extractor to load zarr and fix zarr annotations

- pyproject.toml
- src/spikeinterface/extractors/nwbextractors.py
OK, so #1597 turn out too big as there were a lot of imports that were exposed naively. I am passing the small patch to fix the import with pynwb here as that one will probably take longer to reivew. 
Copying PR text verbatim from here:
This PR resolves #1596.
As described in the issue, importing extractors fails when pynwb is not installed. The problem arises from the newly added type-hints, which are currently evaluated at import time.
PR #1593 suggests a solution that employs forward references, where type hints are defined as strings to force deferred evaluation. While this approach works, we can improve upon it.
Starting with Python 3.8, we can use the following statement at the top of a module to defer the evaluation of type annotations until runtime:
```python
from __future__ …
```
> Use annotations from future (PEP563) to solve type hint references

- src/spikeinterface/core/tests/test_waveform_extractor.py
- src/spikeinterface/core/waveform_extractor.py
This solves #1595, with the addition of a force_dense flag in both get_waveforms and get_templates.
> Force_dense mode for waveforms and templates

- src/spikeinterface/curation/auto_merge.py
Added the list of pairs removed before there wasn't an increase in score in the `auto_merge` function in the extra_outputs.
> Add pairs with decreased score to auto_merge output

- src/spikeinterface/core/recording_tools.py
- src/spikeinterface/core/tests/test_waveform_extractor.py
- src/spikeinterface/core/waveform_extractor.py
- src/spikeinterface/core/waveform_tools.py
I need to load multiple wvf_extractor with the same `recording` object, to then compute the amplitudes.
For that, I cannot use `with_recording=False`, but if I set it to `True`, then it will load the same recording tens of times (which takes time and RAM).
I'd like the possibility to use `with_recording=recording`.
Thanks :)
> Allow to set the recording of `WaveformExtractor`

- src/spikeinterface/extractors/tests/test_iblstreamingrecording.py
There seems to be problems with IBL and one and the test is failing everywhere right now. Trying this patch to skip the test when that is the case.
> Skip streaming test of IBL when server is down.

- src/spikeinterface/qualitymetrics/misc_metrics.py
So as it turns out, `np.int32 * int = np.int64` on Linux to get behind on overflow error, but defaults to `np.int32` in Windows. This leads to an erroneous `D` in Windows with big units.
Changing the dtype to `int64` should fix all problems.
> Fix dtype bug in Windows for `spost.compute_refrac_period_violations`

- src/spikeinterface/postprocessing/unit_localization.py
- src/spikeinterface/sortingcomponents/peak_localization.py
- src/spikeinterface/sortingcomponents/tools.py
After discussing with Sam, and while playing with benchmarks for drift correction, looks like this could be useful to only keep the best scalar products while estimating the position
> Adding percentile as an option for grid localization

- installation_tips/full_spikeinterface_environment_mac.yml
- src/spikeinterface/sorters/external/mountainsort5.py
Version 0.3.x of mountainsort5 has a major improvement which greatly reduces the number of false splits. This PR is to upgrade to that version in SpikeInterface. There were a couple of parameter changes, but that should not affect the tests or basic usage.
> update to mountainsort5 0.3.x

- src/spikeinterface/curation/curationsorting.py
- src/spikeinterface/curation/tests/test_curationsorting.py
Right now it's not possible to do `CurationSorting.merge([1, 2], new_unit_id=1)`, and it should be possible
> Allow `new_unit_id` to be same id in `CurationSorting.merge`

- src/spikeinterface/curation/auto_merge.py
Use the given censored period rather than the default 0.4ms when merging units.
Also sets a default censored period != 0
> Use censored_period when merging units in `scur.merge_units`

- doc/modules/core.rst
- src/spikeinterface/curation/mergeunitssorting.py
Couldn't load `MergeUnitsSorting` from json because of a typo in `kwargs`
> Fixed crash when loading `MergeUnitsSorting`

- src/spikeinterface/extractors/iblstreamingrecording.py
- src/spikeinterface/extractors/matlabhelpers.py
- src/spikeinterface/extractors/nwbextractors.py
- src/spikeinterface/extractors/tridesclousextractors.py
I was profiling something and discussing with @alejoe91 today and we realize that the following imports are not lazy:
* Tridesclous
* Pynwb
* one.api import ONE
I am making them lazy here.
> Make NWB imports lazy

- src/spikeinterface/core/base.py
This was a rabit hole.
OK, so this is the solution that is performing the best now:
```
results for branch fix_loading_pickle [This branch]
Time elapsed for saving: 0.0029435157775878906
Time elapsed for loading: 0.03637957572937012
Memory used by loading: 1.03125 MiB
Peak memory usage: 684.25390625 MiB
```
What was making loading and the [benchmark](https://gist.github.com/h-mayorquin/72f492275767fa9f2cb77a0b117eea67) very slow for loading was the deep copy.
As discussed on the other PR https://github.com/SpikeInterface/spikeinterface/pull/1622#issuecomment-1562000001 the other approaches are terrible in their loading and memory footprint performance. This approach is just better overall, saving, loading and memory usage.
> Fix pickle loading

- src/spikeinterface/extractors/neoextractors/neuroscope.py
- src/spikeinterface/extractors/tests/common_tests.py
- src/spikeinterface/extractors/tests/test_neoextractors.py
The neo reader for Neuroscope supports indicating the xml_file_path that is used to extract the metadata. The option, however, has not been propagated to spikeinterface. This PR solves that.
> Add xml_file_path option to Neuroscope

- src/spikeinterface/comparison/paircomparisons.py
`postprocessing.template_similarity.compute_template_similarity` seems to have changed the way it accepts the second waveform extractor as an argument but `TemplateComparison` was not updated to reflect this. This causes an error when the two waveform extractors have different number of units. There may be other errors like this in the comparison module.
> Fix cosine similarity matrix in `TemplateComparison` 

- src/spikeinterface/curation/remove_duplicated_spikes.py
Fixes a bug in `remove_duplicated_spikes` that throws an error if the unit is empty (no spikes).
> Fixed bug in `remove_duplicated_spikes`

- src/spikeinterface/curation/remove_excess_spikes.py
Use `numpy.searchsorted` to accelerate the process.
> Optimization of `curation.RemoveExcessSpikeSorting`

- src/spikeinterface/extractors/phykilosortextractors.py
**Problem** 
As seen in #1690 splitting in Phy leads to some problems for SI. Phy has two main actions merges which delete two rows of the `cluster_info` tsv/csv and creates a new row (which should) create a nan for the `si_unit_id`. In the case of splits however it takes one row in the tsv and copies it to two new rows with every column except `cluster_id` and `n_spikes` being the same value as the previous single row. Thus the `si_unit_id` is also duplicated in the case of splits.  This issue will only occur after the user has done any SI work because the only way the `si_unit_id` can be duplicated is if it already exists. So performing sorting/Phy outside of SI and doing splitting wouldn't cause this issue if trying to extract an old dataset.
**Potential Solution**
I've put one …
> Allow PhyExtractor to handle splits from Phy

- src/spikeinterface/core/base.py
I need to dump to pickle with `relative_to`, but for that to apply to all parents I also need to set `recursive=True`
See https://github.com/SpikeInterface/spikeinterface/issues/1689#issuecomment-1598660344
> Expand `recursive` to `dump_to_pickle`

- src/spikeinterface/core/base.py
The `recursive` parameter isn't given to the children, and thus doesn't apply after the first parent.
> Fixes `to_dict(recursive)` that isn't recursive

- src/spikeinterface/curation/auto_merge.py
Fixed a bug where `auto_merge` would crash if the sorting object has no units. Removed unused import.
> Fix bug in `auto_merge` with no units

- src/spikeinterface/core/base.py
- src/spikeinterface/preprocessing/tests/test_normalize_scale.py
Since `_make_paths_relative` is already recursive, setting `relative_to=` recursively means that for parents, it will be applied twice which can cause a wrong path.
As you can see in the following example (where some prints were added):
```
sorting.select_units([0, 1]).to_dict(relative_to=base_folder, recursive=True)
>>> /export/home1/users/nsr/wyngaard/Documents/lussac2/tests/datasets/cerebellar_cortex/lussac/logs/merge_sortings/CS/merged_sorting.npz -> merge_sortings/CS/merged_sorting.npz  # Correct transformation.
>>> merge_sortings/CS/merged_sorting.npz -> ../../../../../merge_sortings/CS/merged_sorting.npz  # Second transformation breaks the path!
```
Thanks @alejoe91 for helping me debug this!
This PR fixes #1731.
> Fix bug with `to_dict(recurvise, relative_to)`

- src/spikeinterface/exporters/to_phy.py
Fixes annoying warning from my IDE telling me that `output_folder` needs to be a `str`, not `Path`
> Added typing to `export_to_phy`

- src/spikeinterface/sorters/basesorter.py
Fixes the sorter `runtime_trace` in the log
> Point to correct folder to get runtime_trace from sorter

- src/spikeinterface/core/numpyextractors.py
I used this trick in a conversion recently. I am propagating it here in the unlikly case somebody needs in the future. This decouples the lenght of the recorder from the traces and gives and attribute for the number of samples (I needed to access that without making refence to traces).
This should keep the original API contract and make this a little bit more flexible.
> small refactor to `NumpyRecording` to make it more hackable

- doc/api.rst
- doc/modules/preprocessing.rst
- src/spikeinterface/preprocessing/astype.py
- src/spikeinterface/preprocessing/preprocessinglist.py
- src/spikeinterface/preprocessing/tests/test_astype.py
- src/spikeinterface/preprocessing/tests/test_unsigned_to_signed.py
- src/spikeinterface/preprocessing/unsigned_to_signed.py
Fixes #1702 so you can do the following for a recording of typoe unsigned:
```
rec_int16 = rec_uint16.astype("int16")
```
Internally, it takes care of upcasting and removing the `2**(nbits-1)` offset before adding the sign (to avoid overflow errors).
Also added some tests ;)
> Deal with unsigned int to int conversion

- src/spikeinterface/core/binaryrecordingextractor.py
- src/spikeinterface/core/tests/test_binaryrecordingextractor.py
Larger change than #1741. Can be merged after or instead of it.
Uses native memmaps instead and adds an extra test.
Similar approach as the one used in https://github.com/SpikeInterface/spikeinterface/pull/1741.
> Make binary recording memmap efficient II (using native memmaps)

- src/spikeinterface/core/baserecording.py
Recording segments have a dictionary characterizing their timing properties:
https://github.com/SpikeInterface/spikeinterface/blob/5369cb0e799a52a1ccb1de6feacf05c41f65dd95/src/spikeinterface/core/baserecording.py#L660-L663
Recently, we have been working on time alignment in neuroconv. For data ingestion / extraction is very useful to have this information available from the recoder.  This is what this PR does. It creates a new method at the `BaseRecording` level that returns the information witt the usual logic of working directly for single segment and requiring segment specification for multiple segment. 
The idea is that the segments should be an implementation detail and that users should not have to dig into them to extract timing information if so they desire.
I also added more …
> Propagate `get_times_kwargs` to BaseRecording

- src/spikeinterface/core/waveform_tools.py
Fix SharedMem warning/errors
This avoid `"UserWarning: resource_tracker: There appear to be XX leaked shared_memory objects to clean up at shutdown"` we have we extracting waveforms into shared memmory with multiprocessing.
> Fix SharedMem warning/errors

- src/spikeinterface/core/core_tools.py
- src/spikeinterface/sorters/external/kilosortbase.py
This is necessary for #1602, it removes the `zero_pad_samples` as this can be done with preprocessing after #1706. 
Adjuste the code in kilosort base that was using this option.
> Remove zero pad samples from write_binary_recorder

- examples/modules_gallery/core/plot_1_recording_extractor.py
- src/spikeinterface/core/baserecording.py
- src/spikeinterface/core/binaryrecordingextractor.py
- src/spikeinterface/core/tests/test_baserecording.py
- src/spikeinterface/core/tests/test_binaryrecordingextractor.py
- src/spikeinterface/core/tests/test_channelslicerecording.py
- src/spikeinterface/extractors/shybridextractors.py
While I was working on #1742 I realized that the `BinaryRecordingExtractor` does not follow the convention of the library of referring to number of channels as `num_channels` (as we do in `BaseRecording.get_num_channels`). Instead, it uses `num_chan`. 
This PR starts adding a new argument `BinaryRecordingExtractor` and will throw a deprecation warning for the old argument.
> `num_chan` to `num_channels` in `BinaryRecordingExtractor`

- src/spikeinterface/extractors/phykilosortextractors.py
This excludes end_frame in get_unit_spike_train.
This changes the extractor's behavior...!
But is required for a consistent definition of spike_train values (ie: frame of the parent extractor, and therefore exclusive) and in practice: to avoid IndexErrors when using frame_slice sortings.
> Exclude end_frame in PhyKilosort get_unit_spike_train

- src/spikeinterface/postprocessing/principal_component.py
Hello,
Here is a proposal to fix #1757. I added the possibilty to specify a tmp_folder in the parameter of the PrincipalComponent object. By default is None. 
It works for me, on my local Linux.
Cheers
Maxime
> Pass tmp_folder as parameter for `compute_principal_components`

- src/spikeinterface/core/basesorting.py
- src/spikeinterface/core/frameslicesorting.py
Hi,
I made the call for `has_exceeding_spikes` optional in sorting slicing.
The reason is that it may be redundant with the check performed in `sorting.register_recording`.
Because the check is optional during registration, it's not sufficient to just check whether a recording was assigned...
This is maybe a too specific? but it is a real bottleneck when slicing/concatenating multiple epochs of the same sorting.
Best
> Optional check_spike_frames in sorting.frame_slice

- src/spikeinterface/core/binaryfolder.py
- src/spikeinterface/core/binaryrecordingextractor.py
- src/spikeinterface/core/core_tools.py
- src/spikeinterface/extractors/mdaextractors.py
- src/spikeinterface/sorters/external/tridesclous.py
kwargs in `BinaryRecordingExtractor` were causing warnings to be thrown when loading from dict.
> Fixed `num_chan` warning and propagate to remaining instances

- src/spikeinterface/widgets/amplitudes.py
Small fix to make `plot_amplitudes` work in recordingless mode
> Make plot_amplitudes independent of recording

- pyproject.toml
- src/spikeinterface/extractors/cellexplorersortingextractor.py
When I was working in a conversion I started used this reader for matlab files. Pymat reader uses a consistent interface for matlab files that are in the old format and in hdf5. This allows us to simplify the if conditions code that we have in `CellExplorerSortingExtractor` and have a cleaner code.
Plus, I added some conditions to avoid reading waveform data when possible and a third condition for extracting sampling frequency from the session file when this is available.
> Simplify CellExplorer sorting with pymat reader

- doc/modules/sorters.rst
This question came up several times in issues. I added an explanation of what version of SI is run in the container in the docs
> Add docs on SI version in cointainer

- src/spikeinterface/core/baserecordingsnippets.py
- src/spikeinterface/core/waveform_extractor.py
Fixes #1759 by checking for the probe for every `mode`
> Check probe in waveform extractor and add `has_probe` method

- src/spikeinterface/core/basesorting.py
- src/spikeinterface/extractors/phykilosortextractors.py
- src/spikeinterface/qualitymetrics/misc_metrics.py
- src/spikeinterface/qualitymetrics/pca_metrics.py
- src/spikeinterface/qualitymetrics/quality_metric_calculator.py
- src/spikeinterface/qualitymetrics/tests/test_metrics_functions.py
- src/spikeinterface/qualitymetrics/tests/test_quality_metric_calculator.py
This PR closes #1760 by handling the empty-unit case in quality metrics's `compute_sliding_rp_violations` and `compute_isi_violations`. 
It also shows a warning if empty units exist when running `compute_quality_metrics` to indicate the values for these units are un-interpretable.
To ease this, two new conveience functions `get_non_empty_units` and `get_empty_units` are introduced on basesorter.
Happy to make any required changes!
> Handle empty units in quality metrics

- doc/development/development.rst
- doc/install_sorters.rst
- docs_rtd.yml
- pyproject.toml
- readthedocs.yml
Couple of things that were encountered during the last release.
- Building documentation too slow, both conda and pytorch responsible I think.
- No specific requirements (as in the setup requirements) for the docs.
The big problem is that we need to use conda because of datalad. I am trying to make this better by using mamba. This complicates stuff as I don't know how to hack the read the docs configuration file to use the local branch through conda. Trying a couple of things but will probably need another pair of eyes in the documentation to see that nothing breaks.
I wish that we had the mearec files to the repo so we could get rid of datalad in a bunch of scenarios as the duo git-annex / datalad are a pain and mostly not needed outsides of testing suite for recording.
> Add docs requirements and build read-the-docs documentation faster

- src/spikeinterface/extractors/neoextractors/neuralynx.py
As in the title. This is a mistake that was made in:
https://github.com/SpikeInterface/spikeinterface/pull/1626
It is not a bug as the default behavior is still correct but then the attribute was not working as documentation the way we intended it.
> Fix typo in class attribute for `NeuralynxSortingExtractor`

- src/spikeinterface/comparison/tests/test_groundtruthstudy.py
- src/spikeinterface/core/tests/test_core_tools.py
- src/spikeinterface/sortingcomponents/clustering/sliding_nn.py
- src/spikeinterface/sortingcomponents/peak_detection.py
The `numba` warnings came from the fact that `nopython` default behaviour will change in the future with numba 0.59.
Setting `nopython=True` solves this problem.
Also changed a couple `num_chan` to `num_channels` since this is the new name.
> Fixed `numba.jit` and `binary num_chan` warnings

- src/spikeinterface/extractors/neoextractors/mearec.py
This is a mistake that I made out of ignorance.
I did this PR here:
https://github.com/SpikeInterface/spikeinterface/pull/1835
Which assumes that the changes here would be available in neo version 0.12. At time I did not know that neo version 0.12 was already out as I did not see the tags in github (it is only in pipy). 
But the changes here are not in neo version 0.12 but will come online in the yet to be 0.13:
https://github.com/NeuralEnsemble/python-neo/pull/1258
This PR fixes this here in dev but **I am afraid that the current release mearec is broken.**  The current release is fixed to neo >= 0.12:
https://github.com/SpikeInterface/spikeinterface/commit/c43295d6d6e8a63d124dbfafb17b1937ce4a168e
But this means that lines that I am modifying here will fail (it will assume that a keyword …
> Fix Mearec handling of new arguments before neo release 0.13

- .github/workflows/full-test.yml
- pyproject.toml
Related to #1854
@h-mayorquin another (easier) option is to keep the publish to pypi as is and treat a change in `pyproject.toml` as a core change.
The `prepare-release` branch, with the updated version, will therefore trigger full tests before release, so we can correct any errors prior to tagging.
I think this is a better option than #1854 (and @samuelgarcia too). What do you think?
> Treat pyproject-toml changed as core change

- .github/actions/build-test-environment/action.yml
- .github/is_spikeinterface_dev.py
- .github/workflows/full-test-with-codecov.yml
- .github/workflows/full-test.yml
Two things:
1) As discussed, the cache mechanism of restoring the close keys will get in the way to run the correct dependencies during release.
2) I simplified a bit the installation of dev version dependencies when testing dev versions.
> Eliminate restore keys in CI and simplify installation of dev version dependencies

- .github/workflows/caches_cron_job.yml
There is a new option in the cache machinery that allows for only checking if the cache is available and not downloading it:
https://github.com/actions/cache#inputs
This will save some unecessary computation and bandwith use and as an important side effect make @samuelgarcia happier.
This is used in the daily cron job to checks if it is necessary to create new caches for both the gin data and pip dependencies.
> For the cronjob, avoid re-downloading the cache dataset if present

- src/spikeinterface/qualitymetrics/pca_metrics.py
Fixes #1894 
This was my typo. It was in the non-default 'full silhouette', which is why I think it slipped through.
> Fix typo for `silhouette_full`

- src/spikeinterface/core/waveform_extractor.py
Extracting waveforms from an unfiltered recording with sparsity crashes without this fix
> Fix crash with unfiltered wvf_extractor and sparsity

- src/spikeinterface/comparison/multicomparisons.py
This bug prevents extracting waveforms from an AgreementSortingExtractor as this process requires dumping the AgreementSortingExtractor to disk first.
The issue was that when initialising the AgreementSortingExtractor, BaseSorting.init() is run after self.is_json_serializable = False, which in turn calls BaseExtractor.__init_() which overrides to self._is_json_serializable = True.
The fix is simply to put self.is_json_serializable = False after BaseSorting.init().
Fixes issue #1906
> Fixed bug that prevents dumping AgreementSortingExtractor

- src/spikeinterface/core/baserecording.py
This implements `sample_index_to_time` and reverse on `BaseRecording`, which is something I noticed I wanted the other day. Are you guys open to this change? If so, I can add a test -- `BaseRecordingSegment.sample_index_to_time` didn't have tests anywhere so wasn't sure where to put it, maybe in `test_time_handling.py`?
> Convert from samples<->times directly on BaseRecordings

- src/spikeinterface/sorters/basesorter.py
fixes #1931 
@luiztauffer 
The problem was due to the fact that at the end of spike sorting, the recording is reloaded and attached to the sorting object. Since all internal methods are class methods, this can only be done if the recording is JSON-serializable. In case it's not, the registration is skipped and a warning is printed.
> Check if recording is JSON-serializable in run_sorter

- src/spikeinterface/core/basesorting.py
`count_num_spikes_per_unit` can be very slow for big sorting objects if it needs to re-build all spike trains from a spike vector (in my sorting object, 16min whereas the new implementation takes 5s)
> Use spike_vector in `count_num_spikes_per_unit`

- src/spikeinterface/qualitymetrics/misc_metrics.py
A few of the docstrings have urls that are too long for the RTD boundaries. So this PR is doing its best to prevent that by moving the urls to separate lines. There are a couple more in the API docs, but those will be harder to fix, so I'll try to work on that in a different PR.
Also references aren't numbered so I switched them to the name, from the notes/docstring.
> Change Docstrings to make sure they maintain RTD boundaries

- pyproject.toml
Error with trying to install ".[full]" on a Mac.
```
ERROR: Could not find a version that satisfies the requirement cuda-python; extra == "full" (from spikeinterface[full]) (from versions: none)
ERROR: No matching distribution found for cuda-python; extra == "full"
```
I think they are trying to switch from sys_platform to platform_system in general, but I haven't read too deeply, but based on the fact the old way is error on my M- Mac...
Turns out the boolean can be written as I have (using platform instead of sys). It is discussed here:
https://peps.python.org/pep-0508/#environment-markers
and is now the example given by the 
PyPA for setuptools
https://setuptools.pypa.io/en/latest/userguide/dependency_management.html
(go down about 1/3 the page)
> Fix the [full] install for Macs

- src/spikeinterface/preprocessing/normalize_scale.py
- src/spikeinterface/preprocessing/tests/test_normalize_scale.py
I have this tests failing in #1970 which I have seen failing before. It is not failing in my computer so I want to separate it in its own test to hopefully isolate the failure.
> Pin down z-scale normalized to integer (!) failure by separating the tests

- src/spikeinterface/preprocessing/silence_periods.py
This is because when extending the dimensions of the list if only one segment, it keeps being extended when reloaded by several nodes. The patch should prevent the issues and fixes #1935
> Patch `silence_periods` for mono-segment recordings

- src/spikeinterface/core/generate.py
The `check_borders` should be eventually moved outside (and it's making a bunch of thests failing at the moment)
> Relax check_borders in `InjectTemplatesRecording`

- src/spikeinterface/core/generate.py
Some additiosn after #1948.
* In `generate_recording`. We say that we will deprecate legacy in the next release but we don't have a deprecation warning. Next release is 0.99, so when this is released it should start throwing a deprecation warning, then we can deprecate it in 0.100. I added the deprecation warning. Plus, if we are going to deprecate we should make lazy the default in main so the code that we start suggestin people to use from main remains valid. Otherwise, they we will need to keep an argument with only one possible value (mode="lazy").
* I added the type directly in `rng.standard_normal` as this was generated an expensive computation when I profiled (got 30 % increase in performance for a one hour recorder with "on_the_fly")
* I also modified the default value for the …
> Some additions to generate.py after #1948

- src/spikeinterface/core/waveform_extractor.py
- src/spikeinterface/exporters/to_phy.py
- src/spikeinterface/postprocessing/tests/common_extension_tests.py
- src/spikeinterface/postprocessing/unit_localization.py
In some cases a waveform extractor folder can be loaded in read-only mode (e.g., precomputed waverorms on the cloud, attached as data).
The waveform extensions always inherit the `format` from the parent `WaveformExtractor`. However, if the parent is read-only all postprocessing crashes because it tries to add folders to the parent folder.
This PR adds the `is_read_only()` method to the `WaveformExtractor`. In case a waveform extractor is read-only, extensions can be computed, but they will be in memory and not persistent to disk.
EDIT:
Added a small fix to load the `similarity` extension in the `export_to_phy` if that's already available!
> Allow to postprocess on read-only waveform folders

- src/spikeinterface/curation/mergeunitssorting.py
> Allow MergeUnitsSorting to handle tuples

- src/spikeinterface/preprocessing/detect_bad_channels.py
`detect_bad_channels()`
* fix when some recording is not depth ordered.
* Add more chunk default computation for reproducibility
> Improve detect_bad_channels 

- doc/development/development.rst
- doc/install_sorters.rst
- doc/modules/sorters.rst
- doc/modules/sortingcomponents.rst
Fixes #1966.
I figured I would fix #1966 and while I was fixing that I saw a few more typos and broken links so I just tacked those on to this.
> Fix a few more documentation typos

- doc/api.rst
- src/spikeinterface/extractors/extractorlist.py
When reading #2018 I realized that the `read_binary`/`read_zarr` where not in the docs. Turns out a few core functions were commented out. 
I also exposed the `read_binary` and `read_zarr` as part of the extractors modules.
> Add read_binary and read_zarr functions to extractord and docs API

- src/spikeinterface/preprocessing/remove_artifacts.py
In file: remove_artifacts.py, method: `__init__`, a logical equality check operation was performed. The operands are such that the comparison operation always returns either true or false. Such logical short circuits in code lead to unintended behavior. In this case both parts of a test expression were always returning false.
I suggested that the logical operation should be reviewed for correctness. 
Sponsorship and Support:
This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation (OpenSSF)](https://openssf.org/): [Project Alpha-Omega](https://alpha-omega.dev/). Alpha-Omega is a project partnering with open source software project maintainers to systematically find new, as-yet-undiscovered vulnerabilities in open source code …
> Update a test expression to remove two logical short circuits

- src/spikeinterface/core/sparsity.py
- src/spikeinterface/core/tests/test_sparsity.py
I have been wanting to add something like this for a while and it will be useful in the context of https://github.com/SpikeInterface/spikeinterface/pull/1982.
The idea is that if we have channel sparsity, it should be possible to use the class to compute a sparse or dense representation of a waveform or a template. Now the `ChannelSparsity` object is part of WaveformExtractor but it does not have a way of changing the representation at a waveform at will in the spot. 
Instead, we do sparsifying operations all over the place directly with the mask:
https://github.com/h-mayorquin/spikeinterface/blob/aa5248454462084dcd7a05296ef82c0bb717a285/src/spikeinterface/core/waveform_extractor.py#L946-L950
https://github.com/h-mayorquin/spikeinterface/blob/aa5248454462084dcd7a05296ef82c0bb717a285/src/sp …
> Add methods to sparsify and densify waveforms to `ChannelSparsity`

- src/spikeinterface/core/sparsity.py
Some small typing based on Sam suggestions on https://github.com/SpikeInterface/spikeinterface/pull/1985
> Correct some typing to PR 1985

- doc/conf.py
This is a PR testing what is causing #1964. Since I can't recreate locally I will just test some things in the CI.
> Fix for nested tutorials

- src/spikeinterface/extractors/neoextractors/openephys.py
Resolve https://github.com/SpikeInterface/spikeinterface/issues/2040
Related to https://github.com/NeuralEnsemble/python-neo/pull/1213
> Add `ignore_timestamps_errors` to `OpenEphysLegacyRecordingExtractor`

- src/spikeinterface/extractors/cellexplorersortingextractor.py
- src/spikeinterface/extractors/tests/test_cellexplorerextractor.py
We had a deprecation period in the `CellExplorerSorting` which has expired.
This PR updates the tests and raises an exception ins tead of a warning.
> CellExplorer: fix tests and deprecation

- doc/how_to/load_matlab_data.rst
After https://github.com/SpikeInterface/spikeinterface/pull/2018/files. Minor corrections.
- Some variables were changed to code.
- Correct link display.
- Add extra clarification in the integer dtype example.
> Minor corrections to load from matlab documentation

- src/spikeinterface/extractors/cbin_ibl.py
One of the few missing from the long term project of delaying non-core imports to initialization of their classess.
> Move import to `__init__` in `CompressedBinaryIblExtractor`

- src/spikeinterface/qualitymetrics/misc_metrics.py
- src/spikeinterface/qualitymetrics/tests/test_metrics_functions.py
- src/spikeinterface/sortingcomponents/benchmark/benchmark_motion_estimation.py
- src/spikeinterface/sortingcomponents/benchmark/benchmark_motion_interpolation.py
> Fix firing range when bin size is to small

- doc/how_to/load_matlab_data.rst
- doc/modules/curation.rst
- doc/modules/exporters.rst
- doc/modules/extractors.rst
- doc/modules/motion_correction.rst
- doc/modules/postprocessing.rst
- doc/modules/preprocessing.rst
- doc/modules/qualitymetrics.rst
- doc/modules/qualitymetrics/amplitude_cv.rst
- doc/modules/qualitymetrics/amplitude_median.rst
- doc/modules/qualitymetrics/d_prime.rst
- doc/modules/qualitymetrics/drift.rst
- doc/modules/qualitymetrics/firing_range.rst
- doc/modules/qualitymetrics/firing_rate.rst
- doc/modules/qualitymetrics/isolation_distance.rst
- doc/modules/qualitymetrics/l_ratio.rst
- doc/modules/qualitymetrics/presence_ratio.rst
- doc/modules/qualitymetrics/silhouette_score.rst
- doc/modules/qualitymetrics/sliding_rp_violations.rst
- doc/modules/qualitymetrics/snr.rst
- doc/modules/qualitymetrics/synchrony.rst
- doc/modules/sorters.rst
- doc/modules/sortingcomponents.rst
- doc/modules/widgets.rst
As discussed in #2046. 
I didn't really touch the imports ( I only added imports in a couple spots where it was missing). Once we settle on that I'll just do that in a separate PR.
> Add Keywords to the Documentation Functions

- README.md
Related to discussion in #2042.
I added a link to the docs to pypi release version so users can find that. 
Fixed a few typos/clarifications
> Add link to latest pypi version docs in readme

- src/spikeinterface/sorters/internal/spyking_circus2.py
- src/spikeinterface/sortingcomponents/clustering/random_projections.py
- src/spikeinterface/sortingcomponents/features_from_peaks.py
Extract snippets in a Sparse manner, in order to save a bit the memory footprint and reduce some internal computations.
> Sc2 updates

- src/spikeinterface/sorters/internal/tridesclous2.py
- src/spikeinterface/sortingcomponents/clustering/merge.py
> tridesclous2 update

- examples/modules_gallery/core/plot_4_waveform_extractor.py
- examples/modules_gallery/qualitymetrics/plot_3_quality_mertics.py
The waveform extractor example is broken (due to change in sparsity default in #2071:
https://spikeinterface.readthedocs.io/en/latest/modules_gallery/core/plot_4_waveform_extractor.html#sphx-glr-modules-gallery-core-plot-4-waveform-extractor-py
We need to force the dense example to be dense rather than let it default.
> Fix for `module_gallery` with new sparsity default

- .github/workflows/test_containers_singularity_gpu.yml
@samuelgarcia  @h-mayorquin  this should fix the GPU tests on AWS
https://github.com/SpikeInterface/spikeinterface/actions/runs/6457918395
> Add SPIKEINTERFACE_DEV_PATH to aws gpu tests

- examples/modules_gallery/qualitymetrics/plot_4_curation.py
Fixes #2101.
I know there is a greater debate about what main unit ids should be allowed to be. But at least for the tutorial the path of least resistance is just to pop them out as strings (since everyone agrees strings should be allowed) and use that in the tutorial.
> Fix the `curation` tutorial

- src/spikeinterface/sortingcomponents/clustering/split.py
This should fix recent CI errors: https://github.com/SpikeInterface/spikeinterface/actions/runs/6533283388/job/17738163459
The problem is that the `fix_job_kwargs` removes entries if they are `None`:
See https://github.com/SpikeInterface/spikeinterface/blob/main/src/spikeinterface/core/job_tools.py#L61-L66
> Handle case when mp_context is None

- src/spikeinterface/curation/curation_tools.py
- src/spikeinterface/curation/curationsorting.py
- src/spikeinterface/curation/remove_redundant.py
- src/spikeinterface/curation/splitunitsorting.py
- src/spikeinterface/exporters/to_phy.py
- src/spikeinterface/sorters/basesorter.py
- src/spikeinterface/sorters/launcher.py
- src/spikeinterface/sorters/sorterlist.py
Just another tiny set of typo/grammar fixes for some asserts and trying to provide the user more information about how to fix certain asserts. 
Also in curation there was a typo in two internal function names so I corrected them just to make them easier to find if needed in the future (I didn't run a test on those, so if I see if fail in the CI I'll fix, but they should be called from other functions where I fixed the call too).
> Improve assert messaging (exporters, curation, part of sorters)

- src/spikeinterface/sorters/external/kilosort.py
- src/spikeinterface/sorters/external/kilosort2.py
- src/spikeinterface/sorters/external/kilosort2_5.py
- src/spikeinterface/sorters/external/kilosort3.py
- src/spikeinterface/sorters/external/kilosortbase.py
This PR extends cleanup after kilosort sorting, closes #1896.
The signature for deleting intermediate files is changed slightly and is now a `Tuple` with optional entries, `recording.dat`, `temp_wh.dat` and `matlab_files`. The reason for this extension is to give a little more granularity over the selection of what to delete, and to not delete `temp_wh.dat` by default as it is used for Phy.
For now, have default to delete only `matlab_files` because my understanding is that `recording.dat` is not deleted for other sorters and so this might be confusing if the behaviour is different across sorters. 
Do you think it is worth pushing up this functionality to the `run_sorter` level, so that for any sorter `recording.dat` can be deleted (in the cases it is created). The issue with that …
> Change the signature on kilosort's delete intermediate files parameters.

- src/spikeinterface/extractors/neoextractors/neuroscope.py
- src/spikeinterface/postprocessing/template_metrics.py
Fixes dev tests failing neuroconv. This would also have failed for our users of python 3.8.
I also got another try imported and sent it to the runtime.
> Fixes typing error in waveforms

- src/spikeinterface/sorters/external/kilosort2_5_master.m
- src/spikeinterface/sorters/external/kilosort2_master.m
- src/spikeinterface/sorters/external/kilosort3_master.m
closes #1977.
When using `skip_preprocessed_data` option in kilosort, default options are set from Kilosort's `preprocessDataSub.m` file. Kilosort2 is subtly different to Kilosort2.5 and Kilosort3 but the previous default values did not reflect this. This PR updates the default configs to match those found in `preprocessDataSub.m` of kilosort 2, 2.5 and 3 respectively. This did not require much, only slightly changing 2 variables for kilosort2.
I had a couple of questions:
1) 
I saw this code back
```
ops.NchanTOT = getOr(ops, 'NchanTOT', NchanTOTdefault); % if NchanTOT was left empty, then overwrite with the default
```
in all three KS versions but not in the master matlab files. I guess this is because NchanTOT is expected to always be filled in. But I just wanted to check.
2) maybe now …
> Use versioned kilosort options as default in `skip_preprocessed_data`.

- examples/modules_gallery/widgets/plot_4_peaks_gallery.py
- src/spikeinterface/widgets/peak_activity.py
The final function in the example was missing the `peaks` argument causing it to fail. (See link)
https://spikeinterface.readthedocs.io/en/latest/modules_gallery/widgets/plot_4_peaks_gallery.html#sphx-glr-modules-gallery-widgets-plot-4-peaks-gallery-py
I also added keyword arguments to encourage their use and make clear what arguments are going into the examples.
> Fix peak activity example & bugs in `peak_activity`

- src/spikeinterface/preprocessing/tests/test_whiten.py
- src/spikeinterface/preprocessing/whiten.py
Resolves #2064 
I explain what is happening in the comments
I ran the following test:
```python
import spikeinterface.extractors as se
import spikeinterface.preprocessing as spre
recording, sorting = se.toy_example(num_channels=4, duration=10, seed=0)
recording_whitened = spre.whiten(recording)
traces = recording_whitened.get_traces(segment_index=0)
print(np.var(traces, axis=0))
recording2 = spre.scale(recording, gain=1e-8)
recording2_whitened = spre.whiten(recording2)
traces2 = recording2_whitened.get_traces(segment_index=0)
print(np.var(traces2, axis=0))
```
And got the expected variances close to 1
```bash
[1.0054402  1.0075228  0.9955653  0.96718967]
[0.99692386 0.99832404 0.98711884 0.9610572 ]
```
And without the adjustment the second array is very wrong
```bash …
```
> Adjust eps for whitening in case of very small magnitude data

- pyproject.toml
- src/spikeinterface/qualitymetrics/pca_metrics.py
- src/spikeinterface/qualitymetrics/utils.py
Fixes #1223 
There could always be more submodule specific options in the toml, but since qm is a smaller module and since it was requested should be an easy addition.
Also deleted a couple of unused imports.
> Add quality_metrics specific module requirements to `pyproject.toml`

- src/spikeinterface/preprocessing/tests/test_zero_padding.py
- src/spikeinterface/preprocessing/zero_channel_pad.py
I was running into an error when using Kilosort's `skip_kilosort_preprocessing`  that would crash when running preprocessing during binary-writing prior to sorting.
The (test) file I was running had a period at the end of the trace which was required to be purely padding (for running in kilosort), and was larger than the chunk size. This meant that calls were made to `zero_channel_pad.get_traces()` which had both a start and end frame larger than the original data size. This led to the below function call:
```
original_traces = self.get_original_traces_shifted(
start_frame=start_frame,
end_frame=end_frame,
channel_indices=channel_indices,
)
```
with `start_frame` and `end_frame` that were larger than the original data. 
As a fix, this PR adds another case in which both the `start_frame` …
> Fix `zero_channel_pad` case when selected frames are outside of original data region

- src/spikeinterface/preprocessing/tests/test_zero_padding.py
- src/spikeinterface/preprocessing/zero_channel_pad.py
This adds some cases that were missing while keeping the preprocessing test that was failing on #1979 with a faster test.
> Fix padded traces testing

- src/spikeinterface/core/tests/test_channelslicerecording.py
- src/spikeinterface/extractors/bids.py
- src/spikeinterface/extractors/cbin_ibl.py
- src/spikeinterface/extractors/iblstreamingrecording.py
- src/spikeinterface/extractors/neoextractors/biocam.py
- src/spikeinterface/extractors/neoextractors/maxwell.py
- src/spikeinterface/extractors/neoextractors/mearec.py
- src/spikeinterface/extractors/neoextractors/openephys.py
- src/spikeinterface/extractors/neoextractors/spikeglx.py
- src/spikeinterface/extractors/shybridextractors.py
- src/spikeinterface/extractors/tests/test_neoextractors.py
- src/spikeinterface/preprocessing/deepinterpolation/tests/test_deepinterpolation.py
Fixes CI errors occurring due to this pribeinterface PR: https://github.com/SpikeInterface/probeinterface/pull/206
> Fix open ephys probe loading and unify probeinterface import syntax

- src/spikeinterface/exporters/to_phy.py
Fixes #2023. Just trying to do a cleanup of the issue tracker for 0.99.0. Definitely could go later though.
2 things in this PR
1) As discussed in #2023, there is no point in saving the `template_ind.npy` if the data is dense since it is suppose to be the sparsity for phy. So I just set a boolean to not save `template_ind.npy` if the waveform extractor is dense. Phy will use the lack of `template_ind.npy` to treat it as a dense dataset so Phy's behavior isn't affected (might even be improved since it will treat the data as dense from the get go).
2) with the new default of sparse=True (for `extract_waveforms()`), I'm a little worried that users might not realize their input waveform_extractor is automatically sparse and they might try to layer a sparsity on top. In this case rather than …
> Change phy exporter to not save `template_ind` in the case of dense waveform_extractor

- src/spikeinterface/widgets/traces.py
Fixes #1918,
I just put an assert to double check that each `traces` doesn't have just one channel (though maybe >1 would be a better assert if my assumption of 0 not being possible is wrong). This should prevent the issue seen in #1918.
Also tried to clarify a few errors asserts and added an assert comment for `clim`.
I think with this I'm done with super tiny PR fixes (for the moment :) ). I'll go back to working on module level assert touch-ups and do another pass of the docs after the release is done.
> Add assert error in the case of unichannel data for sortingview backend + minor clarifications

- .github/workflows/installation-tips-test.yml
- doc/modules/core.rst
- src/spikeinterface/core/job_tools.py
Actually I was reading up on multiprocessing and learned that as of 3.8 `fork` should really be avoided on macOS since the resource manager might spin threads. Docs [here](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods). 
Although fork can be used on macOS it is not guaranteed to work safely ( and now `spawn` is the macOS and Windows default), so I added a warning into the job_tools to warn users that setting to fork on macOS is no longer considered safe.
I could change Linux to "not macOS POSIX-based systems" if you'd like though.
+ I noticed one typo in the workflow I wrote for `check_your_install` so I fixed that.
> Add warning that `fork` for the `mp_context` is not recommended for macOS

- src/spikeinterface/core/base.py
> Add overwrite option to save to folder

- src/spikeinterface/sortingcomponents/motion_interpolation.py
Currently if motion correction is performed then `get_traces()` is called with default arguments (i.e. `start_frame=None` or `end_frame=None`) then the routine crashes. This form of calling `get_traces()` is used in some sorters.
This fixes by setting `start_frame=0` and `end_frame = self.get_num_samples()` if either of these values are `None`, which I saw was done elsewhere in the codebase. Let me know if any changes are needed!
> Fix crash when default start / end frame arguments on `motion interpolation` are used.

- src/spikeinterface/comparison/comparisontools.py
- src/spikeinterface/comparison/paircomparisons.py
- src/spikeinterface/comparison/tests/test_comparisontools.py
* Fix corner case in make_match_count_matrix()
* Add symetric option and propagate in SymmetricSortingComparison/GroundTruthComparison
* protect with index instead of frame
> Fix corner case in make_match_count_matrix()

- src/spikeinterface/sorters/internal/spyking_circus2.py
- src/spikeinterface/sorters/internal/tridesclous2.py
We should maybe test that more in depth, but at least, the default is now correct
> Handling segments in SC2 and TDC2

- src/spikeinterface/core/basesorting.py
- src/spikeinterface/core/tests/test_basesorting.py
Added a new `rename_units` method. 
I always forget that the way to do this is to use the `select_units` method with a second argument. 
I think adding a specific method for this is better for discoverability and also is closer to the ideal that "methods should do one thing'" which is also easier for mantainability and code reading.
I also added some missing typing and corrected some docstrings to reflect the fact that some methods don't modify a place but return a new object.
> Add `rename_units` method in sorting

- src/spikeinterface/postprocessing/template_metrics.py
- src/spikeinterface/qualitymetrics/quality_metric_calculator.py
In principle, the user can set duplicated metrics name. This simple PR makes a unique of the metric names to avoid duplication in the output dataframes
> Avoid duplicated template and quality metric names

- src/spikeinterface/core/basesorting.py
`sorting.remove_empty_units()` can be very slow when the spike trains aren't cached
I propose to call `count_num_spikes_per_unit()` which is already optimized.
The downside is that it will not remove a unit that is empty in one segment but not empty in another. Is this a problem?
> Improvement to `get_empty_units()`

- doc/modules/preprocessing.rst
- src/spikeinterface/preprocessing/filter.py
- src/spikeinterface/preprocessing/filter_gaussian.py
- src/spikeinterface/preprocessing/normalize_scale.py
- src/spikeinterface/preprocessing/phase_shift.py
The `astype(dtype)` always converts int to the lower integer, which in some cases causes real problems.
This PR fixes that.
> Fix filtering rounding error

- doc/api.rst
- doc/install_sorters.rst
- doc/modules/core.rst
- doc/modules/curation.rst
- doc/modules/exporters.rst
- doc/modules/postprocessing.rst
- doc/modules/sorters.rst
- doc/modules/sortingcomponents.rst
- doc/modules/widgets.rst
- doc/viewers.rst
- examples/modules_gallery/core/plot_1_recording_extractor.py
- examples/modules_gallery/core/plot_3_handle_probe_info.py
- examples/modules_gallery/core/plot_6_handle_times.py
- examples/modules_gallery/extractors/plot_1_read_various_formats.py
- examples/modules_gallery/extractors/plot_2_working_with_unscaled_traces.py
- examples/modules_gallery/qualitymetrics/plot_3_quality_mertics.py
- examples/modules_gallery/qualitymetrics/plot_4_curation.py
- src/spikeinterface/comparison/groundtruthstudy.py
- src/spikeinterface/postprocessing/spike_locations.py
- src/spikeinterface/widgets/gtstudy.py
- src/spikeinterface/widgets/multicomparison.py
So in this documentation improvement I did:
1) My usual search for typo fixes/minor clarifications
2) I rearranged the sorters docs to move the internal sorters above the legacy sorters because as a reader once I reach legacy I would likely stop reading the docs rather than read on to see SC2 and Tridesclous2, so it is better to be proud of the internal products and move them above legacy. I also added install instruction for Tridesclous2 so for people that want to test it out they can
3) I deleted the legacy section of widgets documentation and instead moved/made sure that every widget currently exposed in the `widgets_list.py` is connected to in the docs. My question for that is: I added `matplotlib` backend, but do all widgets now all have at least the `ipy` backend as well
4) I …
> Improve Documentation VII

- src/spikeinterface/core/baserecording.py
- src/spikeinterface/core/recording_tools.py
- src/spikeinterface/core/tests/test_noise_levels_propagation.py
Caching needs to depend on the method, otherwise the result might be erroneous.
> Fixed a bug when caching recording noise levels

- src/spikeinterface/extractors/mdaextractors.py
- src/spikeinterface/preprocessing/deepinterpolation/generators.py
While triaging your project, our bug fixing tool generated the following message(s)-
> In file: [generators.py](https://github.com/SpikeInterface/spikeinterface/blob/main/src/spikeinterface/preprocessing/deepinterpolation/generators.py#L88), there is a method that creates a temporary file using an unsafe API `mktemp`. The use of this method is discouraged in the [Python documentation](https://docs.python.org/3/library/tempfile.html#tempfile.mktemp). iCR suggested that a temporary file should be created using `mkstemp` which is a [safe API](https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp). iCR replaced the usage of mktemp with `mkstemp`.
- [POC - Improper Method Call - python - mktemp.mp4](https://drive.google.com/file/d/16YKuKgv7iItWcac2biRyi2Cm8upJ3HP_/view?usp=share_link …
> Fix improper method call mktemp

- src/spikeinterface/comparison/comparisontools.py
- src/spikeinterface/core/basesorting.py
- src/spikeinterface/core/tests/test_basesorting.py
- src/spikeinterface/curation/auto_merge.py
- src/spikeinterface/curation/remove_redundant.py
- src/spikeinterface/qualitymetrics/misc_metrics.py
- src/spikeinterface/widgets/unit_depths.py
This should be merge after #2198
> Add an option for count_num_spikes_per_unit

- src/spikeinterface/preprocessing/common_reference.py
Hi,
I found a potential bug and fix while using `common_reference`.
**Problem scenario**: In my original recording object, channel IDs are the same as channel indices. I use `common_reference` after a combination of `channel_slice` and `split_by` while keeping the original IDs. Then when re-loading my latest recording object from the JSON file, the `ids_to_indices` function of the `CommonReferenceRecording` object would raise error suggesting the channel ID is not found. 
**My guess for the cause**: After `channel_slice`, the channel IDs and indices are different. When initializing `CommonReferenceRecording`, the `groups` property is directly modified to reflect indices. Then when re-loading from kwargs, it would run the function `ids_to_indices` again, but this time the input property …
> Fix: save a copy of group ids in CommonReferenceRecording

- src/spikeinterface/core/generate.py
- src/spikeinterface/core/tests/test_generate.py
- src/spikeinterface/preprocessing/tests/test_normalize_scale.py
The time has come.
There is nothing like the joy of deprecation and getting rid of old code.
Courtesy of Dall-e
> Remove legacy mode for `generate_recording`

- src/spikeinterface/sorters/internal/spyking_circus2.py
- src/spikeinterface/sortingcomponents/matching/circus.py
Add the possibility to select the stopping criteria for the circus engine, in order to ease comparison. The default is now a nb_failures mode, that seems to be similar to relative_error, but at least we can explore. This PR depends on PR #2236 that create a debug mode for SC2
> Various stopping criterion for circus matching

- src/spikeinterface/extractors/nwbextractors.py
- src/spikeinterface/extractors/tests/test_nwbextractors.py
One of the IBL nwb files has a ragged column called "spike_relative_depths"
That is, for every unit the properties has a different number of elements (like the spike_times) in a table.
This PR fixes this in the sense that it allows us to load a file with such properties. We should discuss what to do with such properties.
> Fix `NwbSortingExtractor` reading of ragged arrays

- src/spikeinterface/core/tests/test_channelslicerecording.py
- src/spikeinterface/core/tests/test_unitsselectionsorting.py
* Adds tests for #2252 and should come after it.
* Uses generate sorgting instead of saving to disk with `NpzSortingExtractor`
* Eliminates some prints.
> Add tests for unique names in channel slice and unit selection

- src/spikeinterface/extractors/nwbextractors.py
Simple as in the title. As discussed in the monthly meeting yesterday.
> Change cache default to False in NWB Extractors when streaming

- src/spikeinterface/extractors/nwbextractors.py
As in title. Note that this could potentially cause troubles when loading an NWB file saved by SpikeInterface and saving/appending using `neuroconv`.
> Avoid loading `channel_name` property in NwbRecording`

- src/spikeinterface/widgets/traces.py
Fixes #2278.
Do we want to also add in either an assert or clipping mechanism for negative values for time range while we are editing it?
> Prevent users from providing a time_range after the ending of the segment in `plot_traces`

- src/spikeinterface/core/base.py
#2301 adds improved type hints to `core/base.py` `ids_to_indices()` function. These include the pipe `|` operator as alias for `Union` which requires `from __future__ import annotations` for python < 3.10, which this PR adds.
I have no idea why there is an arrow in the line above :sweat_smile:
> Add from `__future__ import annotations` to core base.

- src/spikeinterface/core/generate.py
Just as a MRE
```python
times, labels = synthesize_random_firings(add_shift_shuffle=True, seed=0)
```
There was a bad variable inside the `add_shift_shuffle` if statement that would break the jitter. In addition the spike_times are in samples so the `shift` needs to be dtype `int64`.
Currently `add_shift_shuffle` is not accessed by the main classes at all (it is not exposed at the high level), so there are no tests for this portion of the function. Do we want a test for this? 
Also while working on this PR I was playing around with the `toy_example` and if you put in a sample_frequency of <=15000 it breaks because the default_params for smooth_ms is (0.03, 0.07) and this breaks the smoothing kernel:
Is this worth a separate issue? Or are we just assuming no one will ever want to make low …
> Fix add_shift_shuffle section in synthesize_random_firings

- src/spikeinterface/extractors/neoextractors/neobaseextractor.py
Small typos and format in the warning about t-start and sampling frequencies I found today while working on neuroconv CI.
> Correct warning format in neo base extractors

- src/spikeinterface/sorters/external/kilosort2.py
- src/spikeinterface/sorters/external/kilosort2_5.py
- src/spikeinterface/sorters/external/kilosort3.py
Fixes #2352 
Changes:
1) lam and momentum in 2 & 2.5
2) lam in 3
I didn't touch kilosort1 because the lam and momentum are given slightly differently and they are hardcoded with defaults that are different from the kilosort1 defaults. Is there a reason for this? Should I expose those or just wait for a request?
> Expose `lam` and `momentum` in the appropriate kilosorts

- src/spikeinterface/core/baserecording.py
- src/spikeinterface/core/tests/test_baserecording.py
Easier for users to discover this method with tab completion instead of having to find out by themselves that they need to use channel slice of which this is a particular case.
> Add `rename_channels` method to recording extractors

- src/spikeinterface/core/waveform_extractor.py
This is a pull request following up on issue #2281.
The proposed changes enable the method WaveformExtractor.select_units to also work if the WaveformExtractor had not recording.
> WaveformExtractor.select_units also functional if  we.has_recording()=False

- src/spikeinterface/core/generate.py
This is a PR not to forget, as we discussed with Sam, that unit_locations should be saved as a property of the sorting object in order to be easily used later
> Saving the unit_locations as a property of the sorting in generate_ground_truth_recording()

- src/spikeinterface/core/baserecording.py
Job kwargs passed through `recording.save_to_zarr` or `recording.save(format="zarr")` are ignored. I think this might be a mistake, since [`add_recording_to_zarr_group` seems to expect job kwargs](https://github.com/SpikeInterface/spikeinterface/blob/2e17f2080896bbfb5d7a751f428e127c2fffddea/src/spikeinterface/core/zarrextractors.py#L362)
Opening this just in case (are there interactions with the zarr storage options to be careful with?)
Best
> Pass job_kwargs to ZarrRecordingExtractor.write_recording

- .github/workflows/test_containers_singularity_gpu.yml
- src/spikeinterface/sorters/external/tests/test_singularity_containers_gpu.py
Tests are failing because the test functions still used the deprecated `run_{sorter_name}` functions
> Use run_sorter function in test_containers_singularity_gpu

- src/spikeinterface/core/recording_tools.py
This PR proposes to change how `get_random_data_chunks()` acts if the passed `chunk_size` is too small for the dataset. At present, an error is thrown. However, for me this is causing problems running small datasets for testing, because often this argument is not accessible from surface API (for example, when computing quality metrics).
The proposed solution is to rather than assert if the chunk size is too big, instead clip it and throw a warning. My understanding is this chunk size is pretty much always set internally rather than by the user, so maybe an assert is too strict; the default is somewhat arbitrary anyway, and so can be tailored to the dataset. However, it may cause unintended side-effects, and  an alternative solution would be to ensure the argument is exposed across the …
> Make `chunksize` in `get_random_data_chunks` throw warning and clip if under limit.

- src/spikeinterface/preprocessing/decimate.py
- src/spikeinterface/preprocessing/preprocessinglist.py
- src/spikeinterface/preprocessing/tests/test_decimate.py
Hi,
I needed this because I want to downsample while keeping track of the actual underlying frame ids. In my case I don't care about aliasing etc because I will apply it on a smoothed signal, but it might be a good idea to add some safeguards... Maybe changing the name to avoid confusion with the scipy.decimate function?
Best
Tom
> Add DecimateRecording

- pyproject.toml
See associated issue #2412, but base Anaconda ships with 2.2.0. 
The short story: < 3 can have some issues that can break parallel processing for users (see https://github.com/SpikeInterface/spikeinterface/issues/2401 and https://github.com/SpikeInterface/spikeinterface/issues/2310).
This PR just sets that limit at 3.0.0.
(Fixes #2412 , Fixes #2401, Fixes #2310)
> Add version limit to `threadpoolctl`

- src/spikeinterface/extractors/neoextractors/openephys.py
For other analyses I require the direct data path of the raw data of on Binary Open Ephys recording (continuous.dat). 
For easy acces I propose to add it to the _kwargs property of the OpenEphysBinaryRecordingExtractor. 
Thanks! :)
> Add stream_folders path to OpenEphysBinaryRecordingExtractor

- src/spikeinterface/preprocessing/normalize_scale.py
Previously, random data chunks were loaded in the `ZScoreRecording` constructor, even if `gain` and `offset` were supplied. That meant that re-loading the extractor from a pickle, for example, was slower than it needed to be (I noticed this on a network drive where loading chunks can take a while). This branch calls `get_random_data_chunks` only when needed.
> Faster unpickling of ZScoreRecording

- src/spikeinterface/curation/mergeunitssorting.py
`ind` is not defined if you are in the else ....
Really should have been picked up in the tests.
> Fix bug in `mergeunits`

- src/spikeinterface/postprocessing/template_metrics.py
In the low-level implementation of `get_repolarization_slope` line 471/3:
```python
trough_idx = get_trough_and_peak_idx(template_single)
```
This will return a tuple instead of an int, which will cause the slicing to break later in the function. 
Since the high level call for template metrics supplies `trough_idx` and `peak_idx` this bug would only appear if someone tried to call the low level function by itself.
Also edited some docstrings.
> Fix bug in `get_repolarization_slope` with wrong index type

- src/spikeinterface/preprocessing/tests/test_unsigned_to_signed.py
- src/spikeinterface/preprocessing/unsigned_to_signed.py
Circling back to NeuralEnsemble/python-neo#1348 : 
This PR, as is, returns correct traces from BioCAM recordings when processed through 
`signed_rec = spre.unsigned_to_signed(recording,bit_depth=12)`.
Looking at traces with : 
```
traces = recording.get_traces(channel_ids=['35','26','15','23','8'],
end_frame=4096) # Picking a few random channels
plt.plot(traces)
```
Raw  : 
Processed : 
A few questions : 
- I'm not sure which version of numpy was around when this function was written, but on line 23 : 
https://github.com/SpikeInterface/spikeinterface/blob/c2f18bd536437e9f500a4e24f7a0f3773bd79d3a/src/spikeinterface/preprocessing/unsigned_to_signed.py#L23
`dtype.str` now returns the data type as byte order + kind + item size, which means that `.replace("uint", "int")` does nothing and …
> Add bit depth compensation to unsigned_to_signed

- src/spikeinterface/core/__init__.py
- src/spikeinterface/core/basesorting.py
- src/spikeinterface/core/sorting_tools.py
- src/spikeinterface/core/sparsity.py
- src/spikeinterface/core/template.py
- src/spikeinterface/core/template_tools.py
- src/spikeinterface/core/tests/test_sorting_tools.py
- src/spikeinterface/core/tests/test_sparsity.py
- src/spikeinterface/core/tests/test_template_tools.py
- src/spikeinterface/core/tests/test_waveform_tools.py
- src/spikeinterface/core/waveform_tools.py
This PR:
* make template_tools.py function working without both `WaveformExtractor` (as before) and `Templates` objects
* implements a `estimate_templates()` which is fast and do not need `WaveformExtractor`
* implements `random_spikes_selection()`
* implements `estimate_sparsity()` function. This is also fast. This could replace `precompute_sparsity()` This will be used by `SortingResult`
This PR do not break any signature or behavior. Just improve or enhance previous functions.
> Improvement to compute sparsity without WaveformsExtractor

- src/spikeinterface/core/tests/test_unitsselectionsorting.py
- src/spikeinterface/core/unitsselectionsorting.py
- src/spikeinterface/curation/remove_excess_spikes.py
Fixed a bug introduced in #2353 where the spike vector would be wrong if the given unit_ids were non ordered.
> Fixed parent spike_vector bug

- src/spikeinterface/preprocessing/normalize_scale.py
- src/spikeinterface/preprocessing/tests/test_normalize_scale.py
I am taking a look at https://github.com/SpikeInterface/spikeinterface/issues/2312 and I realized the scale function is really memory hungry. This should make it better.
5 times reduction in memory usage reduction for the following script:
```python
import spikeinterface.preprocessing as spre
from spikeinterface.core.generate import generate_recording, generate_recording_by_size
recording = generate_recording_by_size(full_traces_size_GiB=1.0)
recording = spre.scale(recording, gain=100, offset=70)  
recording.get_traces()
```
In main:
```
Total number of allocations: 46166
Total number of frames seen: 2741
Peak memory usage: 5.1 GiB
```
This branch:
```
Total number of allocations: 45810
Total number of frames seen: 2732
Peak memory usage: 1.1 GiB
```
Note that the trace should be 1.0 GiB …
> Use memory efficient numpy for `ScaleRecordingSegment`

- src/spikeinterface/core/zarrrecordingextractor.py
This PR fixes a back-compatibility issue with the Zarr extractor, since we renamed `root_path` to `folder_path`
> Zarr backcompatibility: map root_path to folder_path

- pyproject.toml
After some failing tests I realized that we are not using the latest dev of probeinterface and neo on the core tests. I guess the reason was that neo does not make much sense but probeinterface does as it is tightly integrated to the core.
> Use core packages on core tests

- src/spikeinterface/core/template.py
Uses the new developed dunder equality method of the `Probe` object:
https://github.com/SpikeInterface/probeinterface/pull/248
Requires:
https://github.com/SpikeInterface/spikeinterface/pull/2458
> Use `Probe` `__eq__` in Template Object `__eq__`

- src/spikeinterface/extractors/nwbextractors.py
The `group` column is a link to the `ElectrodeGroup` object, so it's better to load `group_name`s only to retrieve groups.
Also added a small fix to load the `brainn_area` property
> NWB: do not load group property link

- pyproject.toml
- src/spikeinterface/core/template.py
- src/spikeinterface/core/tests/test_template_class.py
Related to the hybrid project as requested.
> zarr IO for templates object

- src/spikeinterface/preprocessing/filter_gaussian.py
Following up on the discussion we had in #2397 
Indeed there is a bug in the Gaussian filter implementation, which matters if `freq_min` and `freq_max` are close to one another, or even if the min is above the max
Here is a quick code to check for the bug:
```python
import plotly.graph_objects as go
import spikeinterface.core as si
import spikeinterface.preprocessing as spre
sf = 30_000.0
trace = np.zeros([int(sf), 1], dtype=np.float64)
trace[15000] = 1.0
recording = si.NumpyRecording(trace, sf)
recording_f = spre.gaussian_filter(recording, freq_min=600, freq_max=300)
trace_f = recording_f.get_traces()
fig = go.Figure()
fig.add_trace(go.Scatter(
x=1e3 * np.arange(sf) / sf,
y=trace[:, 0],
mode="lines",
name="Original trace"
))
fig.add_trace(go.Scatter(
x=1e3 * …
```
> Fix bug in `GaussianFilter`

- doc/modules/core.rst
- doc/modules/postprocessing.rst
- doc/modules/qualitymetrics.rst
- doc/modules/qualitymetrics/amplitude_cutoff.rst
- doc/modules/qualitymetrics/amplitude_cv.rst
- doc/modules/qualitymetrics/amplitude_median.rst
- doc/modules/qualitymetrics/drift.rst
- doc/modules/qualitymetrics/firing_range.rst
- doc/modules/qualitymetrics/firing_rate.rst
- doc/modules/qualitymetrics/isi_violations.rst
- doc/modules/qualitymetrics/presence_ratio.rst
- doc/modules/qualitymetrics/sd_ratio.rst
- doc/modules/qualitymetrics/sliding_rp_violations.rst
- doc/modules/qualitymetrics/snr.rst
- doc/modules/qualitymetrics/synchrony.rst
- src/spikeinterface/postprocessing/isi.py
I switched postprocessing over to sorting_analyzer.compute notation.
I moved the WaveformExtractor down to a bottom legacy section and opened a blank `SortingAnalyzer` section to be filled in. 
I changed the high level quality metric over to the sorting_analyzer.
The low-level qc stuff should basically be the same right? I would just change that to a sorting_analyzer instead of the waveform_extractor, no?
> WIP: Switching Docs to `SortingAnalyzer`

- src/spikeinterface/core/generate.py
Otherwise the `self.templates` object gets continuously rescaled!
> Fix scaling of inject templates with copy

- examples/modules_gallery/core/plot_4_sorting_analyzer.py
- src/spikeinterface/core/waveforms_extractor_backwards_compatibility.py
Fix bug when reading old dense waveforms.
Only sparse waveforms have a `sparsity.json` file so this should be checked to decide sparsity, rather than the parameter file.
> Fix sparsity check for old waveform extractor

- doc/install_sorters.rst
- src/spikeinterface/sorters/external/kilosort4.py
- src/spikeinterface/sorters/external/tests/test_kilosort4.py
- src/spikeinterface/sorters/external/tests/test_singularity_containers_gpu.py
- src/spikeinterface/sorters/runsorter.py
- src/spikeinterface/sorters/sorterlist.py
Fixes #2527
Kilosort now has a SpikeInterface Wrapper (`RecordingExtractorAsArray`), so we don't need to save to bin!
I had to port subsections of the [`run_kilosort`](https://github.com/MouseLand/Kilosort/blob/main/kilosort/run_kilosort.py#L21) function to allow to:
- do/skip drift correction
- do/skip preprocessing
Added tests for all cases. 
The parameters and descriptions were ported from their [parameters](https://github.com/MouseLand/Kilosort/blob/main/kilosort/parameters.py) definition.
One last comment:
The `RecordingExtractorAsArray` concatenates multiple segment. I think we should handle this externally to "unconcatenate" the sorting output, so I set `handle_multi_segment` to False.
> Kilosort4 Wrapper

- src/spikeinterface/extractors/neoextractors/neobaseextractor.py
This handle negative gain for neo rawio to make smarter user eperience.
For instance in neuralynx very often the gain is negative for all channels which visualization and peak detection comlicated for user.
This simple patch make evrything easier at the cost of of reverting the traces early.
@h-mayorquin @CodyCBakerPhD : could check how  this would impact neuroconv ?
@yger @alejoe91 : if you are ok with this I need it very very soon (for the scool in Paris)
> Handle negative gain for neo rawio to make smarter user eperience.

- src/spikeinterface/core/sortinganalyzer.py
Fixes a bug where `self.folder / "something"` crashes if the given folder was a str to begin with.
Need to cast it to a Path.
> Fixes bug in SortingAnalyzer

- examples/modules_gallery/comparison/plot_5_comparison_sorter_weaknesses.py
- examples/modules_gallery/core/plot_1_recording_extractor.py
- examples/modules_gallery/core/plot_3_handle_probe_info.py
- examples/modules_gallery/core/plot_4_sorting_analyzer.py
- examples/modules_gallery/core/plot_5_append_concatenate_segments.py
- examples/modules_gallery/qualitymetrics/plot_4_curation.py
- examples/modules_gallery/widgets/plot_3_waveforms_gallery.py
- pyproject.toml
@samuelgarcia since you've added zarr into core for SorterAnalyzer we need it to be in base dependencies.... The documentation update broke one of the example code because when you did a zarr with SorterAnalyzer the doc environment didn't have xarray. We could also revert that change and change the example, but at this point it is probably best just to add xarray to core no? 
(Also I see for the examples you're using the list input for the SorterAnalyzer.compute()... Nice)
> Cleanup of modules gallery docs (post SorterAnalyzer)

- src/spikeinterface/extractors/neoextractors/neuralynx.py
@alejoe91 
See https://github.com/NeuralEnsemble/python-neo/pull/1425
> Add strict_gap_mode in read_neuralynx to reflect neo.

- src/spikeinterface/core/recording_tools.py
If you look at Line47 `os.fstat` is used, but os is never imported. This function probably needs a test since this import error hasn't shown up before...
> Add `import os` to recording_tools

- README.md
- doc/index.rst
It could be very confusing for a user to understand the status of the `SortingAnalyzer` in the docs.
Added a comment in the README and docs, so that landing on `latest` will explain briefly what's going on and where to find the stable docs.
> Clarify status of main and Sortinganalyzer

- src/spikeinterface/sorters/external/kilosort4.py
I was trying to run Kilosort4 with docker but it didn't use my GPU.
After some digging I found that `Kilosort4Sorter` only inherits from `BaseSorter` which by default doesn't use the GPU.
I'm not sure if this is the best solution, but adding `gpu_compatibility = "nvidia-required"` seems to have fixed the issue for me.
Might help with #2569
> Use GPU in `Kilosort4Sorter`

- src/spikeinterface/core/numpyextractors.py
As discussed with Sam, we should impose a sorting of the peaks while creating a sorting, to avoid posible bugs downstream
> Fix to impose sorting of the peaks in from_peaks()

- installation_tips/README.md
in #2544 we discovered that one of the files had a broken link (I think it's my bad sorry!), so I fixed the link. I also switch all the links over to main from master. Although github autoconverted them it's probably better just to link them to main just in case :)
> Fix `installation_tips` links

- src/spikeinterface/postprocessing/template_similarity.py
- src/spikeinterface/postprocessing/tests/test_template_similarity.py
Hopefully fixing issue #2599
And added a test to check that the agreement_scores are the expected size.
> Fix template similarity when there are multiple sizes of units

- src/spikeinterface/core/sortinganalyzer.py
Hi @zm711 @alejoe91.
This is proposal to auto load extensions : when extension is builin and not registered because not impotred yet : then we have an auto load mechanism. This should help the end user.
Tell me what you think.
This is hard to be tested in core tests because it auload submodules which will fail on core testing because of dependencies.
So I made local tests and it works.
This should fix partially #2560.
> Proposal for auto import extensions module.

- src/spikeinterface/sorters/external/kilosort.py
- src/spikeinterface/sorters/external/kilosort2.py
- src/spikeinterface/sorters/external/kilosort3.py
Based on the KS readme [here](https://github.com/MouseLand/Kilosort/tree/main). It is not advised for users to change the batch size `NT`. This just adds a note saying that the SpikeInterface default is the KS recommended value as long as the user doesn't change the ntbuff either. Related to #2562.
> Add note about recommendation not to change batch size in Kilosort1-3

- src/spikeinterface/core/core_tools.py
- src/spikeinterface/core/waveform_tools.py
np.prod produces a numpy scalars (not integers or floats!). 
Numpy scalars behave like numpy values and can overflow. Example:
```python
In [1]: a_billion_int = 1_000_000_000
In [2]: np.prod((a_billion_int, a_billion_int, a_billion_int, a_billion_int))
Out[2]: -5527149226598858752
```
Python integers on the other hand do not overflow. 
This PR changes this so overflow errors do not happen.
This error appear to a user here:
https://github.com/SpikeInterface/spikeinterface/issues/1871#issuecomment-1947957281
> Avoid `np.prod` in `make_shared_array`

- src/spikeinterface/core/__init__.py
- src/spikeinterface/core/sortinganalyzer.py
- src/spikeinterface/core/tests/test_sortinganalyzer.py
- src/spikeinterface/postprocessing/tests/test_unit_localization.py
- src/spikeinterface/postprocessing/unit_localization.py
and `get_computable_extensions()`
@samuelgarcia @h-mayorquin @zm711 couldn't come up with a better name for the latter. Any suggestion?
At one point, we will make the switch and define proper pydantic models (at least for extension, sorters, quality metrics, template metrics params)
**NOTE:** I changed the `unit_locations` `**method_kwargs` to a `method_kwargs` dict, which is better for inspection
> SortingAnalyzer: `get_extension_default_params`

- pyproject.toml
- src/spikeinterface/extractors/tests/test_neoextractors.py
As stated on the title. This is possible because we merged the following neo:
https://github.com/NeuralEnsemble/python-neo/pull/1402
As this translated cleanly the only thing that I am adding here are the tests.
> Add supportfor `IntanRecordingExtractor` "one-file-per-signal" and "one-file-per-channel" formats

- src/spikeinterface/core/frameslicesorting.py
From the discussion here:
https://github.com/SpikeInterface/spikeinterface/issues/2573#issuecomment-1995993813
I was kind of recluctanct to add "could indicate a bug on the sorter" as this is a very general function but I guess a sorting object can only come from sorter so...
> Improve documentation for excess spikes error in `FrameSliceSorting`.

- .github/actions/build-test-environment/action.yml
Uses the new attribute on the `__init__` to determine whether to install neo and probe from their latest github versions.
> Modify CI for new dev version criteria

- src/spikeinterface/core/base.py
- src/spikeinterface/core/tests/test_zarrextractors.py
- src/spikeinterface/core/zarrextractors.py
This PR gives the possibility to define compression options per dataset.
This became a requirement in case of compressing traces with a compressor that doesn't support `float64` and also write timestamps, which are internally treated as `float64`
> Extend zarr compression options

- examples/modules_gallery/core/plot_4_sorting_analyzer.py
Merging #2579 broke the `SortingAnalyzer` tutorial because recomputing waveforms deleted templates. I added in a new section that briefly describe why this happens. Then I recomputed templates so the tutorial will work.
> Fix SortingAnalyzer tutorial

- src/spikeinterface/sorters/external/kilosort4.py
add option `torch_device="auto"/"gpu"/"cpu"` to kilosort4 to force cpu even if cuda is available when small gpu
> add option to kilosort4 to force cpu even if cuda is available when small gpu

- src/spikeinterface/preprocessing/common_reference.py
- src/spikeinterface/preprocessing/tests/test_common_reference.py
Fixes bug in `get_traces` for common reference recordings with a `local` reference, where you couldn't select a subset of channels. Noticed it when plotting traces.
Here's minimal code which reproduces the bug
```
from spikeinterface.core import generate_recording
from spikeinterface.preprocessing import common_reference
recording = generate_recording(durations=[5.0], num_channels=4)
recording_cmr_segment = common_reference(recording, reference="local")._recording_segments[0]
recording_cmr_segment.get_traces(start_frame=0, end_frame=10, channel_indices=[1,2])
```
This should raises an error.
Also added a test which selects a subset of channels ids, and makes sure it's selected the right one.
> Fix get_traces for a local common reference

- .github/workflows/streaming-extractor-test.yml
- pyproject.toml
- src/spikeinterface/extractors/nwbextractors.py
- src/spikeinterface/extractors/tests/test_nwbextractors_streaming.py
We have discussed about this for a while. It is hard to mantain and test and it does not seem to buy anything over `ffspec`.
I will do it now as I am getting some import errors on the stream extractors test on https://github.com/SpikeInterface/spikeinterface/pull/2661 and I want to get rid of this complexity before digging into this.
> Deprecate ros3 as a streaming method

- src/spikeinterface/core/tests/test_analyzer_extension_core.py
- src/spikeinterface/core/waveform_tools.py
@DradeAW there was a typo in the tests, but still fast and normal templates give the same stds down to the 4th decimal (which I think it's ok)
> Fix typo in fast templates test

- src/spikeinterface/core/generate.py
- src/spikeinterface/core/tests/test_analyzer_extension_core.py
- src/spikeinterface/postprocessing/tests/common_extension_tests.py
- src/spikeinterface/sortingcomponents/peak_detection.py
- src/spikeinterface/sortingcomponents/tests/test_peak_detection.py
In this PR, we change the way fake templates are generated. Instead of a powerlaw for the decay of the amplitudes as function of the distances, we use a decaying exponential with a spatial_constant. This seems to be more biophysically plausible, and it introduces less artefacts
> Changing the generation of fake template with a decaying exponential and fix torch locally exclusive

- src/spikeinterface/sorters/external/mountainsort5.py
Uses the internal `save` function and gets rid of the `tmp_dir`.
Should fix #2670 #2607
> Improve caching of MS5 sorter

- src/spikeinterface/core/analyzer_extension_core.py
- src/spikeinterface/core/sortinganalyzer.py
- src/spikeinterface/core/sparsity.py
- src/spikeinterface/core/template_tools.py
- src/spikeinterface/core/tests/test_analyzer_extension_core.py
- src/spikeinterface/core/tests/test_sortinganalyzer.py
- src/spikeinterface/core/tests/test_sparsity.py
- src/spikeinterface/core/waveforms_extractor_backwards_compatibility.py
- src/spikeinterface/postprocessing/amplitude_scalings.py
- src/spikeinterface/postprocessing/spike_amplitudes.py
- src/spikeinterface/postprocessing/template_similarity.py
- src/spikeinterface/postprocessing/tests/test_spike_amplitudes.py
- src/spikeinterface/qualitymetrics/misc_metrics.py
- src/spikeinterface/qualitymetrics/pca_metrics.py
Move "return_scaled" options global to SortingAnalyzer.
Having a unique and global option for this is less dangerous, for instance to compute snr which depends on 2 options.
> Move "return_scaled" options global to SortingAnalyzer.

- src/spikeinterface/qualitymetrics/quality_metric_calculator.py
Remove "waveforms" dependency for compute_quality_metrics().
This needed only for some metrics that will give wrnings.
> Remove "waveforms" dependency for compute_quality_metrics().

- examples/modules_gallery/core/plot_4_sorting_analyzer.py
Moving `returned_scaled` in #2684 broke the sorting_analyzer example file. 
Datalad is broken on my computer so I need to test this here really quick to make sure my fix worked.
> Fix example broken by #2684

- src/spikeinterface/curation/remove_excess_spikes.py
- src/spikeinterface/curation/tests/test_remove_excess_spikes.py
Fixes #2710.
Remove negative spikes (a known bug in KS4) and update tests to test removing negative times.
> Allow for `remove_excess_spikes` to remove negative spike times

- src/spikeinterface/core/channelsaggregationrecording.py
> Fix performance issue for `aggregate_channels`

- doc/how_to/combine_recordings.rst
- doc/how_to/index.rst
Fixes #2620.
@h-mayorquin just getting the ball rolling. Did we want to include aggregate channels at the bottom of this tutorial? 
I need to update the `repr` I was just trying to get the gist, but I'll try to do this with a real file so I can get the real repr values shortly :)
> Add a "how to" for combining recordings 

- src/spikeinterface/extractors/tests/test_nwbextractors_streaming.py
Speed up a very slow test, by only checking some units, cutting the total test run from 33->28 minutes!
A preview of the Great-Test-Speed-Up of 2024: https://github.com/SpikeInterface/SpikeInteface-Hackathon-Edinburgh-May24/issues/8
(This seemed too easy and impactful to wait until the hackathon)
The function `test_sorting_s3_nwb_zarr` downloads a sorting object from s3 and checks some things about it. This has traditionally taken a while because the object is pretty big and has ~450 units. Most of the testing time was spent looping over these 450 units and calculating their spike trains. This is probably overkill, so I propose to only check a random selection of 3/450 units.
You can see the overall speed-up here, from my github page (I realise these are failing, but they are attempting …
> Speed up test_sorting_s3_nwb_zarr

- doc/modules/exporters.rst
- src/spikeinterface/exporters/report.py
- src/spikeinterface/exporters/to_phy.py
Exporter docs still said WaveformExtractor so I switched those over.
While doing that I noticed that the export report let's the user specify the `peak_sign` and then promptly forces it to be `neg` so I just switched it so that the `peak_sign` that the user specified is used.
> Switch exporters docs to `SortingAnalyzer`

- src/spikeinterface/core/sortinganalyzer.py
- src/spikeinterface/core/tests/test_analyzer_extension_core.py
Fixes #2745 , bug discovered and solution discovered by @zm711 
The function `_get_children_dependencies` randomised the list of children, through the `set` function. This is a problem when using this function to delete extensions, since this has an ordering to it. Solution is simply to delete `set`, which didn't do anything (as far as I can tell, from playing with more complicated dependencies in the postprocessing module).
Added test to check that ordering is correct for the core extensions. Note: the test randomly passes or fails randomly for past versions. Test always passes now 😎
> Remove randomness of order in _get_children_dependencies

- src/spikeinterface/core/template_tools.py
Fixes #2751.
As the issue states there is a problem if the end-user sets the global `SortingAnalyzer` `return_scaled=False` because in template tools it checks to make sure that `get_template_amplitudes` has the same `return_scaled` as the `SortingAnalyzer`. But the default is `True` for the function. 
In this PR we use the `SortingAnalyzer.return_scaled` if it is a sorting analyzer and `True` if it is `Templates` which was the previous default. We missed this because `return_scaled=True` is the default for the `SortingAnalyzer` which wouldn't trigger this.
> Check for SortingAnalyzer `return_scaled` in template_tools

- src/spikeinterface/sorters/external/kilosort4.py
> Fix KS4 for v>=4.0.5 and simplify skip correction

- src/spikeinterface/preprocessing/motion.py
- src/spikeinterface/preprocessing/preprocessing_tools.py
- src/spikeinterface/preprocessing/tests/test_preprocessing_tools.py
change "idw" to "krigging" in spatial_interpolation_kernel in parameters preset because  really depend on the geometry.
> Change "idw" to "kriging" in spatial_interpolation_kernel parameters

- src/spikeinterface/curation/auto_merge.py
This PR improve `get_potential_auto_merge()` with:
* several metrics for templates distances
* handling sparsity of templates
* use computed units locations from analyzer
@DradeAW  : can you check this, if you use this in Lussac. Normally the behavior is the same as before.
> Enhancing curation : get_potential_auto_merge()

- doc/modules/preprocessing.rst
Clarify that detect_bad_channels doesn´t automatically deal with multi probe recordings  #2766
> Update detect_bad_channels docs

- src/spikeinterface/core/sortinganalyzer.py
Fixes #2788 
See issue for full discussion but basically before `return_scaled` was global the `settings.json` file was not written and is now required to reload a SortingAnalyzer. This just writes the file to allow for compatibility for early adopters and can be removed at some point in the future.
@samuelgarcia is this what you had in mind based on our discussion in the issue?
> Add write settings.json for back compatibility for early-adopters of SortingAnalyzer

- src/spikeinterface/widgets/base.py
- src/spikeinterface/widgets/crosscorrelograms.py
This came up during talking in #2782, but I think `TypeError` instead of `ValueError` no? @alejoe91 ? 
And was there a reason you didn't want an error here originally @samuelgarcia @alejoe91 ?
> Add errors to `ensure` functions  in `Base` of widgets

- src/spikeinterface/curation/remove_redundant.py
Current error message if using a `Sorting` with `remove_redundant_units` and `remove_strategy != max_spikes` is 
```python
AttributeError: 'NoneType' object has no attribute 'unit_ids'
```
This is because the other strategies rely on Templates from the `SortingAnalyzer`. This just adds an extra assert at the beginning indicating that for a sorting input only `max_spikes` is possible. If there is a better solution also happy to adapt.
> Provide useful message if sorting used instead of analyzer for remove_duplicate_units

- src/spikeinterface/curation/curationsorting.py
- src/spikeinterface/curation/splitunitsorting.py
- src/spikeinterface/curation/tests/test_curationsorting.py
Fixes #2694 and replaces #2695 (by @OlivierPeron)
@OlivierPeron when making aPR it's better to create a branch different than main so we can directly contribute to it ;)
> Fix split in more than 2 units and extend curation docs and tests

- src/spikeinterface/core/zarrextractors.py
- src/spikeinterface/generation/template_database.py
If the zarr folder has timestamps, they were re-extracted and uncompressed every time the `get_times()` was called. 
This PR loads the zarr array as a numpy array at instantiation to speed things up
> Zarr: extract time vector once and for all!

- src/spikeinterface/core/job_tools.py
- src/spikeinterface/core/tests/test_job_tools.py
For functions that take in an `n_jobs` argument they all run `fix_job_kwargs`, but if the user gives something like 4.0 to mean 4 jobs they end up with (if they have 4 cores)
int(4.0 * 4.0) = 16
So instead we should cast 4.0 -> 4 and just make it 4 jobs no? 
What do you think @alejoe91 ?
> Add extra check in fix_job_kwargs

- src/spikeinterface/core/recording_tools.py
- src/spikeinterface/preprocessing/unsigned_to_signed.py
Working on the tutorial. Small PR with improvement.
> Add typing to `write_binary_recording`

- doc/how_to/viewers.rst
Related to the decision to use US spelling.
Last fix we need to make is analyse_neuropixel to analyze_neuropixel. But I don't have access to the raw data to fix that one.
@chrishalcrow  :)
> Switch `Visualise` to `Visualize`

- src/spikeinterface/sorters/external/ironclust.py
> Add parameter for irc1

- src/spikeinterface/core/baserecording.py
Similar to #2747 but for recording objects
Note that this avoids the problem that once bothered @samuelgarcia about displaying too much. This displays less than the string representation by making the segment representation optional (you need to click).
Here an interactive version you can click:
<div style='border:1px solid #ddd; padding:10px;'><strong>NoiseGeneratorRecording: 4 channels - 30.0kHz - 3 segments - 6,300,000 samples - 210.00s (3.50 minutes) - float32 dtype - 96.13 MiB</strong></div><details style='margin-left: 10px;'>  <summary><strong>Segments</strong></summary><ol><li> Samples: 300,000, Duration: 10.00s, Memory: 4.58 MiB</li><li> Samples: 600,000, Duration: 20.00s, Memory: 9.16 MiB</li><li> Samples: 5,400,000, Duration: 180.00s (3.00 minutes), Memory: 82.40 …
> Add html representation for recording objects

- src/spikeinterface/core/job_tools.py
> improve verbose of  `ChunkRecordingExecutor`

- src/spikeinterface/core/sortinganalyzer.py
Fixes #2772
@zm711 this is a temporary solution that works for the time being. We can look for a more flexible and long-term solution later
> Compute quality metrics after pipeline nodes

- src/spikeinterface/core/template.py
- src/spikeinterface/core/tests/test_template_class.py
This was missing. Added a test to catch this type of error.
> Load `is_scaled` in from zarr Template representation

- src/spikeinterface/core/sortinganalyzer.py
Fixes #2887 
See #2887. But the issue is delete on recompute won't work for non-core extensions since the get_child_dependencies won't have the other extensions registered. We either need to flip the order (which I want to test with this PR) or fix the error messaging for this case.
Logic is that getting the class_extension should register it, which would allow us to delete on recompute.
> Put get_extension (to trigger auto-import) before get_children_dependencies for deleting Analyzer extensions to prevent KeyError

- src/spikeinterface/core/core_tools.py
- src/spikeinterface/core/job_tools.py
- src/spikeinterface/core/tests/test_core_tools.py
This is so primarly the ChunkRecordingExecturo can accept binary prefixes like 1 GiB, 500 MiB:
https://en.wikipedia.org/wiki/Binary_prefix
I think this is more useful for working with ram related things.
I am struggling with some memory errors while uploading data to the templates database and I am trying a more fine control so I thought this would be useful.
> Add binary sufixes to job tools memory specification (e.g. 1GiB vs 1GB)

- src/spikeinterface/extractors/neoextractors/neobaseextractor.py
As in the title. 
There is always a `channel_names` annotation in neo that we can load with `all_annotations=True`:
https://github.com/h-mayorquin/python-neo/blob/223e22edb917d8ad5ef8aff4fe7197afc414d5f6/neo/rawio/baserawio.py#L282-L293
This PR modifieds the code so when `all_annotations=True` the property is not duplicated. 
Plus, I am changing the name of the property to `channel_names` because that's how it is neo and I think is more consistent overall. Another option is to instead change the property  name to "channel_name" when loaded from neo annotations so we don't duplicate. I think that the first approach is better.
> Avoid duplicating channel names as property in neo base extractor when `all_annotations=True`

- src/spikeinterface/core/sparsity.py
- src/spikeinterface/core/template_tools.py
Now that #2842 adds an attribute which indicates that the Templates object is scaled we should use that for the functions inside of template_tools no? If the Templates aren't scaled then we can't return scaled.
> Use the `is_scaled` attribute inside of `template_tools` functions

- pyproject.toml
Should fix https://github.com/SpikeInterface/spikeinterface/issues/2863 while someone goes and ensures that the library works with the newest version of matplotlib
> Pin matplotlib dependency

- src/spikeinterface/core/zarrextractors.py
- src/spikeinterface/extractors/phykilosortextractors.py
When loading phy/kilosort folders, string array properties are cast to python `Object`. This results in a failure when writing to zarr.
This simple PR protects against Object dtypes and tries to cast the array as str.
> Protect zarr properties of type object

- pyproject.toml
- src/spikeinterface/widgets/multicomparison.py
This PR unpins the Sphinx version dependency from 5.1.1 as well as read the docs from 1.0.0. It also adds `networkx` which from the logs seems to be a dependency on the docs as an build warning was raised.
I can't detect any issues from the upgrade, although it's quite hard to test. I looked through the logs and they look similar, Number of warnings differs by 1. I went through every page and compared with current docs, everything looks the same and seems to have build without issue, but I did skim pages just randomly checking features like 1) links working 2) images rendering 3) generated values the same. The only differences I saw is that in the new version, the API docs typing is written a little neater using the new shortcuts (e.g. "|") and there is a slight stylistic change (the grey …
> Unpin sphinx and add networkx dependency.

- src/spikeinterface/core/job_tools.py
- src/spikeinterface/core/recording_tools.py
- src/spikeinterface/core/tests/test_recording_tools.py
- src/spikeinterface/sorters/internal/simplesorter.py
- src/spikeinterface/sorters/internal/spyking_circus2.py
- src/spikeinterface/sortingcomponents/clustering/circus.py
- src/spikeinterface/sortingcomponents/clustering/position_and_features.py
- src/spikeinterface/sortingcomponents/clustering/position_and_pca.py
- src/spikeinterface/sortingcomponents/clustering/position_ptp_scaled.py
- src/spikeinterface/sortingcomponents/clustering/random_projections.py
- src/spikeinterface/sortingcomponents/clustering/sliding_hdbscan.py
- src/spikeinterface/sortingcomponents/tests/test_clustering.py
- src/spikeinterface/sortingcomponents/tests/test_motion_estimation.py
- src/spikeinterface/sortingcomponents/tests/test_peak_detection.py
- src/spikeinterface/sortingcomponents/tests/test_peak_localization.py
- src/spikeinterface/sortingcomponents/tests/test_peak_selection.py
Lets see what new bug this could trigger!
@h-mayorquin @zm711 : this has been discuss at many places.
Lets make a list of link here.
> remove verbose from job_kwargs

- src/spikeinterface/core/baserecording.py
- src/spikeinterface/core/recording_tools.py
Should close #2847. Following on https://github.com/SpikeInterface/spikeinterface/pull/2898/files. Also removed some comments from https://github.com/SpikeInterface/spikeinterface/pull/2728.
I still think this approach of catching verbose at every point of the call stack is very labor intensive. I mentioned to Sam that we could have more specific verbosity terms:
For the ChunkRecordingExectuor: `display_chunk_info` or `verbose_chunk_executor` 
For the save_to_folder `display_saved_folder`
But he pointed out -correctly I think- that usually verbose is managed in linux like a global option which I think it makes sense. 
Maybe the real work around will be the genera logger as described in https://github.com/SpikeInterface/spikeinterface/pull/2602
> Fix remaining verbose clashing

- src/spikeinterface/core/job_tools.py
- src/spikeinterface/core/tests/test_job_tools.py
This is necessary for #2892.
As you can see from my previous comment one year ago in the diff I was baffled by this edge case. Today while working on #2892 I finally understood (I hope!) what @samuelgarcia intended. 
I am making this behavior explicit and adding a test.
> Making `chunk_size=None` behavior for n_jobs=1 explicit

- src/spikeinterface/extractors/nwbextractors.py
> Remove unused argument in nwb extractors `read_file_from_backend`

- src/spikeinterface/extractors/nwbextractors.py
Reason is this are sometimes needed when straming with zarr. I also improved the docstring.
> Add `zarr.open` kwargs to `fetch_available_electrical_series_paths` in `NWBRecordingExtractor`

- src/spikeinterface/sorters/launcher.py
- src/spikeinterface/sorters/runsorter.py
- src/spikeinterface/sorters/tests/common_tests.py
- src/spikeinterface/sorters/tests/test_launcher.py
Working on switching all run_sorter flavors to folder rather than working_folder/output_folder/ folder.
> Regularize folder argument for user in run_sorter options

- src/spikeinterface/core/baserecording.py
- src/spikeinterface/core/baserecordingsnippets.py
- src/spikeinterface/core/basesnippets.py
- src/spikeinterface/core/sortinganalyzer.py
- src/spikeinterface/extractors/tests/test_nwbextractors_streaming.py
- src/spikeinterface/postprocessing/amplitude_scalings.py
- src/spikeinterface/postprocessing/spike_amplitudes.py
- src/spikeinterface/preprocessing/correct_lsb.py
- src/spikeinterface/preprocessing/detect_bad_channels.py
- src/spikeinterface/sorters/external/waveclus.py
- src/spikeinterface/widgets/traces.py
This is for developer and end-user clarity. `has_scaled` is not clear because what we really have is the ability to scale the traces so this object is `has_scaleable_traces` which clearly states what the boolean is indicating.
+ appropriate deprecations.
> API: switch `has_scaled` -> `has_scaleable_traces`

- src/spikeinterface/core/core_tools.py
- src/spikeinterface/core/tests/test_core_tools.py
I found a bug wherein the add_suffix function was adding two dots to the filename instead of just one. For example, add_suffix('myfile', ['raw','bin','path']) returned "myfile..raw" instead of "myfile.raw". I have corrected this bug and also added a new test in test_core_tools.py.
> fixed bug in add_suffix and added test

- src/spikeinterface/comparison/tests/test_groundtruthcomparison.py
- src/spikeinterface/comparison/tests/test_multisortingcomparison.py
- src/spikeinterface/comparison/tests/test_symmetricsortingcomparison.py
- src/spikeinterface/qualitymetrics/tests/test_pca_metrics.py
This PR replaces `toy_example` with `generate_recordings` in certain test files (outside of sorter tests). This PR is part of three PRs removing `toy_example` created during the 2024 Hackathon.
TODO:
- [src/spikeinterface/comparison/tests/test_hybrid.py](https://github.com/JoeZiminski/spikeinterface/blob/29ad02bba37426e931902744a3eb68bc6c1ae2f2/src/spikeinterface/comparison/tests/test_hybrid.py#L10) uses a `average_peak_amplitude` argument that is not  included in `generate_ground_truth_recording`. Q: should this functionality be added to `generate_ground_truth_recording`?
> Remove toy example from test codebase (1)

- src/spikeinterface/comparison/tests/test_templatecomparison.py
- src/spikeinterface/extractors/tests/test_mdaextractors.py
- src/spikeinterface/extractors/tests/test_shybridextractors.py
- src/spikeinterface/preprocessing/tests/test_motion.py
- src/spikeinterface/qualitymetrics/tests/test_metrics_functions.py
Removed some `toy_examples` from some test code.
> Remove toy_example from test codebase (2)

- src/spikeinterface/preprocessing/tests/test_phase_shift.py
- src/spikeinterface/sorters/external/tests/test_docker_containers.py
- src/spikeinterface/sorters/external/tests/test_kilosort4.py
- src/spikeinterface/sorters/external/tests/test_pykilosort.py
- src/spikeinterface/sorters/external/tests/test_singularity_containers.py
- src/spikeinterface/sorters/external/tests/test_singularity_containers_gpu.py
- src/spikeinterface/sorters/external/yass.py
- src/spikeinterface/sorters/tests/common_tests.py
- src/spikeinterface/sorters/tests/test_container_tools.py
- src/spikeinterface/sorters/tests/test_launcher.py
This PR replaces toy_example with generate_ground_truth_recording in the sorters folder, it is part of a group of PRs removing toy_example decided during the hackathon 2024
> Replace toy_example by generate_ground_truth_recording in sorters folder

- src/spikeinterface/extractors/tests/test_iblextractors.py
Remove unused tkinter import on ibl that is breaking tests on mac.
> Remove unused imports in ibl test

- src/spikeinterface/core/sorting_tools.py
- src/spikeinterface/postprocessing/correlograms.py
- src/spikeinterface/postprocessing/isi.py
- src/spikeinterface/qualitymetrics/misc_metrics.py
https://numba.discourse.group/t/reducing-import-time/1072/8 
This discussion says that providing type signatures gives type checking, but then leads to eager compilation. This PR tests removing that to see if it speeds import time.
> Remove numba type signature to prevent compilation of numba functions at import

- src/spikeinterface/preprocessing/tests/test_zero_padding.py
- src/spikeinterface/preprocessing/zero_channel_pad.py
https://github.com/SpikeInterface/SpikeInterface-Hackathon-Edinburgh-May24/issues/6
Changed variable name from parent_recording to recording
> Regularised the API from parent_recording to recording in zero_channel_pad

- src/spikeinterface/qualitymetrics/pca_metrics.py
- src/spikeinterface/qualitymetrics/quality_metric_calculator.py
- src/spikeinterface/qualitymetrics/quality_metric_list.py
- src/spikeinterface/qualitymetrics/tests/test_pca_metrics.py
Basically everything else at the low level is compute_x so switching this over for consistency.
> Switch `calculate_pc_metrics` to `compute_pc_metrics` for api consistency

- doc/conf.py
Sphinx removed JQuery dependency in v6. To keep using ReadTheDocs we need to add an extension.
Should fix #2961, wait till documentation has built to see!
> Add a jQuery extension to enable search

- pyproject.toml
This is something that @samuelgarcia asked me to do here https://github.com/SpikeInterface/spikeinterface/pull/2665#discussion_r1552037196 but got lost.
Hopefully the tests pass.
> Remove upper bound in scipy dependency for full install

- pyproject.toml
- src/spikeinterface/core/waveform_extractor.py
This small PR fixes the `WaveformExtractor.save()` in recordingless mode
> [0.100.x-bug-fixes] Fix waveforms save in recordingless mode

- src/spikeinterface/sorters/runsorter.py
Fixes #2967 , Fixes #2965. 
A bug noticed by @ninelK. 
If folder is None we should set folder to the output for docker/singularity.
To answer your question in the commit history Nina,
they can be strings because we are adding here then we switch to path. We could do the same with a Path, but it doesn't really matter. 
Thanks for spotting the bug. related to #2917.--Needs to be tested by someone with Docker.
> Patch for regularizing folder arguments

- src/spikeinterface/sorters/external/tests/test_docker_containers.py
- src/spikeinterface/sorters/external/tests/test_singularity_containers.py
- src/spikeinterface/sorters/external/tests/test_singularity_containers_gpu.py
- src/spikeinterface/widgets/tests/test_widgets.py
As discussed the link between KACHERY and Sortingview is not super clear so this provides an easier to discover env-var for skipping sortingview tests for local development of widgets.
> Make easier env vars for local testing

- src/spikeinterface/extractors/neoextractors/intan.py
Following on the corresponding neo work:
https://github.com/NeuralEnsemble/python-neo/pull/1470
Comes with a check so the argument is only propagated for the upcoming version of neo and does not break current version.
> Add argument to `IntanRecordingExtractor`  for opening files with discontinous timestamps

- .github/import_test.py
- src/spikeinterface/exporters/report.py
- src/spikeinterface/exporters/to_phy.py
- src/spikeinterface/extractors/matlabhelpers.py
- src/spikeinterface/qualitymetrics/pca_metrics.py
- src/spikeinterface/sorters/container_tools.py
- src/spikeinterface/sorters/external/combinato.py
- src/spikeinterface/sorters/external/pykilosort.py
- src/spikeinterface/sorters/internal/spyking_circus2.py
- src/spikeinterface/sortingcomponents/matching/circus.py
- src/spikeinterface/widgets/utils.py
On the context of:
https://github.com/SpikeInterface/spikeinterface/issues/2957
I re-activated the tests that no import should take longer than 2.5 seconds. Fingers crossed but I will have my eyes on numba and torch which I did not move.
> Improve import times with full

- src/spikeinterface/extractors/nwbextractors.py
I'm getting `AttributeError: 'Group' object has no attribute 'timestamps'` error when accessing an NWB recording with explicit timestamps. This seems to resolve the error.
> Fix timestamps access in NWB extractor

- src/spikeinterface/postprocessing/unit_localization.py
- src/spikeinterface/sortingcomponents/clustering/circus.py
Currently, unit_locations can not be properly computed for return_scaled=False, because the argument (inherited from the analyzer) is not propage to the get_dense_template() local call
> Patch unit location

- src/spikeinterface/extractors/phykilosortextractors.py
When the first value was a `nan` (because of no value), we ended up with the wrong dtype (e.g. should have been `str`)
> Fix bug with nan values

- doc/releases/0.100.5.rst
- doc/releases/0.100.6.rst
- doc/releases/0.100.7.rst
- doc/whatisnew.rst
- pyproject.toml
- src/spikeinterface/__init__.py
@samuelgarcia 
I would merge this (#2827) first and release 0.100.7 bug fixes.
then this is ready to follow!
> Updated release notes and pyproject for 0.101.0rc0

- src/spikeinterface/sortingcomponents/tools.py
As explained in the doc (https://psutil.readthedocs.io/en/latest/#processes), "available" works better cross-platform. Additionally, "free" means that if a lot of RAM is used by the cache, then it won't pre-process, which is annoying
> Use "available" for memory caching

- .github/import_test.py
- src/spikeinterface/extractors/bids.py
- src/spikeinterface/extractors/mcsh5extractors.py
- src/spikeinterface/extractors/neoextractors/blackrock.py
- src/spikeinterface/extractors/neoextractors/spikeglx.py
- src/spikeinterface/sorters/internal/spyking_circus2.py
- src/spikeinterface/widgets/utils.py
Thanks to @zm711 whose profile helped in this [discussion](https://github.com/SpikeInterface/spikeinterface/issues/2957) to find out that import neo `import neo` imports scipy under the hood.
This should make the imports of the extractors module faster.
This should close #2957.
> Remove neo top level imports

- src/spikeinterface/core/baserecording.py
- src/spikeinterface/core/baserecordingsnippets.py
- src/spikeinterface/core/basesnippets.py
A continuation from https://github.com/SpikeInterface/spikeinterface/pull/2977 because I did not want to stop @DradeAW aurelien's job which was to get rid of an unfair warning.
As mentioned in the other discussion the current approach has the drawback of making the function harder to document (you don't get the docstring of the function correspondign to BaseRecording) plus it makes navigation harder. You click on the method and instead you get to `BaseRecordingSnippets` where the method is not implemented. All of that for no aparent gain (maybe I am wrong here?).
This PR fixes this.
> Avoid redirection to not implemented method in `BaseRecording.select_channels`

- src/spikeinterface/core/baserecording.py
- src/spikeinterface/core/baserecordingsnippets.py
- src/spikeinterface/core/basesnippets.py
From a comment in https://github.com/SpikeInterface/spikeinterface/pull/2977#issuecomment-2154864078 but for frame_slice.
This method is defined is only for base recording but then it points to `BaseRecordingSnippets` where the method is not implemented. This makes it harder for navigation when reading the code base for no benefit.
This PR defined overides the method in `BaseRecording` keeping the behavior in `BaseSnipets` and `BaseRecordingSnippets` the same as before. It also adds documentation to the function.
> Add documentation to `frame_slice` in recording and drop redundant inheritance

- pyproject.toml
This was solved:
https://github.com/int-brain-lab/ibllib/issues/753#event-13133745384
> Remove scipy upper bound for streaming extractors

- pyproject.toml
- src/spikeinterface/core/core_tools.py
- src/spikeinterface/core/tests/test_jsonification.py
- src/spikeinterface/generation/tests/test_template_database.py
- src/spikeinterface/preprocessing/tests/test_highpass_spatial_filter.py
- src/spikeinterface/preprocessing/tests/test_interpolate_bad_channels.py
- src/spikeinterface/sortingcomponents/peak_localization.py
- src/spikeinterface/sortingcomponents/tests/test_waveforms/test_waveform_thresholder.py
- src/spikeinterface/sortingcomponents/waveforms/waveform_thresholder.py
The goal of this PR is to fix the failing tests so we can move on.
Plus, this should make the core compatible with numpy 2.0.
We can't offer support yet because some packages (like scipy and numba) would require us to put lower versions on them. 
We can discuss how to move forward with this in an issue that I will link soon.
> Numpy 2.0 cap Fix most egregorious deprecated behavior and cap version

- src/spikeinterface/sorters/basesorter.py
- src/spikeinterface/sorters/external/mountainsort5.py
This is a bug that has both bothered me and not been annoying enough for me to hunt it down until now.  :)
also cleaned up an import in mountainsort.
Since we just check that the `is_filtered` method exists it always returns `True` even if a recording is not filtered and then says that the sorter is filtered over the filter. This switches it to the actual check instead :)
> Make sure we check `is_filtered()` rather than bound method during run basesorter

- src/spikeinterface/core/baserecording.py
- src/spikeinterface/core/tests/test_baserecording.py
Many times when I use spikeinterface I wish had this facility. recording.time_slice() to avoid having to do the conversion myself. This PR adds the functionality and a test.
That said, I am not sure I really like name, any suggestions @zm711, @JoeZiminski? 
I am thinking on discoverability.
I think that if the methods started by slice it would be nice to get the auto-completition to either complete it to time or frame but  because they are not
Maybe there is a better name?
> add recording.time_slice like recording.frame_slice

- .github/workflows/installation-tips-test.yml
The mac install has been failing for the past few months.... Based on the instructions it seems like the solution is to 
provide miniconda version so it is downloaded for safety on Mac.
https://github.com/conda-incubator/setup-miniconda
Also updated to v3. Not sure if we want me to switch to push to test or if we just want to merge and then fix after the next cron job if there is a problem?
> Update cron job for `installation_tips`

- src/spikeinterface/preprocessing/astype.py
- src/spikeinterface/preprocessing/depth_order.py
- src/spikeinterface/preprocessing/detect_bad_channels.py
- src/spikeinterface/preprocessing/filter.py
- src/spikeinterface/preprocessing/normalize_scale.py
- src/spikeinterface/preprocessing/phase_shift.py
- src/spikeinterface/preprocessing/resample.py
- src/spikeinterface/preprocessing/silence_periods.py
Update docstrings in Preprocessing module to be compliant with PR01 and PR02 from numpydoc.
These rules are...
https://numpydoc.readthedocs.io/en/latest/validation.html#
"PR01": "Parameters {missing_params} not documented",
"PR02": "Unknown parameters {unknown_params}",
...and ensure that the function argument agrees with the Parameters listed in docstrings.
> Docstrings preprocessing update, fix PR01 and PR02

- src/spikeinterface/postprocessing/tests/common_extension_tests.py
- src/spikeinterface/postprocessing/tests/test_align_sorting.py
- src/spikeinterface/postprocessing/tests/test_amplitude_scalings.py
- src/spikeinterface/postprocessing/tests/test_correlograms.py
- src/spikeinterface/postprocessing/tests/test_isi.py
- src/spikeinterface/postprocessing/tests/test_noise_levels.py
- src/spikeinterface/postprocessing/tests/test_principal_component.py
- src/spikeinterface/postprocessing/tests/test_spike_amplitudes.py
- src/spikeinterface/postprocessing/tests/test_spike_locations.py
- src/spikeinterface/postprocessing/tests/test_template_metrics.py
- src/spikeinterface/postprocessing/tests/test_template_similarity.py
- src/spikeinterface/postprocessing/tests/test_unit_localization.py
This PR removes `unittest` from the tests in the `postprocessing` module. Overall it:
1) Removes `unittest` and changes the `setUpClass` (the running of which was handlded by `unittest`) to a pytest fixture. This still is setup only once-per-subclass instantiation and the run-time of the `postprocessing` tests is within a few seconds of the old runtime.
2) Slightly reworks how `test_extension` is called. Now each subclass has its own `test_extension` function that calls the base class `run_extension_tests`, and the parameters are parameterised which means `pytest` runs 1 test per parameter set. This gives a bit more granulatiry to the test output.
3) In a couple of places add `sparsity` as a test parameterization rather than a loop, for the benefit for separating the tests in the output. …
> Remove unittest from postprocessing

- src/spikeinterface/extractors/cellexplorersortingextractor.py
- src/spikeinterface/extractors/iblextractors.py
Just some deprecations that have been there.
> Cell explorer deprecations

- src/spikeinterface/extractors/neoextractors/intan.py
- src/spikeinterface/widgets/traces.py
The `ignore_integrity_checks` keyword that was added recently was not propagated to the kwargs. So running thing in parallel with a context other than fork was not working. This PR fixes it.
This also indicates that there are some missing tests there if this behavior was missing. I will think on how to add a general test to see that al kwargs are catched in another PR.
> Fix intan kwargs

- src/spikeinterface/core/generate.py
- src/spikeinterface/sorters/external/kilosort4.py
Plus some safe casting in the InjectTemplateRecording
Fixes #3050 #3020 #3007
> Add support for kilosort>=4.0.12

- src/spikeinterface/postprocessing/tests/common_extension_tests.py
This PR removes a duplicate-named function from the `postprocessing` common test class. All tests pass, I think this function was just overridden by the below version and was silent.
> Remove duplicate function from common test suite.

- src/spikeinterface/core/baserecording.py
- src/spikeinterface/core/frameslicerecording.py
`FrameSlice` sets defaults of 0 and num_samples when start_frame and end_frame are not passed respectively:
https://github.com/h-mayorquin/spikeinterface/blob/bd626b0b4fbf4bfa5cfa68e857fb8ea997784c56/src/spikeinterface/core/frameslicerecording.py#L33-L45
But currently, this behavior is not available in frame_slice. This PR propagates this behavior to both frame_slice and time_slice to make it consistent.
> Propagate FrameSlice default behavior to frame_slice and time_slice

- src/spikeinterface/core/sortinganalyzer.py
- src/spikeinterface/core/tests/test_sortinganalyzer.py
Fixes #3041 
Based on our discussion today. This patch is tested and working for `select_units`.
> Skip loading `info.json` into `ext.data`

- src/spikeinterface/postprocessing/spike_locations.py
Fixes #3010
Removes `get_template_extremum_channel`, and hence the dependency on the `templates` extension, from the `SpikeLocations` init. It looks like we don't need to saves `spikes` at all in the extensions, I completely removed this line (this is similar to `ComputeSpikeAmplitudes`). @samuelgarcia can you double check this?
Note for #2984, on how to test this. The problem here was that `SpikeLocations` couldn't be initialised without `Templates` being present. To test this we could add something to the `AnalyzerExtensionCommonTestSuite`. Perhaps at the end, we could delete all extensions except the one we're interested in, then save it and load it. This would test that each extension can be saved loaded independent of what other extensions exist? @JoeZiminski thoughts?
> Remove get_template_extremum_channel from spikelocations init

- examples/tutorials/core/plot_3_handle_probe_info.py
If you do 
```python
>>> a_dict = {0: 'a', 1: 'b'}
>>> a, b = a_dict
>>>print(a)
0
>>>print(b)
1
```
which means people will do this wrong. I think maybe we switched the default from list to dict as some point. So I added a note in the explanation that you can choose the output and then fixed the example for the dict output instead.
> Fix the probe handling tutorial

- src/spikeinterface/extractors/neoextractors/plexon2.py
The header for signals in plexon data:
```python
'signal_channels': array([('WB01', 'source3.1', 40000., 'int16', 'Volts', 1.52587891e-07, 0., '3'),
('WB02', 'source3.2', 40000., 'int16', 'Volts', 1.52587891e-07, 0., '3'),
('WB03', 'source3.3', 40000., 'int16', 'Volts', 1.52587891e-07, 0., '3'),
('WB04', 'source3.4', 40000., 'int16', 'Volts', 1.52587891e-07, 0., '3'),
('WB05', 'source3.5', 40000., 'int16', 'Volts', 1.52587891e-07, 0., '3'),
('WB06', 'source3.6', 40000., 'int16', 'Volts', 1.52587891e-07, 0., '3'),
('WB07', 'source3.7', 40000., 'int16', 'Volts', 1.52587891e-07, 0., '3'),
('WB08', 'source3.8', 40000., 'int16', 'Volts', 1.52587891e-07, 0., '3'),
('WB09', 'source3.9', 40000., 'int16', 'Volts', 1.52587891e-07, 0., '3'),
('WB10', 'source3.10', 40000., 'int16', 'Volts', …
```
> Use names as channel ids in plexon2

- src/spikeinterface/core/baserecording.py
- src/spikeinterface/core/frameslicerecording.py
- src/spikeinterface/core/generate.py
- src/spikeinterface/core/segmentutils.py
- src/spikeinterface/core/tests/test_binaryrecordingextractor.py
- src/spikeinterface/extractors/cbin_ibl.py
- src/spikeinterface/extractors/iblextractors.py
- src/spikeinterface/extractors/nwbextractors.py
- src/spikeinterface/preprocessing/average_across_direction.py
- src/spikeinterface/preprocessing/decimate.py
- src/spikeinterface/preprocessing/deepinterpolation/deepinterpolation.py
- src/spikeinterface/preprocessing/directional_derivative.py
- src/spikeinterface/preprocessing/phase_shift.py
- src/spikeinterface/preprocessing/remove_artifacts.py
- src/spikeinterface/preprocessing/resample.py
- src/spikeinterface/preprocessing/silence_periods.py
- src/spikeinterface/preprocessing/zero_channel_pad.py
- src/spikeinterface/sorters/external/kilosort4.py
Following up on #3055, this PR moves the logic of checking and setting `start/end_frame` in the `BaseRecording.get_traces` instead of leaving it to the segments. 
This simplifies a lot the `segment.get_traces()`
@JoeZiminski
> Check start_frame/end_frame in `BaseRecording.get_traces()`

- doc/modules/core.rst
- doc/modules/postprocessing.rst
- src/spikeinterface/postprocessing/template_metrics.py
In response to issue #2309.
Correct documentation on `compute_template_metrics` which had incorrect units for `repolarization_slope` and `recovery_slope`. The correct units are "units of the templates" per second, rather than `V/s`.
Also added a few more details to the docs, and updated docstrings of several of the template metrics to be more precise about units.
> Correct docs and docstrings for compute_template_metric units

- .github/workflows/caches_cron_job.yml
Two things into this PR. As discussed with everyone the impact of caching the virtual environment is minimal and the impact of caching on the datasets is too large. The first one is 3 vs 5 minutes whereas the latter one is 3 vs 50 minutes.
Plus, there is already [caching functionality](https://github.com/actions/setup-python?tab=readme-ov-file#caching-packages-dependencies) in the setup-python action. I can test that after we get this caching running.
This PR enables caching for windows and macos.
Hopefully this works OK for windows when datasets are not downloaded file by file otherwise I will need a hack for windows : )
> Add macos and windows to cache cron jobs

- doc/api.rst
- doc/modules/extractors.rst
- src/spikeinterface/extractors/cbin_ibl.py
- src/spikeinterface/extractors/herdingspikesextractors.py
- src/spikeinterface/extractors/iblextractors.py
- src/spikeinterface/extractors/neoextractors/alphaomega.py
- src/spikeinterface/extractors/neoextractors/biocam.py
- src/spikeinterface/extractors/neoextractors/blackrock.py
- src/spikeinterface/extractors/neoextractors/ced.py
- src/spikeinterface/extractors/neoextractors/intan.py
- src/spikeinterface/extractors/neoextractors/maxwell.py
- src/spikeinterface/extractors/neoextractors/neuralynx.py
- src/spikeinterface/extractors/neoextractors/plexon2.py
- src/spikeinterface/extractors/neoextractors/spikegadgets.py
- src/spikeinterface/extractors/neoextractors/tdt.py
- src/spikeinterface/extractors/toy_example.py
- src/spikeinterface/preprocessing/filter.py
Update docstrings in public Extractors module functions to be compliant with PR01 and PR02 from numpydoc.
(also fix a whitespace error in Preprocessing)
Two controversial changes:
- This update BREAKS `BiocamRecordingExtractor`, `SpikeGadgetsRecordingExtractor` and `BlackrockRecordingExtractor`, which all had an unused `block_index` parameter in their `__init__`. I think it's better to delete these than to document something which is unused => can create unexpected behaviour. Is this a problem @alejoe91 @samuelgarcia ?
- `read_openephys` still fails PR01 and PR02 because the Parameters are bundled in a `kwargs` dict. But the Parameters are very helpful and, from the user point of view, can be passed as "normal" parameters. Not sure what to do. Code here: …
> Docstrings extractors update, fix PR01 and PR02 #3016

- src/spikeinterface/sorters/tests/test_runsorter.py
See https://github.com/SpikeInterface/spikeinterface/actions/runs/9693230325/job/26748253219?pr=3090
Let's not waste too much time here for the time being since it seems a 3rd party problem
> Mark failing sorter test on Windows*Python3.12 as xfail

- .gitignore
Further to the comment [here](https://github.com/SpikeInterface/spikeinterface/pull/2879#discussion_r1656732438), this PR adds `*sg_execution_times.rst` to the gitignore so it is ignored wherever it may be found. This file is generated automatically when building docs.
> Add `*sg_execution_times.rst` to gitignore.

- src/spikeinterface/sorters/basesorter.py
As in the title.
In the current PR:
```json
{
"sorter_name": "kilosort3",
"sorter_version": "compiled",
"datetime": "2024-06-20T19:08:55.934035",
"runtime_trace": [
"Warning: X does not support locale C.UTF-8",
"Time   0s. Computing whitening matrix..",
"Getting channel whitening matrix...",
"Channel-whitening matrix computed.",
"Time   2s. Loading raw data and applying filters...",
"Time   2s. Finished preprocessing 4 batches.",
"Drift correction ENABLED",
"vertical pitch size is 20",
"horizontal pitch size is 20",
"0    10    20",
"",
"6",
"",
"----------------------------------------Index in position 1 exceeds array bounds. Index must not exceed 4."
],
"error": true,
"error_trace": [
"Traceback (most recent call last):",
"  File …
```
> Improve error log to json in run_sorter

- src/spikeinterface/sorters/runsorter.py
- src/spikeinterface/sorters/tests/test_runsorter_dependency_checks.py
- src/spikeinterface/sorters/utils/__init__.py
- src/spikeinterface/sorters/utils/misc.py
This PR closes #2855 by adding in additional checks on container and GPU dependencies when running `run_sorter()`. 
It adds checks that `docker` or `singularity` are installed (if running sorter with `docker` or `singularity` respectively) and also that the corresponding python packages `docker` and `spython` are installed. It also show a warning if, on Linux, some nvidia-docker tools are not available, which  are usually necessary. See #2855 for a disucssion, but these nvidia-docker dependencies are a little complex so instead of raising an error, only a warning is shown.
I tested all locally and they work okay. It is not easy to test these nvidia-docker checks in code and so have left these, they raise only a warning anyway. The tests are a little bit 'extra', in particulary testing …
> Add more container dependency checks in `run_sorter`

- src/spikeinterface/core/generate.py
closes #3077 by removing the unused `unit_params_range` in `generate.py`. This previously allowed the user to set the parameters for templates injected into synthetic recordings. However I think it was superceeded by `unit_params`. @samuelgarcia you were correct on #3077 `unit_params` can take a tuple in which case it will use these as bounds to generate template parameters randomly. So `unit_params` performs the job of `unit_params_range`.
> Remove unit_params_range from generate.py

- src/spikeinterface/core/baserecording.py
In `BaseRecordingSegment.time_to_sample_index()` the calculation from time was cast from `float` to `int`. By default this will use floor method of rounding, which can lead to wrong results e.g. doing:
```
sample = 500
time_ = recording.sample_index_to_time(sample)
sample_again = recording.time_to_sample_index(time_)
```
Could lead to `sample` not equalling `sampling_again`.
This PR is tested in #3118.
> Round instead of int for `time_to_sample_index`.

- src/spikeinterface/exporters/tests/test_export_to_phy.py
- src/spikeinterface/exporters/to_phy.py
> Improve export to Phy property handling

- src/spikeinterface/core/base.py
As in the title, related to 
https://github.com/SpikeInterface/spikeinterface/issues/3049
Looks like this:
> Add more helpful error when a non-existent id is passed to extractors

- src/spikeinterface/extractors/mcsh5extractors.py
Adding the offsets from the mcs5h header in order to have a recording with offset_to_UV and gain_to_UV. In addition, the gain was entered in V, and thus the scaling was not really making sense. As far as I understand, we want to have return_scaled returning values in uV, am I right? If yes, this is doing the job here, given the documentation that can be found online
https://www.multichannelsystems.com/sites/multichannelsystems.com/files/documents/manuals/HDF5%20MCS%20Raw%20Data%20Definition.pdf
> Mcsh5 offsets and proper scaling in uV for return_scaled

- src/spikeinterface/core/channelsaggregationrecording.py
Following up a @zm711 request in #2797:
https://github.com/SpikeInterface/spikeinterface/pull/2797#discussion_r1589532970
The errors now tell the user explictly what went wrong.
> More explicit consistency checks for Channel aggregation 

- src/spikeinterface/core/base.py
Related to the discussion in #3148.
> Saving provenance with paths relative to folder

- README.md
So double quotes works on all operating systems, see:
https://github.com/catalystneuro/neuroconv/issues/947
https://discuss.python.org/t/pep-621-how-to-specify-dependencies/4599/61
> Change installation instructions in readme to be compatible with all OS

- src/spikeinterface/core/base.py
As in the title, related to issue https://github.com/SpikeInterface/spikeinterface/issues/3148
> Better error message for `BaseExtractor.load()` 

- src/spikeinterface/core/tests/test_unitsaggregationsorting.py
- src/spikeinterface/core/unitsaggregationsorting.py
> Units aggregation preserve unit ids of aggregated sorters

- src/spikeinterface/extractors/neoextractors/plexon.py
Related to this discussion in neo:
https://github.com/NeuralEnsemble/python-neo/issues/1507
> Use names as ids in Plexon1 recording extractor

- src/spikeinterface/extractors/neoextractors/alphaomega.py
- src/spikeinterface/extractors/neoextractors/axona.py
- src/spikeinterface/extractors/neoextractors/biocam.py
- src/spikeinterface/extractors/neoextractors/blackrock.py
- src/spikeinterface/extractors/neoextractors/ced.py
- src/spikeinterface/extractors/neoextractors/edf.py
- src/spikeinterface/extractors/neoextractors/intan.py
- src/spikeinterface/extractors/neoextractors/maxwell.py
- src/spikeinterface/extractors/neoextractors/mcsraw.py
- src/spikeinterface/extractors/neoextractors/mearec.py
- src/spikeinterface/extractors/neoextractors/neuralynx.py
- src/spikeinterface/extractors/neoextractors/neuroexplorer.py
- src/spikeinterface/extractors/neoextractors/neuroscope.py
- src/spikeinterface/extractors/neoextractors/nix.py
- src/spikeinterface/extractors/neoextractors/openephys.py
- src/spikeinterface/extractors/neoextractors/spike2.py
- src/spikeinterface/extractors/neoextractors/spikegadgets.py
- src/spikeinterface/extractors/neoextractors/spikeglx.py
- src/spikeinterface/extractors/neoextractors/tdt.py
Should fix https://github.com/SpikeInterface/spikeinterface/issues/3194
This just make the option available but does not switch default behavior.
> Propagate option for using neo channel names as ids in all neo extractors without changing the deafult behavior

- src/spikeinterface/core/sortinganalyzer.py
Mostly just cleaning up the `merge_units` docstring for the release. We could probably do more cleanup later, but these are the big ones I saw.
> Analyzer docstring cleanup

- src/spikeinterface/sortingcomponents/tools.py
as in title! nan median is needed in case some waveforms are flat!
> Protect median against nans in get_prototype_spike

- src/spikeinterface/sorters/external/herdingspikes.py
Small addition for a new sorter parameter, will also now respect `verbose=False`.
> added lowpass parameter, fixed verbose option

- src/spikeinterface/extractors/tests/test_iblextractors.py
> Test IBL skip when the setting up the one client fails

- src/spikeinterface/sorters/external/kilosort4.py
This PR edits `kilosort4.py` to expose the `save_preprocessed_copy` parameter. Now, `temp_wh.dat` is saveed to the sorting output and `params.py` is edited to point `phy` to the `temp_wh.dat.` @carlacodes if you have some time maybe you could check off this fork/branch this is behaving as expected? I tested with the below code:
<details><summary> Test code </summary>
```
recording, _, sorting = si.generate_drifting_recording(
duration=10.0,
generate_displacement_vector_kwargs=dict(
displacement_sampling_frequency=5.0,
drift_start_um=[0, 20],
drift_stop_um=[0, -20],
drift_step_um=1,
motion_list=[
dict(
drift_mode="zigzag",
non_rigid_gradient=None,
t_start_drift=None,
t_end_drift=None,
period_s=200,
),
],
),
)
si.run_sorter("kilosort4", …
```
> Expose save preprocessing in ks4

- src/spikeinterface/curation/curation_format.py
- src/spikeinterface/curation/tests/sv-sorting-curation-no-merge.json
- src/spikeinterface/curation/tests/test_sortingview_curation.py
Fixes #3308 
In the case where no merges are made in sortingview, two errors are thrown. 
First error is due to sortingview not returning a curation_dict with a "mergeGroups" key which hopefully I fixed. 
Second error is due to type mismatch between labeled units and unit list. This one still needs to be fixed. 
Edit: Second error fixed. I believe this PR is ready to be reviewed.
> Fix sortingview curation no merge case 

- src/spikeinterface/core/baserecording.py
- src/spikeinterface/core/zarrextractors.py
This was previously discussed here: https://github.com/SpikeInterface/spikeinterface/pull/2828
To sum up, loading and decompressing zarr timestamps for very long recordings can be quite time consuming, so we want to avoid doing that at init. When fetching the timestamps though, if they ar not a numpy array they are cast and cached as np.arryas, to avoid re-reading and re-decompressing at every call
> Lazy loading of zarr timestamps

- pyproject.toml
Python 3.9 is going in October:
https://devguide.python.org/versions/
See #3253 plus we are not testing for python 3.8 in the CI. 
Let's drop it.
> Drop python 3.8 in pyproject.toml

- src/spikeinterface/extractors/neoextractors/alphaomega.py
- src/spikeinterface/extractors/neoextractors/axona.py
- src/spikeinterface/extractors/neoextractors/ced.py
- src/spikeinterface/extractors/neoextractors/intan.py
- src/spikeinterface/extractors/neoextractors/plexon.py
- src/spikeinterface/extractors/neoextractors/plexon2.py
- src/spikeinterface/extractors/neoextractors/spikegadgets.py
- src/spikeinterface/extractors/neoextractors/spikeglx.py
To increase documentation for users that don't read the docs but instead use `help` or their IDE docstring reader we could begin to add examples to the code base. `read_intan` is the clearest for what I would like examples to be, but I think even beginning to add examples that we flesh out later would be an incremental improvement (for example intan stream_id ='0' is for amplifier data. I could also add an example with how to use name.
What do people think about this in general?
> Proposal for adding Examples to docstrings

- src/spikeinterface/core/baserecording.py
The current repr is rounded to int even it is not which is deceiving. I discussed this with @alejoe91 in person. 
Screenshoot of the new behavior:
> Fix sampling frequency repr

- pyproject.toml
…query
Fixes #3306  issue of missing the `sphinxcontrib.jquery` to the pyproject.toml.
Still needs to address other components of that issue.
> Added sphinxcontrib-jquery

- src/spikeinterface/widgets/sorting_summary.py
- src/spikeinterface/widgets/utils_sortingview.py
Hi all — I'm wondering about the status of sortingview (see https://github.com/magland/sortingview/issues/233), and how close it is to being a phy replacement. In the meantime, I implemented a small change whereby you can add in any quality and template metrics that have been computed to the sortingview window — this gets it one step closer to being like Phy :) happy to accommodate any suggestions. Thanks!
> Allow quality and template metrics in sortingview's unit table

- src/spikeinterface/core/base.py
- src/spikeinterface/core/tests/test_base.py
I added two things around `set_property` and `set_annotations` in `base.py`:
1) Typing to inputs
2) More meaningful errors that describe the nature of the problem to the user.
I started adding tests but then I found a bug that I will report in an issue. I will fix the bug after we merge this.
[EDIT] This is the error that I stumbuled upon https://github.com/SpikeInterface/spikeinterface/issues/3288
> Refactor `set_property` in base

- src/spikeinterface/core/base.py
- src/spikeinterface/core/core_tools.py
- src/spikeinterface/core/sortinganalyzer.py
While troubleshooting for #3348, I noticed some odd behavior with zarr-based sorting analyzers. Specifically, in some parts of the code, it seemed like the user would be permitted to pass a folder name with the `.zarr` suffix included (ie `folder=/my/favorite/analyzer/` instead of `folder=/my/favorite/analyzer.zarr/`). This led to two error cases when using `create_sorting_analyzer` if the user tried to make a new folder without the suffix: 
1) it would be created by [create_zarr](https://github.com/SpikeInterface/spikeinterface/blob/007b6efd0e675e60658199112d0541fba2b432cd/src/spikeinterface/core/sortinganalyzer.py#L272) [with the suffix](https://github.com/SpikeInterface/spikeinterface/blob/007b6efd0e675e60658199112d0541fba2b432cd/src/spikeinterface/core/sortinganalyzer.py#L492), but …
> Fix zarr folder suffix handling

- src/spikeinterface/comparison/paircomparisons.py
as mentioned here : https://github.com/SpikeInterface/spikeinterface/issues/3344
print_summary failed despite exhaustive_gt being set to False
> Fix print_summary for reporting when not exhaustive_gt

- doc/api.rst
- src/spikeinterface/core/__init__.py
- src/spikeinterface/core/waveforms_extractor_backwards_compatibility.py
Helper function to be able to load with the same API either an old waveform extractor folder as an analzyer or a newly created sorting analyzer object
> Add `load_sorting_analyzer_or_waveforms` function

- .github/workflows/all-tests.yml
- src/spikeinterface/widgets/tests/test_widgets.py
- src/spikeinterface/widgets/utils_sortingview.py
Not sure how but https://github.com/SpikeInterface/spikeinterface/pull/3299 broke a bunch of widgets tests that were uncaught and are showing up in the daily full tests.
The fix here is that the `generate_unit_table_view` needs to support both a `SortingAnalyzer` and a `BaseSorting`, because it's used by other widgets as well
> Fix widgets tests and add test on unit_table_properties

- src/spikeinterface/extractors/phykilosortextractors.py
At the moment, this specific column which we know is a string is unnecessarily read as an object.
This is a simple patch so this property is converted as a string.
Another possible more general solution is to use this function from pandas after reading the cluster info data frames and merging
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.convert_dtypes.html 
I think this could simplify the logic here where we do the casting:
https://github.com/h-mayorquin/spikeinterface/blob/5953d6cdaac993928988a715725b824edf11d00a/src/spikeinterface/extractors/phykilosortextractors.py#L167-L183
@pauladkisson
> "quality" property to be read as string instead of object in `BasePhyKilosortSortingExtractor`

- src/spikeinterface/core/baserecording.py
- src/spikeinterface/core/tests/test_baserecording.py
This is a convenience function to discard time_vector information. It only acts in memory
> Add `BaseRecording.reset_times()` function

- src/spikeinterface/core/tests/test_time_handling.py
@JoeZiminski I realized that the `test_sorting_analyzer_get_durations` test was using up 10s of GBs of RAM!
This is because the cumulative offsets ended up creating durations of over 30'000 seconds, used to generate sorting objects. I refactored the test to "manually" extend the duration with a simple linspace
> Fix time handling test memory

- src/spikeinterface/core/baserecording.py
- src/spikeinterface/core/tests/test_baserecording.py
Fixes a bug in reset times that causes issues downstream, since rec segments must have either a `sampling_frequency` or a `time_vector`
> Reset-times: segment must have either time vector or sampling frequency

- src/spikeinterface/postprocessing/template_metrics.py
- src/spikeinterface/qualitymetrics/quality_metric_calculator.py
Being extra careful is never enough! We simply don't want a full pipeline to fail because computing `spread` for a single unit fails...
> Add extra protection for template metrics

- src/spikeinterface/core/core_tools.py
- src/spikeinterface/core/recording_tools.py
A couple of minor typing fixes that I found while trying to erroneously removing `from __future__ import annotations` :)
> Minor typing fixes

- src/spikeinterface/core/segmentutils.py
Fix integer overflow of the total sample number when concatenating long recordings.
The bug occurs when concatenating recordings exceeding 24 hours in total length at a 30000 Hz sampling rate, leading to integer overflow in `np.sum` function.
Simply adding `dtype=np.int64` in `np.sum` resolves this bug.
> Fix integer overflow of the total sample number when concatenating long recordings

- src/spikeinterface/core/sortinganalyzer.py
- src/spikeinterface/core/tests/test_sortinganalyzer.py
Fixes #3329
Here's a first pass at adding information about an extension's completion (or not) to its metadata.
This PR adds a `run_info.json` file to each extension's folder. This contains keys:
* `run_completed` (whether or not the call to `AnalyzerExtension._run()` finished),
* `data_loadable` (whether or not `AnalyzerExtension.load_data()` can be called without an error) 
* `runtime_s` (the runtime of `AnalyzerExtension._run()` in seconds). 
The core logic is implemented in `AnalyzerExtension.run()` and wraps the call to the extension-specific `_run()`. Then when `AnalyzerExtension.get_extension()` is called (and redirects to `AnalyzerExtension.load()` internally), if the run wasn't completed, it simply returns None as if the extension doesn't exist, and the user would be able to …
> Analyzer extension exit status

- src/spikeinterface/core/sortinganalyzer.py
- src/spikeinterface/core/tests/test_analyzer_extension_core.py
- src/spikeinterface/core/tests/test_sortinganalyzer.py
> Ensure sorting analyzer in zarr are consolidated

- doc/development/development.rst
> Add decision about headers to dev docs

- src/spikeinterface/core/baserecordingsnippets.py
- src/spikeinterface/core/recording_tools.py
- src/spikeinterface/core/sortinganalyzer.py
- src/spikeinterface/core/tests/test_baserecording.py
- src/spikeinterface/core/tests/test_sortinganalyzer.py
This should solve #3389 and replace #3389
@RobertoDF : could you check on your side that it solve the original problem.
This is untested at the moment, if this works I will push some tests and continue to improve this way.
EDIT:
@JoeZiminski 
Here the problem:
1. Having a `Probe` is similar to having the `contact_vector` respresentation
2. in a recording the `contact_vector`  is always sorted so that `device_channel_indices` = np.arange(num_channels)
3. For the ProbeGroup this is the same only and only the channel of Probes are NOT interlaved otherwise 
having the `ProbeGroup` (which is a list Probe) is different from having the full `contact_vector` because the 
ProbeGroup do not ensue th step 2. when channels of probes of interleaved
> Fix proposal for channel location when probegroup

- src/spikeinterface/widgets/utils_sortingview.py
Recently we added a `format_float_positional` for sortingview properties, but this must be applied only to floats
> Sortingview: only round float properties

- src/spikeinterface/core/baserecording.py
- src/spikeinterface/sorters/external/kilosort4.py
- src/spikeinterface/sorters/external/kilosortbase.py
@alejoe91, I'm not sure what the problem is here; I wanted to check if we check for 'int16' in KS which we do. I noticed a typo so I fixed it, but does this check not actually fix the problem for users (related to #3404)?
> Fix argument spelling in check for binary compatibility

- src/spikeinterface/core/sortinganalyzer.py
> Check run info completed only if it exists (back-compatibility)

- pyproject.toml
- src/spikeinterface/core/sortinganalyzer.py
- src/spikeinterface/postprocessing/template_metrics.py
- src/spikeinterface/postprocessing/tests/common_extension_tests.py
- src/spikeinterface/qualitymetrics/quality_metric_calculator.py
We found out that zarr consolidation doens't seem to play well with our way of saving/loading dataframes to zarr, using xarray.
`xarray` was only used to save/load pandas dataframes to zarr, and this PR modifies that by saving each column and the index directly. This is similar to how xarray saves to zarr, so it should be backcompatible (testing now).
To make sure we don't run in such problems in the future, I added a roundtrip test in the common extension tests that asserts that data reloaded is the same as the original ones.
As sugegsted by @h-mayorquin here #3365, the generated and reloaded dataframes are also converted to numpy dtypes with the `convert_dtypes` function. We just have to make sure to call a `Series.to_numpy` to cast pandas dtypes to numpy ones.
> Refactor pandas save load and convert dtypes

- src/spikeinterface/preprocessing/motion.py
Fixes #3404
Thanks @jiumao2 for the suggestion
> Auto-cast recording to float prior to interpolation

- src/spikeinterface/core/baserecording.py
The times array loaded from zarr are converted to numpy arrays only when `get_times` is called. This resulted in an error when saving a zarr-based recording, since we were accessing times vector directly.
> Fix bug in saving zarr recordings

- src/spikeinterface/core/waveforms_extractor_backwards_compatibility.py
We need this otherwise the `get_data` will fail!
> Set `run_info` to `None` for `load_waveforms`

- src/spikeinterface/core/sortinganalyzer.py
- src/spikeinterface/postprocessing/principal_component.py
Fixes a bug that prevented runnning pipeline-based extensions with a temprary recording alone.
Also some other small fixes (e.g., removing some `we` variable names in pca postprocessing)
> Fix compute analyzer pipeline with tmp recording

- src/spikeinterface/core/job_tools.py
`frame_starts = np.arange(n) * chunk_size` will overflow when the recording is ~24 hours long and `chunk_size = "1s"`
Another integer overflow issue on long recordings following #3388
> Fix integer overflow in parallel computing

- .github/scripts/determine_testing_environment.py
- .github/workflows/all-tests.yml
- src/spikeinterface/extractors/tests/test_neoextractors.py
> Enable testing arm64 Mac architecture in the CI.

- src/spikeinterface/core/baserecording.py
- src/spikeinterface/core/baserecordingsnippets.py
This will make the method appear on the BaseRecording API on the docs.
Plus, I added a docstring to the method. 
No changes on behavior with this diff.
> Add `get_channel_locations` to the base recording api

- src/spikeinterface/core/generate.py
This function is missing a docstring.
> Add docstring for `generate_unit_locations` 

- src/spikeinterface/preprocessing/tests/test_filter.py
This has been popping up here and there in the causal filter tests..I think that `atol=1e-6` is too strict and some numerical approximations might make it fail
> Relax causal filter tests

- src/spikeinterface/core/sortinganalyzer.py
- src/spikeinterface/preprocessing/tests/test_filter.py
This PR allows to save an analyzer as binary or zarr even if recordingless
> Allow to save recordingless analyzer as

- src/spikeinterface/core/sortinganalyzer.py
- src/spikeinterface/core/tests/test_sortinganalyzer.py
- src/spikeinterface/core/zarrextractors.py
- src/spikeinterface/extractors/iblextractors.py
Generally, default compression works fine, but I've been hitting some errors with chunks being too large when analyzing very long NP recordings (>8h). 
This PR gives the possibility to modify the zarr arguments used to create a dataset. These can be passed at the `create_sorting_analyzer` or `save_as` step. The update test shows it in action
> Expose `backend_options` at the analyzer level to set `storage_options` and `saving_options`

- src/spikeinterface/core/baserecordingsnippets.py
Hey @alejoe91 the confusion in #3477 has come up multiple times. How about this as a change:
1) we check if the list is the wrong length (this is a rare mistake)
2) we see if they forgot to 0-index the list (this is the common mistake)
Happy to workshop this a bit if needed :) 
Just for clarity the current error saying you made a mistake because you have 32 values and you should have 32 values is super confusing, but the problem is that is actually the max value.
> Improve error message for `set_probegroup`/`set_probe`

- doc/modules/curation.rst
Saw a couple typos in curation and our `remove_redundant_units` always returns a sorting so I added a line to the example to take the unit_ids to generate a sorting analyzer with the "non-redundant" units.
> Fix a few typos in the curation docs

- src/spikeinterface/postprocessing/localization_tools.py
- src/spikeinterface/sortingcomponents/motion/dredge.py
For numpy 2.0 support -- `ggrep -R -P '(?<!np)\.ptp\(' src/*` says these were the last ones.
> Remove remaining array.ptp()s

- src/spikeinterface/preprocessing/whiten.py
In `whiten.py` there is a datatype argument to set the datatype of the output recording. The casting is performed after whitening has been performed and does not affect the datatype used for computing the whitening matrix. Up until `0.100.8`, the covariance matrix was always computed in `float32`, but in `0.101.0` the line `random_data = np.astype(random_data, np.float32)` that was [under this line](https://github.com/SpikeInterface/spikeinterface/blob/4a1a45a67db4534150d591bd5324e271ae8af740/src/spikeinterface/preprocessing/whiten.py#L187) was removed. Now if the recording is `int16` the covariance matrix estimation is performed in `int16` and will overflow in nearly all cases.
This PR reinstates that line, for now casting to `float64`. The recording `dtype` will be cast back to the …
> Whitening fix - compute covariance matrix in float

- src/spikeinterface/core/job_tools.py
- src/spikeinterface/core/node_pipeline.py
- src/spikeinterface/core/recording_tools.py
- src/spikeinterface/core/tests/test_node_pipeline.py
- src/spikeinterface/sortingcomponents/peak_detection.py
Add `recording_slices` option in `run_node_pipeline()`.
So we can run computation onyl on some partv of a recording.
Also propagated to peak_detection
> recording_slices in run_node_pipeline()

- src/spikeinterface/core/analyzer_extension_core.py
This is a light changing of the error messaging in the core extension file along with some docstring touch ups for numpydoc.
Related to #3495
> Add error messaging around use of get data in templates

- src/spikeinterface/exporters/report.py
- src/spikeinterface/widgets/autocorrelograms.py
- src/spikeinterface/widgets/crosscorrelograms.py
- src/spikeinterface/widgets/unit_summary.py
Small edit to `export_report` so that it will generate a report without waveforms.
When we're being speedy, we often don't compute or don't copy over waveforms. This PR just changes `export_report` so that it does/doesn't include the `UnitWaveformDensityMapWidget` if the sorting_analyzer does/doesn't have waveforms computed.
A unit report without waveforms:
computed using
```
rec, sort = si.generate_ground_truth_recording()
sa = si.create_sorting_analyzer(recording=rec, sorting=sort)
sa.compute(["random_spikes",  "templates", "spike_amplitudes", "correlograms", "template_similarity"])
si.export_report(sorting_analyzer=sa, output_folder="my_report")
```
> Allow `export_report` to run without waveforms

- src/spikeinterface/sorters/basesorter.py
The note says remove after 0.100 and this caused an issue recently #3448 with the error not being super clear (because recording was None) the  error the user saw was that None didn't have get_num_channels). Since this isn't supported we shouldn't write this here, right? I have run local tests because I need to run, so will update after the CI if needed.
> Remove Non-Serializable writing of json

- src/spikeinterface/preprocessing/decimate.py
- src/spikeinterface/preprocessing/tests/test_decimate.py
Deep bug in decimate, that deletes existing time vectors for segments!
This PR modifies the behavior so that `time_vectors` are also decimated, which is very intuitive.
Also skimmed a but the tests (previously 2100 tests with parameterized, now "only" 25)
> Don't let decimate mess with times and skim tests

- src/spikeinterface/postprocessing/template_metrics.py
- src/spikeinterface/postprocessing/template_similarity.py
- src/spikeinterface/postprocessing/unit_locations.py
Some extensions computed by the sorting analyzer should relax their dependencies, and do not need recording, as far as I am aware. Looks like template_similarity and template_metrics, once you have the templates, could be recomputed without the recording
> Removing useless dependencies

- src/spikeinterface/extractors/mdaextractors.py
Possible fix for #3532
Adds `verbose` as a kwarg to `write_recording` for `MdaRecordingExtractor` class, rather then it being in `job_kwargs`.
Probably missed when we removed `verbose` from `job_kwargs`. Does this look like a reasonable fix @zm711 ? This seems like a good time to check all the `RecordingExtractor`s.
> Add verbose kwarg to mda write_recording

- src/spikeinterface/extractors/cbin_ibl.py
> Fix cbin_file_path

- src/spikeinterface/core/baserecording.py
- src/spikeinterface/core/tests/test_time_handling.py
This PR adds a 'shift start time' function that a user can use to set a new start time for their recording.
This follows from discussions on the time API #3117 and #3157. Briefly, there are two ways to handle time in SI, a `t_start` recording attribute that is used to set the start time. Under this regime, the (regularly) spaced timeseries is regenerated on the fly from `t_start`, num samples and sampling frequency. Alternatively, a (more memory heavy) `time_vector` can be set to explicitly set the time array for a recording. As I understand it this is useful in the case there are gaps in the recording or there is some clock drift. From the user perspective, they always get a time vector back from `get_times()`.
This PR implements a `shift_start_time` as suggested by @h-mayorquin as a …
> Add `shift start time` function.

- src/spikeinterface/postprocessing/template_metrics.py
- src/spikeinterface/postprocessing/tests/test_template_metrics.py
- src/spikeinterface/qualitymetrics/pca_metrics.py
- src/spikeinterface/qualitymetrics/quality_metric_calculator.py
- src/spikeinterface/qualitymetrics/quality_metric_list.py
- src/spikeinterface/qualitymetrics/tests/test_metrics_functions.py
- src/spikeinterface/qualitymetrics/tests/test_quality_metric_calculator.py
Begin unifying template and quality metrics.
We recently discussed unifying the template and quality metric extensions. Here’s a proposal for starting that process. They’re already quite similar: the big difference is how they deal with parameters. Quality metrics have a parameter set for each metric, through the `qm_params` kwarg:
``` python
qm_params = {
'sd_ratio’: {
‘censored_period_ms’: 4.0
},
‘synchrony’: {
‘synchrony_sizes’: (2,4)
}
}
```
while the template metrics have one set of parameters shared between all metrics, through the `metrics_kwargs` kwarg:
``` python
metrics_kwargs = {
'recovery_window_ms’: 0.4,
‘spread_smooth_um’ : 20
}
```
This PR is a proposal to unify the parameter handling of the two metrics extensions, following the more flexible `qm_params` pattern, calling it …
> Unify template and quality metrics

- doc/get_started/quickstart.rst
- doc/modules/qualitymetrics/synchrony.rst
- src/spikeinterface/qualitymetrics/__init__.py
- src/spikeinterface/qualitymetrics/misc_metrics.py
- src/spikeinterface/qualitymetrics/tests/test_metrics_functions.py
Fix #3549
Currently there is one metric, `synchony`, whose column names depends on a kwarg: `synchony_sizes`. If the user inputs `synchony_sizes = [3,5,7]` the columns in the `quality_metrics` dataframe are `sync_spikes_3`, `sync_spikes_5` and `sync_spikes_7`. This is a bit awkward to deal with in a few places. Computing these custom `synchrony_sizes` are a bit of an edge case, so me @alejoe91 and @zm711 decided to just hard code the default values of `synchony_sizes = [2,4,8]`.
To help users who _really_ want to compute custom synchony sizes, I've left the `_compute_synchonry_counts` function (which is called by the user-facing `compute_synchrony_metrics` function) with the ability to do this, but made it private. 
No backwards compatibility issues spring to mind: using this PR you can …
> Hard code `synchony_sizes`

- src/spikeinterface/postprocessing/unit_locations.py
Fixes #3566
Correct the default `method` docstring in `compute_unit_locations`. Was `center_of_mass` but `monopolar_triangulation` is actually the default.
> Correct method default in docstring

- .github/actions/build-test-environment/action.yml
- .github/workflows/all-tests.yml
- .github/workflows/full-test-with-codecov.yml
- pyproject.toml
Thansk for the hint @h-mayorquin 
Tests passing: https://github.com/SpikeInterface/spikeinterface/actions/runs/12157608869
> Fix codecov tests

- src/spikeinterface/widgets/unit_waveforms.py
Currently, the ipywidget plot_unit_templates is not working when launched with sparse Templates and not SortingAnalyzer. This fixes the problem
> Patch to allow ipywidget plot_unit_templates to work with sparse templates (instead of analyzer)

- src/spikeinterface/benchmark/benchmark_motion_estimation.py
> MotionEstimationStudy : plot drift with the scatter plot

- src/spikeinterface/benchmark/benchmark_base.py
- src/spikeinterface/benchmark/benchmark_sorter.py
- src/spikeinterface/curation/auto_merge.py
During a benchmark_sorter study, it could be that a particular sorter is crashing. If we want to relaunch, the keep=False method will not work and relaunch will not be permitted because the files of the sorter are not deleted. This fixes the issue
> Fix use of keep during run_sorter benchmark

- examples/tutorials/widgets/plot_2_sort_gallery.py
#3588 broke one of the tutorials in the docs, since the selected `unit_id`s were integers, but should now by string.
This PR string-ifies the unit_ids to fix the docs.
> Convert generated unit_ids in docs to strings

- readthedocs.yml
Due to this: https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
> Fix sphinx doc build

- src/spikeinterface/widgets/sorting_summary.py
- src/spikeinterface/widgets/tests/test_widgets.py
- src/spikeinterface/widgets/utils.py
- src/spikeinterface/widgets/utils_sortingview.py
> Fix `plot_sorting_summary` widget 

- src/spikeinterface/preprocessing/average_across_direction.py
- src/spikeinterface/preprocessing/tests/test_average_across_direction.py
Fixes https://github.com/SpikeInterface/spikeinterface/issues/3626
channel_indices was unused in the segment's get_traces()! My apologies. This fixes and adds a test.
> Fix channels bug in average_across_direction, and add a test

- src/spikeinterface/core/baserecording.py
- src/spikeinterface/core/loading.py
Since the `__repr__` uses the `get_duration`s function, I added an option to avoid using timestamps to estimate duration. 
In fact, this can be quite slow for long zarr datasets with timestamps, since the whole array is loaded in mem when calling `get_times()`.
> Add `get_start_time`/`get_end_time` functions and use them in `get_duration`

- src/spikeinterface/preprocessing/average_across_direction.py
Addressing @samuelgarcia 's comment https://github.com/SpikeInterface/spikeinterface/pull/3631#discussion_r1923467538
> Check for channel_indices is None

- src/spikeinterface/widgets/traces.py
One of the most edge-case, inconsequential bugs ever: If your recording is < 1 second long and if you specify `time_range=(0, 1)` instead of `(0, 1.0)` then the cast from `tuple` to `array` will generate an `int` array. When`t_end` is assigned to it it will round to `0` leading to `time_range=(0, 0)` and failure to retrieve traces.
This is for a super-short example file I am using😅
> Make `time_range` conversion to array dtype `float64` 

- examples/tutorials/curation/plot_1_automated_curation.py
We ported the UnitRefine models in the SpikeInterface org in HF. This PR updates the models examples to reflect it
> Use SpikeInterface-ported pre-trained models in doc

- src/spikeinterface/core/sortinganalyzer.py
- src/spikeinterface/postprocessing/template_metrics.py
Might fix #3471
(Could you try this out please @jonpedros)
When `template_metrics` is computed and `delete_existing_metrics = False`, any old metrics which aren't being recomputed are kept. To do this, the `_run` method loads the old template metric extension (if it exists). However, if this is the first time it has run, it has already created the extension folder. In this case `_run` sees the newly-created folder and tries to load it. Bu there's not much in it, so a no `run_info` warning appears.
To avoid this, this PR only loads the extension folder if there are metrics to be kept.
I think the previous implementation of `load_run_info` was sending two warnings if a `run_info` file didn't exist. I think I've made the logic a bit simpler. Could one of the `run_info` experts take a look …
> Only load `template_metrics` extension on compute if keeping some metrics

- src/spikeinterface/postprocessing/principal_component.py
- src/spikeinterface/postprocessing/tests/test_principal_component.py
- src/spikeinterface/qualitymetrics/pca_metrics.py
Should fix #3653
Fixes bug where `get_some_projections` and `compute_pc_metrics` couldn't extract pcas when they were computed in concatenated mode. Fixing this allows pca quality metrics to be computed too.
Added a test which used to fail, and now passes.
Harder to test if this definitely works. Here's some evidence: it's code which computes the quality metrics in `concatenated` mode (with 20 components) and in non-concatenated mode (with `5x4=20` components), then computes the metrics. We wouldn't expect the results to be equal, but would expect them to be highly correlated, which they seem to be!
``` python
rec, sort = si.generate_ground_truth_recording()
sa_1 = si.create_sorting_analyzer(recording=rec, sorting=sort, folder="my_sa", …
```
> Allow for concatenated mode in `get_some_projections` and `compute_pc_metrics`

- examples/tutorials/curation/plot_1_automated_curation.py
Hi,
Right now the [example](https://spikeinterface.readthedocs.io/en/latest/tutorials/curation/plot_1_automated_curation.html) returns False at https://github.com/SpikeInterface/spikeinterface/blob/b22fc3774108dea1a7647a0f794acda43cb6af92/examples/tutorials/curation/plot_1_automated_curation.py#L82 because "sd_ratio" is calculated but not used by the model. This fixes the check.
> Fix  plot_1_automated_curation.py

- src/spikeinterface/core/baserecording.py
- src/spikeinterface/core/basesorting.py
- src/spikeinterface/core/tests/test_basesorting.py
In response to #3675
This PR allows the user to slice a sorting, so that you can do something like
``` python
reduced_sorting = sorting.time_slice(start_time = 60, end_time=120)
reduced_spike_train = reduced_sorting.to_spike_vector()
```
Code and test were essentially copied and pasted from the `BaseRecording` object's `time_slice` method. Then had to make a new `time_to_sample_index` function for the `BaseSorting`, whose logic was taken from `get_unit_spike_trains` here: 
https://github.com/SpikeInterface/spikeinterface/blob/4e34fc747115e91dde06bf2b42ea6bfe4d42616c/src/spikeinterface/core/basesorting.py#L169
This uses the attached recording if there is one, checks if there's a `_t_start`, and sets `_t_start` to zero if there isn't.
Only works for single-segment sorting objects, which …
> Add `time_slice` method to `BaseSorting`

- src/spikeinterface/core/base.py
- src/spikeinterface/core/baserecording.py
- src/spikeinterface/core/basesorting.py
I'm always finding myself searching through the kwargs to check the preprocessing chain...
@chrishalcrow you're gonna like this :) 
Added the `Parent` section in the HTML repr (and also appended the class name to the `self.name`). Here's how it looks:
> Add parents in HTML representation and always print class name

- pyproject.toml
Accidentally removed it when removing tridesclous and pymde and makes codecov tests fail.
> Add torch to test installation

- src/spikeinterface/extractors/mdaextractors.py
- src/spikeinterface/extractors/tests/test_mdaextractors.py
> Set max_channel property of MdaSortingExtractor

- src/spikeinterface/core/sparsity.py
- src/spikeinterface/core/tests/test_sparsity.py
It can be convenient to add the sparsity used by KS, i.e. simply selecting the N closest channels
> New sparsity (to add Ks clustering in components)

- src/spikeinterface/comparison/basecomparison.py
- src/spikeinterface/comparison/multicomparisons.py
- src/spikeinterface/comparison/tests/test_multisortingcomparison.py
Fixes #3734
@paul-aparicio 
@h-mayorquin developed a faster method for sorting comparison here https://github.com/SpikeInterface/spikeinterface/pull/2192, but that was not propagated to the `compare_multple_sorters`
With this PR, you can do `compare_multiple_sorters(..., agreement_method="distance")` and the speed should be much higher. Can you give it a try?
> Propagate `agreemennt_method` to `compare_multiple_sorters`

- src/spikeinterface/widgets/spike_locations_by_time.py
- src/spikeinterface/widgets/tests/test_widgets.py
- src/spikeinterface/widgets/widget_list.py
Add a `LocationsWidget` and `plot_locations`, to complement the `AmplitudesWidget`  and `plot_amplitudes`.
This plots the spike locations as a function of time, and is 99% the same as the `plot_amplitudes` function. You can control which direction you want to plot using e.g. `directions_axis = 'x'` and plot a histogram if you'd like.
An example:
``` python
_, drift_rec, sort = si.generate_drifting_recording(
num_units=2, 
duration=30,
generate_displacement_vector_kwargs=dict(
displacement_sampling_frequency=20.0,
drift_start_um=[0, 50],
drift_stop_um=[0, -50],
drift_step_um=5,
motion_list=[
dict(
drift_mode="zigzag",
non_rigid_gradient=None,
t_start_drift=0.0,
t_end_drift=None,
period_s=300,
),
],
)
)
sorting_analyzer = …
```
> Add LocationsWidget and plot_locations

- src/spikeinterface/core/channelsaggregationrecording.py
- src/spikeinterface/core/channelslice.py
- src/spikeinterface/core/tests/test_channelsaggregationrecording.py
This will fix @chrishalcrow bug on #3733.
The current check for `all_channels_have_same_type` is too strict. I added a test.
> Fix `aggregate_channels`  merging of channel ids with different string sub type 

- src/spikeinterface/extractors/neoextractors/neobaseextractor.py
Another victim of the changes on string representations with numpy 2.0:
```python
ValueError: This reader have several streams: 
Names: [np.str_('RHS2000 amplifier channel'), np.str_('USB board ADC input channel'), np.str_('USB board ADC output channel'), np.str_('USB board digital input channel'), np.str_('USB board digital output channel'), np.str_('DC Amplifier channel')]
IDs: [np.str_('0'), np.str_('3'), np.str_('4'), np.str_('5'), np.str_('6'), np.str_('10')]. 
Specify it from the options above with the 'stream_name' or 'stream_id' arguments
```
> Fix stream names and ids representation in numpy 2.0

- src/spikeinterface/core/baserecordingsnippets.py
- src/spikeinterface/core/channelsaggregationrecording.py
- src/spikeinterface/core/tests/test_channelsaggregationrecording.py
Related to #3711
Allows `aggregate_channels` to accept a dict of recordings. This allows for the workflow (once #3711 is merged) of the kind:
``` python
split_recordings = recording.split_by('group')
preprocessed_recordings = si.common_reference(si.bandpass_filter(split_recordings))
aggregated_preprocessing_recording = si.aggregate_channels(preprocessed_recordings)
```
or the truly horrifying
``` python
preprocessed_recording =  si.aggregate_channels(si.common_reference(si.bandpass_filter(recording.split_by('group'))))
```
edit: PR is mostly new tests
> Allow `aggregate_channels` to accept a dict of recordings

- src/spikeinterface/core/waveforms_extractor_backwards_compatibility.py
Looks like this one function got missed while adding backward compatibility for the old WaveformExtractor extensions.
Without this fix, I get the error:
```
waves = si.load_waveforms(paths['si_waveforms'], with_recording=False, sorting = sorting)
locs = waves.load_extension('unit_locations').get_data()
AttributeError: 'MockWaveformExtractor' object has no attribute 'load_extension'
```
> add `load_extension()` in `MockWaveformExtractor` for backwards compatibility

- src/spikeinterface/core/tests/test_unitsaggregationsorting.py
- src/spikeinterface/core/unitsaggregationsorting.py
- src/spikeinterface/postprocessing/template_metrics.py
- src/spikeinterface/postprocessing/tests/test_template_metrics.py
- src/spikeinterface/qualitymetrics/quality_metric_calculator.py
- src/spikeinterface/qualitymetrics/tests/test_metrics_functions.py
Fixes #3774
This PR changes the dtype check when we combine `sortings` using `aggregate_units`. This allows for two sortings to be combined whose longest strings are different lengths. 
Implementation details: we compare property types using `dtype.kind`. If these are the same, we let numpy have a go at concatenation.
Ended up refactoring a bit in this PR to make the logic a bit clearer. The tests have also been split up.
Initial implementation idea:
~~Implementation wise, I made a list of allowed numpy parent types (`[np.integer, np.floating, np.bool, np.str_]`). We then loop over all the sortings being aggregated and check that their properties all have the same parent types. If not, we delete this property from the aggregated sorting.~~
> Update sorting property dtype check on unit aggregation to allow for different string types

- pyproject.toml
- src/spikeinterface/preprocessing/motion.py
When we added the `Motion.load` to the `load_motion_info`, we forgot to handle back-compatibility.
This PR just tries to load a legacy motion in case the `Motion.load` fails.
> Update `load_motion_info` to load legacy motion folders

- src/spikeinterface/core/base.py
- src/spikeinterface/preprocessing/whiten.py
As discussed in https://github.com/SpikeInterface/spikeinterface/pull/3685#discussion_r1954036875 and in maintainer meetings, it would be handy to have a `_precomputable_kwargs` in the `BaseExtractor`, especially for Preprocessors.
These are kwargs which can be precomputed for use in a preprocessor. For instance, if you know the whitening matrices, you can pass these directly instead of computing them. If you know the bad channel ids, you can pass these to `RemoveBadChannels` (once it exists #3685) and if you know your motion object, you could pass this to a `CorrectMotion` class (once this exists too!).
This can also be used when saving preprocessed recordings. If we save the provenance and the precomputed data, we can load a preprocessed recording much faster. This will be implemented …
> Add `_precomputable_kwarg_names` to `BaseExtractor`

- src/spikeinterface/core/numpyextractors.py
Fixes #3814. 
We can see that a package that relies on si was using our wrongly named function based on the what we told them to do (function requested times but need samples). We fixed the name by making new functions but connected the old function to the wrong new function which means the time <-> sample conversion was backwards. We should keep it connected to the wrong function for at least a version so that the warning can be read by people expecting the behavior and then fixed before we change the behavior in what could be a silent fashion.
https://github.com/flatironinstitute/mountainsort5/blob/a2f4195927b041210bed8c7113eda5f7ffd367e7/mountainsort5/schemes/sorting_scheme2.py#L328
@magland this affects mountainsort. (I'm happy to push a PR for you over there to deal with this. But I …
> Fix error message and pass through function for generating `NumpySorting`

- pyproject.toml
We (Heberto and I ) ran into this issue on Neo yesterday. There is a long-term switch from `-` to `_` in setuptools. This means that some old packages without wheels are breaking. This led to a lot of angry comments on setuptools so they decided to switch back from error to warning with 78.0.2 so we should probably put the floor to that just in case :)
> Update floor of `setuptools` for metadata

- src/spikeinterface/comparison/collision.py
- src/spikeinterface/comparison/correlogram.py
- src/spikeinterface/core/baserecordingsnippets.py
- src/spikeinterface/core/frameslicerecording.py
- src/spikeinterface/core/frameslicesorting.py
- src/spikeinterface/core/npyfoldersnippets.py
- src/spikeinterface/core/snippets_tools.py
- src/spikeinterface/core/template_tools.py
- src/spikeinterface/core/testing.py
- src/spikeinterface/core/unitsaggregationsorting.py
- src/spikeinterface/core/waveform_tools.py
- src/spikeinterface/sorters/external/combinato.py
- src/spikeinterface/sorters/external/herdingspikes.py
- src/spikeinterface/sorters/external/kilosort4.py
- src/spikeinterface/sorters/external/klusta.py
- src/spikeinterface/sorters/external/mountainsort4.py
- src/spikeinterface/sorters/external/mountainsort5.py
- src/spikeinterface/sorters/external/pykilosort.py
- src/spikeinterface/sorters/external/spyking_circus.py
- src/spikeinterface/sorters/external/tridesclous.py
- src/spikeinterface/sorters/external/yass.py
- src/spikeinterface/widgets/traces.py
- src/spikeinterface/widgets/unit_depths.py
- src/spikeinterface/widgets/unit_locations.py
- src/spikeinterface/widgets/unit_probe_map.py
try-except is expensive especially to import something like torch just to check if the user has it. What if we move more toward `importlib.util.find_spec` instead? Also cleaned up a few imports.
in draft for feedback--I could do more. For example we could change the numba check to this instead which I think would be useful. Doing a single test on my Mac showed that trying to import numba took 0.1997 seconds whereas doing the find_spec took 0.00016 seconds. They are marginal gains for sure, but having a really smooth import experience for users keeps them with a good feeling for the package. Thoughts all?
> Cleanup imports and use `importlib.util.find_spec` rather than try-except

- src/spikeinterface/core/sorting_tools.py
- src/spikeinterface/postprocessing/alignsorting.py
- src/spikeinterface/postprocessing/correlograms.py
- src/spikeinterface/postprocessing/isi.py
- src/spikeinterface/postprocessing/localization_tools.py
- src/spikeinterface/postprocessing/spike_locations.py
- src/spikeinterface/postprocessing/template_similarity.py
- src/spikeinterface/qualitymetrics/misc_metrics.py
- src/spikeinterface/sortingcomponents/matching/tdc.py
- src/spikeinterface/sortingcomponents/peak_detection.py
Same idea as #3795, but moving our numba check to find_spec so that we don't waste time importing. The import is moved to run time so that only users using a numba based function pay the cost. 
I was hoping the `torch.nn.functional` check would work so I was just winging that one. I'll fix it soon :)
> Switch `numba` check to `importlib.util.find_spec`

- src/spikeinterface/comparison/basecomparison.py
- src/spikeinterface/comparison/multicomparisons.py
- src/spikeinterface/comparison/paircomparisons.py
- src/spikeinterface/comparison/tests/test_multisortingcomparison.py
@paul-aparicio I realized that the `n_jobs` parameter was actually not used.
This PR adds it back and updates the parallelization using the `ProcessPoolExecutor`. This will run each comparison in parallel.
A simple test shows that the results are >10x faster (on my machine - 8 CPUs).
Can you test this PR? you just need to add the `n_jobs=-1` to the `compare_multiple_sorters`
> Re-enable n_jobs in multi-comparison

- src/spikeinterface/benchmark/benchmark_base.py
- src/spikeinterface/benchmark/benchmark_motion_estimation.py
- src/spikeinterface/benchmark/benchmark_peak_localization.py
- src/spikeinterface/benchmark/benchmark_plot_tools.py
- src/spikeinterface/benchmark/benchmark_sorter.py
- src/spikeinterface/benchmark/benchmark_tools.py
- src/spikeinterface/benchmark/tests/test_benchmark_sorter.py
- src/spikeinterface/core/zarrextractors.py
Replacement for https://github.com/SpikeInterface/spikeinterface/pull/3301
This adds the option to aggregate levels when plotting benchmark results.
> Add levels to plot benchmarks

- src/spikeinterface/sortingcomponents/clustering/clustering_tools.py
Fixes #3812
Basically in the case that either `nb_templates` is 0 or the number of `ignore_inds` is the same as the `nb_templates` we skip the for loop that generates the `sub_recording` variable. so when we try to `del` it later it causes an error. 
I'm not completely sure what you are hoping for this function @yger and @samuelgarcia so feel free to make a better solution :)
> Prevent error of trying to delete non-existent variable in sorting components

- src/spikeinterface/core/channelsaggregationrecording.py
- src/spikeinterface/core/tests/test_loading.py
Fixes #3825.
In #3767, we decided to deprecate `recording_list` in favor or `recording_list_or_dict`, now that `aggregate_channels` can accept dicts. I did the deprecation at the "user level" by putting it in `aggregate_channels` and only allowing `ChannelAggregationRecording` to accept `recording_list_or_dict`. This creates a bug since the saving functions use the args from `aggregate_channels` but the load-from-provenance functions use the args from `ChannelAggregationRecording`. So e.g. sorting fails in #3825.
This PR fixes the bug by unifying the arguments in the function and class.
Minimal version of #3825 bug:
``` python
rec, _ = si.generate_ground_truth_recording(num_channels=2)
rec.set_property("group", [0,1])
list_of_recs = …
```
> BUG FIX: ensure matching of args in aggregate_channels and ChannelAggregationRecording

- src/spikeinterface/extractors/iblextractors.py
This is a mini patch to the IBL recording to make sure stream_type is stored in _kwargs, so that the assert which happens in the case where only `pid` is supplied is not triggered when unpickling.
> Pickle fix for the IBL recording

- src/spikeinterface/core/analyzer_extension_core.py
easy one :)
We have recently added parallelization to get_noise_levels, but the extension didn't use the job_kwargs
> Propagate job_kwargs to noise_levels

- pyproject.toml
We have huggingface_hub twice in the pyproject.toml. This just removes the duplicate. (see line 173/175)
> cleanup pyproject--remove duplicate from testing section

- src/spikeinterface/core/base.py
- src/spikeinterface/core/baserecording.py
- src/spikeinterface/core/baserecordingsnippets.py
- src/spikeinterface/core/basesorting.py
- src/spikeinterface/core/tests/test_basesorting.py
- src/spikeinterface/core/zarrextractors.py
- src/spikeinterface/extractors/tridesclousextractors.py
- src/spikeinterface/postprocessing/tests/test_principal_component.py
Some fixes:
* Remove `get_total_num_spikes`
* add some missing typing
* List to list in typing
* removed unused imports and attributes.
* Added some missing docstrings.
> Cleanup base sorting extractor 

- src/spikeinterface/extractors/tests/test_whitematterrecordingextractor.py
- src/spikeinterface/extractors/whitematterrecordingextractor.py
Follow up on #3849
I forgot to specify self._kwargs, which gave me trouble when trying to set the probe from probeinterface.
Now, self._kwargs is set properly and I added a test to make sure it doesn't get missed again.
> White matter Recording Extractor Follow Up

- src/spikeinterface/extractors/neoextractors/neobaseextractor.py
When we were discussing the scaling properties, @alejoe91 preferred the property names to be singular. I just realized that channel_names is plural, not channel_name, which would be more consistent with that approach
> channel names  to singular as property

- examples/get_started/quickstart.py
This small PR fixes the MEArec reference in Quickstart. Relevant page: https://spikeinterface.readthedocs.io/en/stable/get_started/quickstart.html
It also fixes a few typos along the way.
> Update MEArec reference in Quickstart

- src/spikeinterface/widgets/motion.py
- src/spikeinterface/widgets/traces.py
We were not handling correctly the case when time_vector is None, but t_starts are present
> Fix plot traces when t_start is defined

- src/spikeinterface/curation/curation_tools.py
- src/spikeinterface/qualitymetrics/misc_metrics.py
Hello,
If you don't have numba installed and try to compute `sd_ratio`, like so:
``` python
rec, sort = si.generate_ground_truth_recording()
sa = si.create_sorting_analyzer(recording=rec, sorting=sort)
sa.compute(["noise_levels", "random_spikes", "templates", "spike_amplitudes"])
si.compute_quality_metrics(sa, metric_names=["sd_ratio"])
```
you get a tricky error message:
```
File "/Users/christopherhalcrow/Work/fromgit/spikeinterface/src/spikeinterface/qualitymetrics/misc_metrics.py", line 1472, in compute_sd_ratio
from spikeinterface.curation.curation_tools import _find_duplicated_spikes_keep_first_iterative
ImportError: cannot import name '_find_duplicated_spikes_keep_first_iterative' from 'spikeinterface.curation.curation_tools' …
```
> Add numba check to `sd_ratio`

- .github/scripts/test_kilosort4_ci.py
- src/spikeinterface/sorters/basesorter.py
- src/spikeinterface/sorters/external/kilosort4.py
- skip `"templates_from_data"` from testing (since it results in failures: https://github.com/MouseLand/Kilosort/issues/932)
- support KS API changes from 4.0.34
> Fix ks4 tests and support ks4>=4.0.34

- src/spikeinterface/widgets/unit_waveforms.py
Allows the UnitWaveformsWidget to use probeinterface `plot_probe` for channel locations, and implements axes_equal arg which was not previously implemented. This would depend on ProbeInterface [PR 334](https://github.com/SpikeInterface/probeinterface/pull/334) to allow the plot_probe function not to plot directly to an set of axes.
Would this be safe enough (do we expect the sorting_analyzer_or_templates object to always have a probe attached, or should I include a fallback to the original implementation too?
> allow UnitWaveformsWidget to use probeinterface plot_probe

- src/spikeinterface/benchmark/benchmark_base.py
- src/spikeinterface/benchmark/benchmark_plot_tools.py
With many cases and large recordings, loading everything in RAM can cause out of mem issues.
We don't really need loading extensions at this point
> Skip loading extensions when instantiating benchmarks

- src/spikeinterface/extractors/neoextractors/spikeglx.py
- src/spikeinterface/extractors/neuropixels_utils.py
Fixes #3894
@billkarsh Do you mind taking a look? I believe that the main error and confusion point was in the use of `num_channels_per_adc` and its description
> Clarify docstrings in neuropixels_utils

- src/spikeinterface/sortingcomponents/clustering/merge.py
- src/spikeinterface/sortingcomponents/clustering/tools.py
This small PR resolves the NumPy deprecation warnings of `np.in1d` which you can find in the CI Logs:
```python
DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
```
It also fixes a few typos along the way.
> Resolve warnings of NumPy library

- src/spikeinterface/preprocessing/motion.py
- src/spikeinterface/preprocessing/tests/test_motion.py
Fixes #3927
When we recently updated the `correct_motion` object, we didn't move the casting of the recording. This fixes the bug, restoring behaviour to that of the previous version.
Added a test to apply a motion correction to a `int`-typed recording.
> Bug fix: cast corrected motion recording to float

- doc/how_to/combine_recordings.rst
- src/spikeinterface/core/baserecording.py
> Fix recording slicing docstrings and documentation typo

- src/spikeinterface/core/baserecording.py
- src/spikeinterface/core/tests/test_time_handling.py
Currently, trying to use `recording.shift_times` when the the segment `t_start` is None produces an error:
This PR fixes this so this situation is interpreted as t_start being 0 as we do in many other places of the code base. Here is a concrete example but other methods do the same implicitly:
https://github.com/h-mayorquin/spikeinterface/blob/252c8f85fbac2af67ff663330a009219994f6717/src/spikeinterface/core/baserecording.py#L929-L934
> Fix shift times when `t_start` is None

- src/spikeinterface/core/baserecording.py
- src/spikeinterface/core/generate.py
- src/spikeinterface/core/tests/test_baserecording.py
This is so the user knows that they are out of the time range of the recording. This would have saved me time when solving this:
https://github.com/catalystneuro/neuroconv/issues/1355
And I think is useful overall.
> Add informative assertions to `slice_time`

- src/spikeinterface/extractors/phykilosortextractors.py
few corrections/suggestions
https://github.com/SpikeInterface/spikeinterface/issues/3920
> phykilosortextractors.py Phy/Kilosort

- .github/scripts/test_kilosort4_ci.py
- src/spikeinterface/sorters/external/kilosort4.py
Introduced by #3852, if the channel groups are not strings they cannot be cast to float. This makes a map to integers
> Fix kcoords for non-int groups

- src/spikeinterface/extractors/neoextractors/spikeglx.py
> Read spikeglx neuropixels data without ap meta

- src/spikeinterface/core/frameslicerecording.py
This comes from here:
https://github.com/catalystneuro/neuroconv/issues/1355
where a users has a slicing error and I don't have enough info to debug it.
> More informative errors in frame slicing

- src/spikeinterface/core/loading.py
- src/spikeinterface/core/zarrextractors.py
The compression ratio can take a very long time to load for long recordings, since the size of each zarr chunk is checked. Since this is not something normally useful, this PR adds a `load_compression_ratio` argument and sets it to False by default
> Optional loading of compression ratio in zarr recording

- src/spikeinterface/core/sortinganalyzer.py
MacOS sometimes saves shadow files in the AppleDouble format to help manage the filesystem. E.g. in one of my `analyzer/extensions/spike_locations` folders, this is the contens:
``` bash
❯ ls -la
total 257859
drwx------@ 1 christopherhalcrow  staff      16384 24 Jun 12:59 .
-rwx------  1 christopherhalcrow  staff       4096 27 Jan 11:18 ._info.json
drwx------  1 christopherhalcrow  staff      16384 22 Apr 18:32 ..
-rwx------@ 1 christopherhalcrow  staff        144 27 Jan 11:18 info.json
-rwx------  1 christopherhalcrow  staff        231 24 Jun 12:59 params.json
-rwx------  1 christopherhalcrow  staff         66 24 Jun 12:59 run_info.json
-rwx------  1 christopherhalcrow  staff  131828480 24 Jun 12:59 spike_locations.npy
```
The `._info.json` file is the AppleDouble format: they always …
> Ignore AppleDouble format files on analyzer extension load

- src/spikeinterface/extractors/tests/test_neoextractors.py
Suggested in Neo to use a useful stream id rather than a number. Updated to fix in our testing.
> Fix NeuroNexus stream_id

- pyproject.toml
When using `uv` to install packages which depend on spikeinterface[full] (e.g. spikeinterface-gui), it somehow tries to install numba v0.53.1 (I can't figure out why...). This fails to install if you're using python>3.9.
This PR puts a lower bound on numba (0.59), which matches our python support (since numba 0.59  dropped support for python 3.8). This forces `uv` to resolve a numba version which will work with all python versions we support. Idea to try this came from https://github.com/astral-sh/uv/issues/14484#issuecomment-3044877590 "We recommend always adding lower bounds to dependencies, to avoid such problems."
In conclusion: this makes `uv run sigui` work out of the box.
> Add lower bound version to numba

- doc/api.rst
- doc/how_to/handle_drift.rst
- examples/how_to/handle_drift.py
- src/spikeinterface/preprocessing/motion.py
Fixes #3083.
The second half of missing api functions. Now added to the api.rst.
Also a tiny fix. The semantic (that Chris and I discussed) for saying backward compatible would be to save that it is for versions greater than what we are being compatible to. So I think we want to actually list this compatibility as > 100 rather than < 101. Otherwise I think we would rewrite that whole statement.
> Add motion functions to api docs

- src/spikeinterface/core/sortinganalyzer.py
Currently the code doesn't actually care if you are doing a soft or hard merge, it verifies the sparsity overlap for all units whether soft or hard and then errors even on hard merge if there is not an overlap. Confirmed by a labmate who ran
```python
merged_analyzer = analyzer.merge_units(
new_merges,
merging_mode='hard'
sparsity_overlap = 0.75
)
```
and got an error
To be honest I don't understand the merging mechanism well enough to know just setting sparsity to None for a hard merge is desired so I'm submitting this as a reminder that we should probably fix this before the next version. Sorry I don't really know how to make a MRE for this.
so help writing a test would be great.
> Fix soft vs hard merge issue in analyzer

- src/spikeinterface/extractors/extractor_classes.py
We weren't granting access to the convenience function `read_neuroscope` which was causing errors in the documentation that we were skipping over. It is one of the edge cases that we missed in my recent PR. Mainly I'm testing this via the docs which should lose the error (good thing they only take 2 minutes now :) )
> Add `read_neuroscope` to `__all__` for extractors

- src/spikeinterface/core/tests/test_unitsaggregationsorting.py
- src/spikeinterface/core/unitsaggregationsorting.py
Different versions of Kilosort output different sampling rate (sometimes rounding it to 2 decimal places, sometimes not)
This makes a crash when trying to aggregate both sortings together This PR fixes this
> Fix sampling rate issue when aggregating

- doc/api.rst
- src/spikeinterface/preprocessing/interpolate_bad_channels.py
A few missing entries in the API and fix docstrings for `detect_and_interpolate_bad_channels`
> Add missing functions in API

- src/spikeinterface/core/tests/test_sorting_tools.py
This small PR fixes a mistaken self-comparison in the `test_sorting_tools.py` test case, correctly asserting spike vector sizes.
> Fix size comparison in sorting tools test case

- pyproject.toml
- src/spikeinterface/sorters/utils/misc.py
Closes #4110
This PR also pins the minimum `cuda-python` version to `11.8.6`
> [!NOTE]
> The new module layouts were applied in [11.8.4](https://nvidia.github.io/cuda-python/cuda-bindings/latest/release/11.8.4-notes.html#cuda-namespace-cleanup-with-a-new-module-layout), but I was getting: 
> > Could not find a version that satisfies the requirement cuda-python==11.8.4; platform_system != "Darwin" and extra == "full" (from spikeinterface[full]) (from versions: 11.8.6, 11.8.7, 12.8.0, 12.9.0, 12.9.1, 12.9.2, 13.0.0, 13.0.1)
> Update deprecated cuda import

- src/spikeinterface/core/sortinganalyzer.py
- src/spikeinterface/core/tests/test_sortinganalyzer.py
As mentioned in #4103, it can be very annoying if your sorting has excess spikes, because the issue only rears its head when you compute spike locations/amplitudes.
This PR would make `create_analyzer_sorting` check for excess spikes and automatically remove them if they are there. If this happens, it will warn the user.
Also added a test.
> Make `create_analyzer_sorting` check for excess spikes
