- requirements.txt
- requests installed by spikesorters
- spikemetrics installed by spiketoolkit
> removed requests and spikemetrics from requirements

- doc/api.rst
- doc/authors.rst
- doc/conf.py
- doc/index.rst
- doc/installation.rst
- doc/releases/0.9.0.rst
- doc/sorters_comparison.rst
- doc/sortersinfo.rst
- doc/supported.rst
- doc/whatisnew.rst
- examples/getting_started/plot_getting_started.py
- examples/modules/comparison/plot_2_compare_multiple_sorters.py
- examples/modules/comparison/plot_4_ground_truth_study.py
- examples/modules/comparison/plot_5_comparison_sorter_weaknesses.py
- examples/modules/extractors/plot_1_recording_extractor.py
- examples/modules/extractors/plot_2_sorting_extractor.py
- examples/modules/extractors/plot_3_handle_probe_info.py
- examples/modules/sorters/plot_1_sorters_example.py
- requirements.txt
- added right version to conf.py
> Release notes

- doc/recording_extractor.rst
- doc/sorting_extractor.rst
Improved documentation for adding new Recording/Sorting extractors to spikextractors.
> Improved instructions for writing extensions to spikextractors.

- examples/modules/extractors/plot_2_sorting_extractor.py
Fixes firing rate calculation and printing of single unit property/spike feature
> Fix bug in plot_2_sorting_extractor.py

- .travis.yml
- README.md
- doc/index.rst
- doc/sorting_extractor.rst
- doc/spike_sorter.rst
- doc/supported.rst
- examples/getting_started/plot_getting_started.py
- examples/modules/comparison/generate_erroneous_sorting.py
- examples/modules/comparison/plot_1_compare_two_sorters.py
- examples/modules/comparison/plot_2_compare_multiple_sorters.py
- examples/modules/comparison/plot_3_compare_sorter_with_ground_truth.py
- examples/modules/comparison/plot_5_comparison_sorter_weaknesses.py
- examples/modules/sorters/plot_1_sorters_example.py
- examples/modules/sorters/plot_3_sorting_by_group.py
- requirements.txt
- requirements_rtd.txt
Still need to release spikesorters and spikecomparison (depends on spikesorters)
Waiting for this to be fixed:
https://github.com/SpikeInterface/spikesorters/pull/171
> Prepare release

- doc/recording_extractor.rst
- doc/releases/0.12.0.rst
- doc/sorting_extractor.rst
- examples/modules/extractors/plot_4_working_with_unscaled_traces.py
- requirements.txt
> Prepare for release 0.12.0

- spikeinterface/toolkit/preprocessing/common_reference.py
- spikeinterface/toolkit/preprocessing/tests/test_common_reference.py
I also fixed your test which is not very discriminant as if you put "mean" it is still passing where it should fail.
> add assert in case of no reference channels in the selected mask

- spikeinterface/toolkit/preprocessing/common_reference.py
Propagation of: https://github.com/SpikeInterface/spiketoolkit/pull/482
> Fix cmr grouping

- .github/workflows/full-test.yml
- requirements_extractors.txt
- requirements_full.txt
- requirements_test.txt
- setup.py
- spikeinterface/__init__.py
- spikeinterface/full.py
@alejoe91 
Add the spikeinertafce.full concept for importing flat
Add differnts layer of extras_require.
> spikeinertafce.full + extras_require

- spikeinterface/extractors/combinatoextractors.py
- spikeinterface/sorters/combinato/combinato.py
Hi Guys, working code for combinato
But only return units not labelled as artifacts or outliers/not sorted... do you think that we should define a common property with defined categories? or maybe multiple binary ones
> working combinato sorter

- spikeinterface/core/numpyextractors.py
- spikeinterface/core/tests/test_waveform_extractor.py
- spikeinterface/core/tests/testing_tools.py
- spikeinterface/core/waveform_extractor.py
- spikeinterface/extractors/toy_example.py
- spikeinterface/toolkit/postprocessing/__init__.py
- spikeinterface/toolkit/postprocessing/correlograms.py
- spikeinterface/toolkit/postprocessing/tests/test_correlograms.py
Deep bug on spiek time not ordred.
> Deep bug on spiek time not ordred and waveform extarctor

- doc/index.rst
- doc/installation.rst
- doc/overview.rst
- examples/getting_started/plot_getting_started.py
- examples/modules/core/plot_1_recording_extractor.py
- examples/modules/core/plot_2_sorting_extractor.py
- examples/modules/core/plot_3_handle_probe_info.py
- examples/modules/core/plot_4_waveform_extractor.py
- examples/modules/core/plot_5_append_concatenate_segments.py
- spikeinterface/toolkit/qualitymetrics/misc_metrics.py
> Doc update

- spikeinterface/sorters/yass/yass.py
https://github.com/SpikeInterface/spikeinterface/issues/164
@ZiadAli can you try this fix? I don't have YASS installed, so it would be great if you can test it out.
> YASS fixes

- spikeinterface/sorters/yass/yass.py
https://github.com/SpikeInterface/spikeinterface/issues/164
> Generate_phy default 0 in yass

- spikeinterface/extractors/combinatoextractors.py
- spikeinterface/sorters/combinato/combinato.py
Hi, these are the same changes that @alejoe91 proposed for waveclus. 
Note that keep_good_only  just removes unsorted units, I think it follows the idea of combinato, the artefact flag is only to help the user to decide.
> adds chunk_memory and keep_good_only to combinato

- examples/modules/comparison/plot_1_compare_two_sorters.py
- examples/modules/comparison/plot_2_compare_multiple_sorters.py
- examples/modules/comparison/plot_3_compare_sorter_with_ground_truth.py
- examples/modules/extractors/plot_1_read_various_formats.py
- examples/modules/extractors/plot_2_working_with_unscaled_traces.py
- examples/modules/toolkit/plot_1_preprocessing.py
- examples/modules/toolkit/plot_2_postprocessing.py
- examples/modules/toolkit/plot_3_quality_mertics.py
- examples/modules/toolkit/plot_4_curation.py
- examples/modules/widgets/plot_3_waveforms_gallery.py
- examples/modules/widgets/plot_4_peaks_gallery.py
- spikeinterface/core/default_folders.py
- spikeinterface/toolkit/postprocessing/principal_component.py
- fix creation of default folders (only when requested)
- various updates to documentation
> Fixed default_folders and update docs

- spikeinterface/sorters/kilosortbase.py
- spikeinterface/widgets/multicompgraph.py
- Removed 2 from kilosortbase class
- Update multicompgraph for new networkx version
> Fix kilosort run on windows and multicompwidget

- examples/modules/widgets/plot_2_sort_gallery.py
- spikeinterface/widgets/correlograms.py
* update example for auto and cross correlogram.
> Some fixes

- spikeinterface/widgets/amplitudes.py
- spikeinterface/widgets/basewidget.py
- spikeinterface/widgets/correlograms.py
- spikeinterface/widgets/depthamplitude.py
- spikeinterface/widgets/isidistribution.py
- spikeinterface/widgets/multicompgraph.py
- spikeinterface/widgets/principalcomponent.py
- spikeinterface/widgets/tests/test_widgets.py
- spikeinterface/widgets/unitprobemap.py
- spikeinterface/widgets/unitwaveformdensitymap.py
- spikeinterface/widgets/unitwaveforms.py
simplify the basewwidget.py :
* keep only one classe that handle one or multiple subplots.
* some clean to come
> Start refactor basewidget : remove BaseMultiWidget

- spikeinterface/sorters/mountainsort4/mountainsort4.py
> Commented out mountainsort4 curation as not implemented in new ms4

- spikeinterface/exporters/report.py
- spikeinterface/widgets/unitsummary.py
> Fix docstrings for unit summary and enable amplitude=None

- spikeinterface/exporters/to_phy.py
> Add choice for template mode in export_to_phy

- spikeinterface/core/tests/test_waveform_extractor.py
- spikeinterface/core/waveform_extractor.py
getting waveform template metrics for each segment of recording/sorting
> adding segment option for get templates

- spikeinterface/core/base.py
- spikeinterface/sorters/runsorter.py
@alejoe91 : tell me what you think
* run_docker binds absolut path
* run command by command with tty=True mode
> Improve docker run

- spikeinterface/core/waveform_extractor.py
- spikeinterface/toolkit/postprocessing/principal_component.py
> Try a fix for spikes on border for waveform extarctor

- spikeinterface/extractors/nwbextractors.py
> Fix loading of locations in NWB

- spikeinterface/extractors/phykilosortextractors.py
- spikeinterface/sorters/runsorter.py
* read_sorter_folder()
* small bug fix
> Read sorter folder

- spikeinterface/core/baserecording.py
- spikeinterface/extractors/nwbextractors.py
@khl02007 Can you test if this fixes the timestamp issue?
@samuelgarcia also the nwbfile is only opened in the segment `__init__`
> Fixes to NWBExtractors

- spikeinterface/extractors/tests/test_neoextractors.py
Disable spikeglx for the moment to avoid test failing.
@alejoe91 : can you merge as soon you se it.
> Disable spikeglx for the moment.

- examples/modules/widgets/plot_3_waveforms_gallery.py
- spikeinterface/sortingcomponents/peak_detection.py
- spikeinterface/sortingcomponents/peak_localization.py
- spikeinterface/sortingcomponents/tests/test_peak_detection.py
- spikeinterface/sortingcomponents/tests/test_peak_localization.py
- spikeinterface/toolkit/postprocessing/__init__.py
- spikeinterface/toolkit/postprocessing/template_localization.py
- spikeinterface/toolkit/postprocessing/template_tools.py
- spikeinterface/toolkit/postprocessing/tests/test_template_localization.py
- spikeinterface/toolkit/postprocessing/tests/test_template_tools.py
- spikeinterface/toolkit/postprocessing/tests/test_unit_localization.py
- spikeinterface/toolkit/postprocessing/unit_localization.py
- spikeinterface/widgets/tests/test_widgets.py
- spikeinterface/widgets/unitlocalization.py
This is an initial draft for peak localisation.
This will be used in drift motion correction.
>  peak localisation and unit localization

- spikeinterface/extractors/neoextractors/spikeglx.py
- spikeinterface/extractors/tests/test_neoextractors.py
This depend on :
* https://github.com/NeuralEnsemble/python-neo/pull/1045
* https://github.com/SpikeInterface/probeinterface/pull/74
> Set probe for spikeglx with neo 0.11 (actual master)

- spikeinterface/core/__init__.py
- spikeinterface/core/old_api_utils.py
> Import old api conversion functions in core init

- spikeinterface/sortingcomponents/peak_detection.py
@alejoe91 : this should be include in the release
> Fix noise level scale in detect_peaks

- spikeinterface/sortingcomponents/peak_detection.py
- spikeinterface/sortingcomponents/peak_localization.py
- spikeinterface/sortingcomponents/template_matching.py
- spikeinterface/sortingcomponents/tests/test_peak_detection.py
- spikeinterface/sortingcomponents/tests/test_peak_localization.py
- spikeinterface/sortingcomponents/tests/test_template_matching.py
This is a sweep through of the sorting_components sub-module, doing some doc updates / clean ups, and minor code linting.
> [MNT] - Doc updates & lints for sorting components

- doc/releases/0.92.0.rst
- doc/whatisnew.rst
- spikeinterface/version.py
@alejoe91 : this branch is in the main repo. If you want to change stuff you can push directly here.
> Prepare release 0.92.0

- spikeinterface/toolkit/preprocessing/whiten.py
Hi,
Adds a `by_property` parameter to the whiten function in preprocessing (mentioned on #363 ).
> Whiten by_property

- spikeinterface/sorters/waveclus/p_waveclus.m
- spikeinterface/sorters/waveclus/set_parameters_ss.m
Hi guys I found a bug in the waveclus sorter, related to the sampling frequency of the output for some cases.
> fixes waveclus output sampling rate

- spikeinterface/extractors/phykilosortextractors.py
Fixes: https://github.com/SpikeInterface/spikeinterface/issues/404
> Fix KS keep_good_only query

- spikeinterface/core/baserecording.py
- spikeinterface/core/old_api_utils.py
Implements https://github.com/SpikeInterface/spikeinterface/issues/426
> Propagate properties in Recording and Sorting OldToNew wrappers

- spikeinterface/core/segmentutils.py
Hi all
This:
- Adds `sampling_frequency_max_diff` kwarg to AppendSegmentSorting and
AppendSegmentRecording (and therefore to concatenate/append_sorting/recording)
- raise a warning if srates differ by less than the limit
I thought this could be of interest to some since sampling freqs slightly differ across runs with SpikeGLX (neuropixels) data.
I did not update the documentation nor tests, nor the concatenate_events method that may or may not presently exist
Best, Tom
> Allow concatenation of datasets with diff srate

- .github/workflows/full-test.yml
- spikeinterface/toolkit/qualitymetrics/quality_metric_calculator.py
- spikeinterface/toolkit/qualitymetrics/quality_metric_list.py
force numpy 1.20 before neo in actions to avoid hdbscan wring linkage
> Try to fix hdbscan make failing tests

- requirements_test.txt
- spikeinterface/core/waveform_extractor.py
- spikeinterface/exporters/report.py
- spikeinterface/exporters/tests/test_export_to_phy.py
- spikeinterface/exporters/to_phy.py
- spikeinterface/toolkit/postprocessing/__init__.py
- spikeinterface/toolkit/postprocessing/principal_component.py
- spikeinterface/toolkit/postprocessing/spike_amplitudes.py
- spikeinterface/toolkit/postprocessing/template_tools.py
- spikeinterface/toolkit/postprocessing/tests/test_principal_component.py
- spikeinterface/toolkit/postprocessing/tests/test_spike_amplitudes.py
- spikeinterface/toolkit/qualitymetrics/__init__.py
- spikeinterface/toolkit/qualitymetrics/misc_metrics.py
- spikeinterface/toolkit/qualitymetrics/quality_metric_calculator.py
- spikeinterface/toolkit/qualitymetrics/tests/test_quality_metric_calculator.py
- spikeinterface/widgets/amplitudes.py
- spikeinterface/widgets/tests/test_widgets.py
- spikeinterface/widgets/unitsummary.py
Start WaveformExtractorExtension concept.
Implement it:
Propagate in:
Also:
> Start WaveformExtractorExtension concept.

- .github/workflows/full-test.yml
- requirements.txt
- requirements_test.txt
- spikeinterface/sorters/tridesclous/tridesclous.py
- spikeinterface/toolkit/postprocessing/tests/test_principal_component.py
- spikeinterface/toolkit/postprocessing/tests/test_spike_amplitudes.py
- spikeinterface/toolkit/qualitymetrics/tests/test_quality_metric_calculator.py
> try to debug hdbscan and numba stuff that make TDC buggy.

- spikeinterface/toolkit/postprocessing/spike_amplitudes.py
- spikeinterface/toolkit/postprocessing/tests/test_spike_amplitudes.py
* enable back compute_spike_amplitudes with n_jobs >= 2
* try fix #435 with differents shift approach
* avoid loop and use numpy vector
> enable back compute_spike_amplitudes with n_jobs >= 2

- spikeinterface/core/old_api_utils.py
Recursively search for correct gains and offsets in old API RecordingExtractor
> Correctly set gains and offsets in old to new recording

- spikeinterface/extractors/nwbextractors.py
Fix https://github.com/SpikeInterface/spikeinterface/issues/457
Not sure if we should rely on Python to handle file closing or to propagate the file opening to the recording segment.
> Remove __del__ from nwbextractor

- .gitignore
- spikeinterface/sorters/runsorter.py
Using guard clause in run_sorter function
Some not used imports clean up
Fix wrong spacing/blank lines
> Clean up in run_sorter.py

- spikeinterface/core/job_tools.py
- spikeinterface/sortingcomponents/peak_detection.py
- spikeinterface/sortingcomponents/template_matching.py
- spikeinterface/sortingcomponents/tests/test_template_matching.py
* Add threadpoolctl for circus peeler.
* fix abuse of tqdm
@yger : have a look!!
> Improve template matching

- spikeinterface/core/job_tools.py
- spikeinterface/sortingcomponents/peak_detection.py
- spikeinterface/sortingcomponents/template_matching.py
- spikeinterface/sortingcomponents/tests/test_template_matching.py
Built upon Sam's branch. Correction of a bug in the amplitudes of SC, and some internals function to implement a denoising/smoothing of the templates. Still playing
> [DO NOT MERGE] Template matching 

- spikeinterface/core/base.py
- spikeinterface/core/tests/test_waveform_extractor.py
- spikeinterface/core/waveform_extractor.py
Fixes https://github.com/SpikeInterface/spikeinterface/issues/473
> Improve portability of WaveformExtractor

- environment_rtd.yml
- examples/modules/toolkit/plot_1_preprocessing.py
- examples/modules/toolkit/plot_3_quality_mertics.py
- examples/modules/toolkit/plot_4_curation.py
- spikeinterface/core/base.py
- spikeinterface/core/waveform_extractor.py
- spikeinterface/toolkit/postprocessing/__init__.py
- spikeinterface/toolkit/postprocessing/principal_component.py
- spikeinterface/toolkit/postprocessing/tests/test_unit_localization.py
- spikeinterface/toolkit/postprocessing/unit_localization.py
- spikeinterface/toolkit/qualitymetrics/misc_metrics.py
- spikeinterface/widgets/unitlocalization.py
Fix docs +
- improve docstrings for `save` function
- `localize_unit` --> `localize_units` (better naming as it calculates location for all units!)
> Attempt to fix broken docs

- spikeinterface/core/segmentutils.py
- spikeinterface/extractors/nwbextractors.py
@alejoe91 @khl02007 
This PR revert #488 and make a better fix for the problem.
@khl02007 : could you test this ?
> Rervert #488

- spikeinterface/core/tests/test_time_handling.py
> Fix time handling tests

- environment_rtd.yml
- examples/getting_started/plot_getting_started.py
- examples/modules/sorters/plot_2_using_the_launcher.py
- spikeinterface/core/base.py
- spikeinterface/sorters/basesorter.py
@alejoe91 : this fix examples
I made a change in base we need to discuss.
What to load when json contain "recording not dumpable".
I put None but maybe we should raise an error or an option to control erroor ve None.
have a look
> Fix examples

- spikeinterface/toolkit/postprocessing/template_metrics.py
- spikeinterface/toolkit/postprocessing/tests/test_template_metrics.py
- Added `upsamplong_factor` (default 10)
- Added `sparsity_dict` option to compute metrics on more channels per unit
> Refactor template metrics

- spikeinterface/core/core_tools.py
- spikeinterface/sortingcomponents/__init__.py
- spikeinterface/sortingcomponents/motion_correction.py
- spikeinterface/sortingcomponents/motion_estimation.py
- spikeinterface/widgets/__init__.py
- spikeinterface/widgets/basewidget.py
- spikeinterface/widgets/drift.py
ported from https://github.com/SpikeInterface/spikeinterface/pull/472
> Drift correction

- spikeinterface/core/segmentutils.py
> Fix typo in SplitSegmentSorting init

- spikeinterface/toolkit/qualitymetrics/misc_metrics.py
- spikeinterface/toolkit/qualitymetrics/pca_metrics.py
- spikeinterface/toolkit/qualitymetrics/quality_metric_calculator.py
- spikeinterface/toolkit/qualitymetrics/quality_metric_list.py
I've been exploring and working with the quality metrics, and in doing so worked through some maintenance updates on the code. Most updates here are cleaning up the code documentation, with some small code lints. No actual code or functionality should have changed. 
Related note: in `misc_metrics.py`, all the functions allow for passing `kwargs`, except that in almost all of them these are not used. I wasn't sure if this is like this to allow for passing through extra arguments somewhere upstream or something - if not, should these `kwargs` inputs be removed in functions they are not used?
> [MNT] - Documentation updates for `quality_metrics`

- spikeinterface/core/basesorting.py
- spikeinterface/core/core_tools.py
- spikeinterface/core/tests/test_basesorting.py
- spikeinterface/core/tests/test_waveform_tools.py
- spikeinterface/core/waveform_extractor.py
- spikeinterface/core/waveform_tools.py
> Start refactor waveformextractor with waveform_tools.

- environment_rtd.yml
- examples/modules/comparison/plot_2_compare_multiple_sorters.py
- readthedocs.yml
As suggested [here](https://github.com/readthedocs/readthedocs.org/issues/8890), try to fix `--update-strategy eager` problem of RTD by installing SI in the conda env directly
> Try install SI from conda env and skip pip

- examples/modules/widgets/plot_2_sort_gallery.py
- spikeinterface/widgets/__init__.py
- spikeinterface/widgets/presence.py
Hi guys, What do you think about this widget?. We use a similar plot to find overclustering due drifting and I thought that could be useful. For long recordings or with units with noisy detections this way to plot activity makes more sense that the raster
> add presence plot

- spikeinterface/extractors/tests/test_neoextractors.py
@samuelgarcia This should be now fixed in Neo, right?
> [test] reintroduce spikeglx test files

- spikeinterface/toolkit/qualitymetrics/misc_metrics.py
Fixes https://github.com/SpikeInterface/spikeinterface/issues/518
> Fix typo in isi violation

- spikeinterface/core/tests/test_waveform_tools.py
- spikeinterface/core/waveform_extractor.py
- spikeinterface/core/waveform_tools.py
@alejoe91 : We have a problem of "too many open file" with the new design of waveforme xtractor.
This should fix it but I don't know yet if this is still fast.
> Fix bug "too many open file" for the new waveforme extractor.

- spikeinterface/extractors/phykilosortextractors.py
Fixes https://github.com/SpikeInterface/spikeinterface/issues/522
> Fix mismatch between phy and si unit ids

- setup.py
Fixes https://github.com/SpikeInterface/spikeinterface/issues/532
> MIT license in setup.py

- spikeinterface/extractors/tests/test_neoextractors.py
Now testing for:
- 'neuralynx/Cheetah_v1.1.0/original_data',
- 'neuralynx/Cheetah_v4.0.2/original_data',
- 'neuralynx/Cheetah_v5.4.0/original_data',
- 'neuralynx/Cheetah_v5.5.1/original_data',
- 'neuralynx/Cheetah_v5.6.3/original_data',
- 'neuralynx/Cheetah_v5.7.4/original_data',
> Add more neualynx versions for testing

- .github/workflows/full-test.yml
- spikeinterface/extractors/neoextractors/spikeglx.py
- spikeinterface/sorters/tridesclous/tridesclous.py
> Remove loose version in favor of packaging

- spikeinterface/core/channelslicerecording.py
@h-mayorquin: there is no a check.
> Check channel_ids are unique.

- spikeinterface/comparison/multicomparisons.py
Fixes https://github.com/SpikeInterface/spikeinterface/issues/547
> Fix multisortingcomparison spiketrains

- spikeinterface/core/numpyextractors.py
- spikeinterface/extractors/neoextractors/openephys.py
Depends on https://github.com/SpikeInterface/probeinterface/pull/94
> Try to read openephys probe

- spikeinterface/extractors/waveclustextractors.py
> it fixes a bug on waveclus sorting extractor

- requirements_full.txt
- spikeinterface/widgets/tests/test_widgets_utils.py
- spikeinterface/widgets/utils.py
@alejoe91 : this is a proposal to add an optional dependency : `distinctipy`
If present this will be used for generating colors for units.
I also added it in [full].
Tell me what you think, it is super light.
> Add optional distinctipy

- spikeinterface/extractors/cbin_ibl.py
- spikeinterface/extractors/extractorlist.py
- spikeinterface/extractors/tests/test_cbin_ibl.py
> read IBL compress files.

- doc/module_sorting_components.rst
- installation_tips/full_spikeinterface_environment_dandi.yml
- installation_tips/full_spikeinterface_environment_windows.yml
- spikeinterface/sortingcomponents/__init__.py
- spikeinterface/sortingcomponents/tests/test_clustering.py
- spikeinterface/sortingcomponents/tests/test_motion_estimation.py
- spikeinterface/sortingcomponents/tests/test_peak_detection.py
- spikeinterface/sortingcomponents/tests/test_peak_localization.py
- spikeinterface/sortingcomponents/tests/test_peak_selection.py
- spikeinterface/sortingcomponents/tests/test_template_matching.py
- spikeinterface/widgets/activity.py
- spikeinterface/widgets/drift.py
- spikeinterface/widgets/tests/test_widgets.py
- spikeinterface/widgets/utils.py
* Doc sorting component
* remove import from sortingcomponents
> Doc sorting component + various stuff

- .github/workflows/full-test.yml
- requirements_test.txt
Try to fix current issues in tests
> Upgrade datalad version

- spikeinterface/extractors/extractorlist.py
- spikeinterface/extractors/mcsh5extractors.py
https://github.com/SpikeInterface/spikeinterface/issues/590
@jonasort could you test this? I don't have a test file so I might have missed something in the refactor. Actually it would be great if you could share a small test file with us :)
> Added MCSH5RecordingExtractor

- spikeinterface/widgets/isidistribution.py
Fixes https://github.com/SpikeInterface/spikeinterface/issues/607
> Fix ISI distribution widget docs

- spikeinterface/toolkit/preprocessing/common_reference.py
> add operator to json

- spikeinterface/sorters/runsorter.py
When we run sorter in container mode, it installs spikeinterface on the fly from remote repository (last commit from main)
This PR allows to set a environment variable called `SPIKEINTERFACE_DEV_PATH` in order to install spikeinterface from local machine in the container
This helps in development phase, since the code changes in the sorter that it's being developed might not be commited, pushed and merged
> Allowing to install local dev spikeinterface in container

- spikeinterface/sortingcomponents/clustering/sliding_nn.py
> Conditional definition of numba function ins sliningNN clustering

- doc/conf.py
- spikeinterface/extractors/neoextractors/axona.py
- spikeinterface/extractors/neoextractors/blackrock.py
- spikeinterface/extractors/neoextractors/ced.py
- spikeinterface/extractors/neoextractors/intan.py
- spikeinterface/extractors/neoextractors/maxwell.py
- spikeinterface/extractors/neoextractors/mscraw.py
- spikeinterface/extractors/neoextractors/neuralynx.py
- spikeinterface/extractors/neoextractors/neuroscope.py
- spikeinterface/extractors/neoextractors/openephys.py
- spikeinterface/extractors/neoextractors/plexon.py
- spikeinterface/extractors/neoextractors/spike2.py
- spikeinterface/extractors/neoextractors/spikeglx.py
- spikeinterface/extractors/neoextractors/tdt.py
use intersphinx to provide links to the relevant neo classes
> add intersphinx for neo readers

- .github/workflows/codecov.yml
- .github/workflows/full-test.yml
- requirements_test.txt
need to set things up for this to work
> add codecov

- spikeinterface/sortingcomponents/peak_waveform_features.py
- spikeinterface/toolkit/postprocessing/__init__.py
- spikeinterface/toolkit/postprocessing/template_tools.py
- Implemented a new `SortingComponent` to extract amplitudes and ptps using `ChunkExecutor`.
- Implemented a new `template_tools` function to create a peaks array from a `WaveformExtractor`
> Waveform features and peaks from templates

- spikeinterface/sortingcomponents/clustering/method_list.py
- spikeinterface/sortingcomponents/clustering/position_ptp_scaled.py
New clustering method with locations and scaled logptps
> scaled clustering with ptp

- spikeinterface/sorters/runsorter.py
add default locations for docker containers
this requires that the containers are uploaded with a "latest" tag
> add default docker containers

- spikeinterface/sortingcomponents/clustering/triage.py
- spikeinterface/sortingcomponents/tests/test_triage.py
- spikeinterface/toolkit/postprocessing/template_tools.py
fix spike amplitude extraction bug
> Template tool

- doc/module_toolkit.rst
Somehow the list and docs for quality metrics had been removed.
> Restore QM in docs

- .github/workflows/full-test.yml
- spikeinterface/extractors/neoextractors/mearec.py
- spikeinterface/extractors/neoextractors/neobaseextractor.py
This revert and fix the mess done by PR #627
> Fix the master because PR627

- doc/install_sorters.rst
Based on this PR https://github.com/SpikeInterface/spikeinterface/pull/624
@yonibrowning I couldn't push on your branch..just cleaned it up a little :)
> Pyks installation instructions

- spikeinterface/comparison/basecomparison.py
- spikeinterface/comparison/multicomparisons.py
- spikeinterface/comparison/paircomparisons.py
and `self.comparisons` is now a dict (easier to navigate) for multicomparisons
e.g. `mcmp.comparisons[("KS2", "KS3")]`
> Cleanup comparison - define functions

- spikeinterface/core/basesorting.py
- spikeinterface/core/tests/test_basesorting.py
@alejoe91 : could you consider this before #735 ?
> Improve `to_spike_vector` by adding channel_ind

- spikeinterface/toolkit/qualitymetrics/tests/test_pca_metrics.py
- spikeinterface/toolkit/utils.py
Use the [scipy definition](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.median_abs_deviation.html#scipy.stats.median_abs_deviation) for the median absolute deviation rather than hard coding it.
> Use scipy for mad

- spikeinterface/core/job_tools.py
- spikeinterface/core/waveform_extractor.py
- spikeinterface/toolkit/postprocessing/correlograms.py
- spikeinterface/toolkit/postprocessing/principal_component.py
- spikeinterface/toolkit/postprocessing/spike_amplitudes.py
- spikeinterface/toolkit/postprocessing/tests/test_principal_component.py
- spikeinterface/toolkit/qualitymetrics/__init__.py
- spikeinterface/toolkit/qualitymetrics/pca_metrics.py
- spikeinterface/toolkit/qualitymetrics/quality_metric_calculator.py
- spikeinterface/toolkit/qualitymetrics/tests/test_quality_metric_calculator.py
- spikeinterface/toolkit/utils.py
- parallelize PCA computation (for `by_channel_local`)
- parallelize PCA metrics computation
- add verbosity options
> Postprocessing updates

- spikeinterface/sorters/waveclus/waveclus_master.m
Hi guys, reading the new wrapper I found a bug in the clustering parameters, and use the opportunity to  improve the case when waveclus doesn't  create a results file and to clean a bit the code
> clean wc master and fix clustering params

- .github/workflows/issue-on-change-matlab.yml
This is a result issue example:
https://github.com/chyumin/spikeinterface/issues/5
> Create issue on change matlab file

- spikeinterface/core/job_tools.py
The simplest PR ever. But to me it will mean a lot
> nicer verbose

- spikeinterface/comparison/groundtruthstudy.py
Computing metrics for study does not work because folder is not created automatically
> Patch for metrics

- spikeinterface/core/base.py
- spikeinterface/core/baserecording.py
- spikeinterface/core/job_tools.py
@samuelgarcia something like this?
> Better handling of preferred mp context

- spikeinterface/sortingcomponents/benchmark/benchmark_clustering.py
- spikeinterface/sortingcomponents/benchmark/benchmark_matching.py
- spikeinterface/sortingcomponents/benchmark/benchmark_peak_selection.py
Misunderstanding of what the filtering flag is. After discussing with Sam, we decided to remove these lines, and I'll ignore the flag for now
> Revert filtering

- spikeinterface/sortingcomponents/benchmark/benchmark_matching.py
- spikeinterface/widgets/legacy_mpl_widgets/__init__.py
- spikeinterface/widgets/legacy_mpl_widgets/gtcomparison.py
- spikeinterface/widgets/legacy_mpl_widgets/gtstudy.py
New widget that we used to have only for study. Maybe could be useful to view all performances on  a single comparison, either with a swarmplot, or averages. Used by benchmark_matching
> Summary widget

- spikeinterface/core/basesorting.py
- spikeinterface/curation/remove_redundant.py
- Added the `max_spikes` strategy which is the pn;ly compatible with passing a `BaseSorting` object
- added `get_total_num_spikes()` in `BaseSorting`
> Allow removal of duplicates from sorting output

- spikeinterface/widgets/sortingview/amplitudes.py
- spikeinterface/widgets/sortingview/autocorrelograms.py
- spikeinterface/widgets/sortingview/base_sortingview.py
- spikeinterface/widgets/sortingview/crosscorrelograms.py
- spikeinterface/widgets/sortingview/sorting_summary.py
- spikeinterface/widgets/sortingview/timeseries.py
- spikeinterface/widgets/sortingview/unit_locations.py
- spikeinterface/widgets/sortingview/unit_waveforms.py
Set `self.view` to be able to access the sortingview `view` from the plotter (similar to mpl figure/axes)
> Set sortingview views at Plotter level

- spikeinterface/widgets/matplotlib/unit_waveforms.py
- spikeinterface/widgets/unit_waveforms.py
- fix yscale (there was a bug)
- add `max_spikes_per_unit` option
- propagate `lw` to waveforms
> Improve unit waveforms mpl

- spikeinterface/postprocessing/template_tools.py
- spikeinterface/qualitymetrics/misc_metrics.py
Added mode extremum or at_index for amplitude and SNR computation.
> Added option for SNR computation

- spikeinterface/sortingcomponents/clustering/position_ptp_scaled.py
- spikeinterface/sortingcomponents/features_from_peaks.py
- spikeinterface/sortingcomponents/motion_estimation.py
- spikeinterface/sortingcomponents/peak_detection.py
- spikeinterface/sortingcomponents/peak_localization.py
- spikeinterface/sortingcomponents/peak_pipeline.py
- spikeinterface/sortingcomponents/tests/test_clustering.py
- spikeinterface/sortingcomponents/tests/test_features_from_peaks.py
- spikeinterface/sortingcomponents/tests/test_motion_estimation.py
- spikeinterface/sortingcomponents/tests/test_peak_detection.py
- spikeinterface/sortingcomponents/tests/test_peak_localization.py
- spikeinterface/sortingcomponents/tests/test_peak_pipeline.py
Add peak pipeline concept.
This enable to compute any 'step' pipeline on peaks at the same time: 
* localization
* ptp
* energy
* ...
This include a refactor of:
* localize_peak()
* compute_features_from_peaks()
* estimate_motion()
@yger :
* please clone this branch and make deep test.
* read carrfully the new compute_features_from_peaks() I rewrote everything, check you have correct results
@alejoe91 :
* tell me what you think
* do NOT make commit on typos or grammar now I will clean this later
@colehurwitz @cwindolf @julienboussard:
* this new concept should make easy to extract any features on the fly (at detect_peak level) for your pipeline
> [important] Peak pipeline

- spikeinterface/sorters/mountainsort4/mountainsort4.py
This fixes typos in the new temporary directory code for mountainsort4
> fixed tempdir typo

- spikeinterface/extractors/extractorlist.py
- spikeinterface/extractors/neoextractors/__init__.py
- spikeinterface/extractors/neoextractors/neobaseextractor.py
- spikeinterface/extractors/neoextractors/neuralynx.py
- spikeinterface/extractors/tests/test_neoextractors.py
First attempt at adding a sorting extractor based on neo. I tried to follow the format of the other tests. Test on the CI seems to be passing.
Related to this issue:
https://github.com/catalystneuro/neuroconv/issues/16
> Add `NeuralynxSortingExtractor` 

- spikeinterface/extractors/extractorlist.py
- spikeinterface/extractors/neoextractors/__init__.py
- spikeinterface/extractors/neoextractors/blackrock.py
- spikeinterface/extractors/tests/test_neoextractors.py
> Add `BlackrockSortingExtractor`

- spikeinterface/core/baserecording.py
- spikeinterface/core/baserecordingsnippets.py
- spikeinterface/core/basesnippets.py
- spikeinterface/core/segmentutils.py
This should close #858 
I also eliminated a duplication of `has_scales` one duplication in the same page in baserecordingsnipets and one duplication (as it is already inherited) on basesnipets.
I added the cleanup of segutils here as well
> Recover has scaled traces

- doc/api.rst
- spikeinterface/extractors/neoextractors/edf.py
- spikeinterface/extractors/neoextractors/neobaseextractor.py
- spikeinterface/extractors/neoextractors/nix.py
> add low-level classes to API docs

- spikeinterface/core/basesorting.py
- spikeinterface/extractors/neoextractors/neobaseextractor.py
- spikeinterface/extractors/neoextractors/neuralynx.py
As discussed with Alessio today this returns the right times when t start is available.
> Shift `get_spike_times`  with `_t_start` when available

- spikeinterface/sorters/runsorter.py
yass image from spikeinterface-dockerfiles needs to be built & pushed before merging
> Added yass to docker map

- spikeinterface/extractors/extractorlist.py
- spikeinterface/extractors/mclustextractors.py
- spikeinterface/sorters/mclust/__init__.py
Hi, We are working on MClust support. For now we have this extractor to read the output. 
I do this pull request first just to start the discussion and help issues like #63 
Cheers,
Fer
> MClust support

- spikeinterface/extractors/cbin_ibl.py
> Fix IBL cbin kwargs

- spikeinterface/sorters/runsorter.py
This PR depends on build & pushing herding spikes image from spikeinterface-dockerfiles
> Add herdingspikes docker

- spikeinterface/core/baserecordingsnippets.py
- spikeinterface/preprocessing/tests/test_whiten.py
- spikeinterface/preprocessing/whiten.py
> Enable specification of dtype of whitening

- spikeinterface/extractors/phykilosortextractors.py
Fixes https://github.com/SpikeInterface/spikeinterface/issues/814
This fixes a bug in `read_phy`: when excluding `noisy`, the spike clusters and times were not filtered accordingly, so the spike trains had many additional "0" spikes (because of `np.zeros`).
Now the new spike clusters and times are pre-computed based on remaining unit ids.
> Fix Phy reading of unit 0 in case of unit exclusion

- spikeinterface/sorters/sorterlist.py
Fixes https://github.com/SpikeInterface/spikeinterface/issues/882
> Fix typo in deprecation warning

- spikeinterface/sorters/runsorter.py
Simplifying singularity local build
Using `docker-daemon` instead of manually creating .tar file and using `docker-archive`
Also some extra spaces cleaning
> improve singularity local build

- spikeinterface/core/job_tools.py
- spikeinterface/core/tests/test_waveform_extractor.py
- spikeinterface/qualitymetrics/pca_metrics.py
- spikeinterface/widgets/__init__.py
- spikeinterface/widgets/amplitudes.py
- spikeinterface/widgets/autocorrelograms.py
- spikeinterface/widgets/crosscorrelograms.py
- spikeinterface/widgets/quality_metrics.py
- spikeinterface/widgets/sorting_summary.py
- spikeinterface/widgets/spike_locations.py
- spikeinterface/widgets/spikes_on_traces.py
- spikeinterface/widgets/template_metrics.py
- spikeinterface/widgets/template_similarity.py
- spikeinterface/widgets/timeseries.py
- spikeinterface/widgets/unit_locations.py
- spikeinterface/widgets/unit_templates.py
- spikeinterface/widgets/unit_waveforms.py
- spikeinterface/widgets/unit_waveforms_density_map.py
- spikeinterface/widgets/widget_list.py
centralize define_widget_function_from_class() in widgets modules toget better document with backend kwargs included
> centralize define_widget_function_from_class() in widgets modules toget better document with backend kwargs included

- spikeinterface/widgets/amplitudes.py
- spikeinterface/widgets/matplotlib/amplitudes.py
- spikeinterface/widgets/matplotlib/base_mpl.py
- spikeinterface/widgets/matplotlib/crosscorrelograms.py
- spikeinterface/widgets/matplotlib/metrics.py
- spikeinterface/widgets/matplotlib/unit_waveforms.py
- spikeinterface/widgets/matplotlib/unit_waveforms_density_map.py
- spikeinterface/widgets/tests/test_widgets.py
In case `ncols` or `nrows` is 1, then `self.axes` is 1D. Here we add the correct dimension so we can assume `self.axes` is always 2D
@samuelgarcia
> Enforce self.axes is 2D

- doc/releases/0.95.1.rst
- doc/whatisnew.rst
- spikeinterface/version.py
> Prepare minor release 0.95.1

- installation_tips/check_your_install.py
- installation_tips/full_spikeinterface_environment_linux_dandi.yml
- installation_tips/full_spikeinterface_environment_mac.yml
- installation_tips/full_spikeinterface_environment_windows.yml
> joblib=1.1

- spikeinterface/core/recording_tools.py
Fixes https://github.com/SpikeInterface/spikeinterface/issues/957
> Check chunk_size VS number of samples in random chunks

- spikeinterface/postprocessing/spike_amplitudes.py
- spikeinterface/preprocessing/common_reference.py
> Fix border effect for compute_spike_amplitudes

- spikeinterface/postprocessing/principal_component.py
> PCA: protect against projection on unfitted models

- spikeinterface/core/waveform_extractor.py
- spikeinterface/postprocessing/correlograms.py
- spikeinterface/postprocessing/isi.py
- spikeinterface/postprocessing/principal_component.py
- spikeinterface/postprocessing/spike_amplitudes.py
- spikeinterface/postprocessing/spike_locations.py
- spikeinterface/postprocessing/template_metrics.py
- spikeinterface/postprocessing/template_similarity.py
- spikeinterface/postprocessing/tests/common_extension_tests.py
- spikeinterface/postprocessing/tests/test_correlograms.py
- spikeinterface/postprocessing/tests/test_isi.py
- spikeinterface/postprocessing/tests/test_principal_component.py
- spikeinterface/postprocessing/tests/test_spike_amplitudes.py
- spikeinterface/postprocessing/tests/test_spike_locations.py
- spikeinterface/postprocessing/tests/test_template_metrics.py
- spikeinterface/postprocessing/tests/test_template_similarity.py
- spikeinterface/postprocessing/tests/test_unit_localization.py
- spikeinterface/postprocessing/unit_localization.py
- spikeinterface/qualitymetrics/quality_metric_calculator.py
- spikeinterface/qualitymetrics/tests/test_quality_metric_calculator.py
- refactor `BaseWaveformExtension`
> Implement in-memory extensions

- .github/workflows/full-test.yml
- spikeinterface/extractors/tests/common_tests.py
- spikeinterface/extractors/tests/test_neoextractors.py
> Fix extractors cache

- spikeinterface/postprocessing/spike_amplitudes.py
- spikeinterface/widgets/sortingview/base_sortingview.py
- spikeinterface/widgets/template_similarity.py
Fixes tests failin in several PRs:
- #989 
- #995 
- #971
> Fix spike amplitudes and widgets tests

- spikeinterface/core/baseevent.py
- spikeinterface/core/numpyextractors.py
- spikeinterface/core/tests/test_numpy_extractors.py
- spikeinterface/extractors/neoextractors/maxwell.py
- spikeinterface/extractors/neoextractors/neobaseextractor.py
- spikeinterface/extractors/neoextractors/openephys.py
- spikeinterface/extractors/tests/common_tests.py
- spikeinterface/extractors/tests/test_neoextractors.py
+ extend open ephys events to handle block_index and test with different datasets
> Improve NEO event handling

- spikeinterface/core/baseevent.py
I left a `@property` by mistake
> Fix event get_dtype()

- spikeinterface/core/base.py
- spikeinterface/core/tests/test_unitsaggregationsorting.py
- spikeinterface/core/unitsaggregationsorting.py
> UnitsAggregationSorting inheritance

- spikeinterface/widgets/base.py
> Check backend kwargs validity

- spikeinterface/sorters/runsorter.py
Tested mechanism both on docker and singularity locally
> Better handling of SI dev install in containers

- requirements_test.txt
- spikeinterface/sorters/runsorter.py
@samuelgarcia somehow these changes were overwritten by the pykilosort PR (I think due to a git reset file)
> Si dev container

- .github/workflows/full-test.yml
- spikeinterface/core/core_tools.py
We had an overly complex and bad implementation (my bad)
> Simplify check_json

- pyproject.toml
- spikeinterface/core/__init__.py
From @caniko https://github.com/SpikeInterface/spikeinterface/pull/986
> Pyproject suggestions

- .github/workflows/full-test.yml
- pyproject.toml
- spikeinterface/core/base.py
- spikeinterface/curation/__init__.py
- spikeinterface/curation/curationsorting.py
- spikeinterface/curation/sortingview_curation.py
- spikeinterface/curation/tests/test_sortingview_curation.py
- spikeinterface/widgets/sorting_summary.py
- spikeinterface/widgets/sortingview/metrics.py
- spikeinterface/widgets/sortingview/sorting_summary.py
- spikeinterface/widgets/tests/test_widgets.py
- Implement sortingview curation widget (example [curation link](https://figurl.org/f?v=gs://figurl/spikesortingview-10&d=sha1://1ba03f81e62ec7cb2e3e46898830f92cdf5e026f&label=SpikeInterface%20-%20Sorting%20Summary)):
```
sw.plot_sorting_summary(we, curation=True, backend="sortingview")
```
- The curation view allows users to create a link associated to a curation. The `spikeinterface.curation.apply_sortingview_curation(sorting, uri)` function enables one to curate an existing SI object with the manual curation from the link (using the `CurationSorting` class) (example [curated link](https://figurl.org/f?v=gs://figurl/spikesortingview-10&d=sha1://1ba03f81e62ec7cb2e3e46898830f92cdf5e026f&label=SpikeInterface%20-%20Sorting%20Summary&s={%22sortingCuration%22:%22jot://cENcosqWTArO%22}})):
``` …
```
> Sortingview curation widget

- spikeinterface/exporters/to_phy.py
Closes #1040 
and possibly fixes #837 #880
> fix: export to phy when empty units are present

- README.md
This small PR fixes broken links in the README. (I hope to make more significant contributions next 😉)
> Fix broken spikeinterface-gui links

- spikeinterface/preprocessing/__init__.py
- spikeinterface/preprocessing/preprocessing_tools.py
- spikeinterface/preprocessing/tests/test_preprocessing_tools.py
Utils function to compute the spatial interpolation kernel
#988 and #1025 should be refactored using this common function.
@JoeZiminski
> Add get_spatial_interpolation_kernel in preprocessing.

- spikeinterface/extractors/nwbextractors.py
- spikeinterface/extractors/tests/test_nwbextractors.py
This should fix #1004.
I added a test.
> NWBRecordingExtractor offset extraction

- README.md
- doc/containerized_sorters.rst
- doc/index.rst
Following  #1077, improved documentation on how to install and setup docker
> Enhance docker docs

- spikeinterface/core/tests/test_waveform_extractor.py
- spikeinterface/core/waveform_extractor.py
> Fix loading unfiltered waveforms crash

- spikeinterface/extractors/mcsh5extractors.py
I have to work with mcsh5 file, and sometimes the unit is not saved in the file. I don't know why, I did not generate the files myself, but I guess this can be quite common. Therefore, I think we should still be able to ready the files even without the proper unit
> Patch for mcsh5

- spikeinterface/core/testing.py
> Correct channel selection in tests when mono-channel recording

- spikeinterface/widgets/timeseries.py
> Increase sv timeresies tile-size

- spikeinterface/postprocessing/template_metrics.py
- spikeinterface/postprocessing/tests/common_extension_tests.py
> Fix template_metrics select_units() and extend postprocessing tests

- doc/containerized_sorters.rst
Closes #1107 by extending documentation
> [doc] Update container docs with save() function

- spikeinterface/postprocessing/unit_localization.py
- spikeinterface/sortingcomponents/peak_localization.py
- spikeinterface/sortingcomponents/tests/test_peak_localization.py
Snould close #1089 once this is done.
> Add `peak_channel` as a method to `localize_peaks` in SortingComponents

- spikeinterface/core/__init__.py
- spikeinterface/core/base.py
- spikeinterface/core/baserecording.py
- spikeinterface/core/baserecordingsnippets.py
- spikeinterface/core/job_tools.py
- spikeinterface/sorters/basesorter.py
Add split_job_kwargs() function
Must be merged before #1105
> Add split_job_kwargs() function

- spikeinterface/core/job_tools.py
@TomBugnon : this should help you
> Also limits thread in init workers.

- spikeinterface/preprocessing/remove_artifacts.py
- spikeinterface/preprocessing/tests/test_remove_artifacts.py
Since this was something in SpyKING CIRCUS, I would like to have again the possibility, in order to remove artefacts, to subtract either the mean or the median computed over several artefacts. This is what this PR is about. It offers two new possibilities for artefact removal: mean or median, as explained in the docstrings.
> Median and average artefact

- README.md
> [doc] Add proper Twitter and Mastodon badges

- spikeinterface/extractors/neoextractors/biocam.py
- spikeinterface/extractors/neoextractors/blackrock.py
- spikeinterface/extractors/neoextractors/ced.py
- spikeinterface/extractors/neoextractors/mcsraw.py
- spikeinterface/extractors/neoextractors/neobaseextractor.py
- spikeinterface/extractors/neoextractors/neuralynx.py
- spikeinterface/extractors/neoextractors/neuroscope.py
- spikeinterface/extractors/neoextractors/nix.py
- spikeinterface/extractors/neoextractors/plexon.py
- spikeinterface/extractors/neoextractors/spikegadgets.py
- spikeinterface/extractors/neoextractors/spikeglx.py
- spikeinterface/extractors/neoextractors/tdt.py
- spikeinterface/extractors/tests/test_neoextractors.py
fixes #1161 
In addition it fixes a case in `NeoBaseSortingExtractor` when sampling frequency cannot be auto-guessed
> [bug-extractors] Fix neuralynx sorting function and NeoBaseSorting when no streams

- pyproject.toml
- spikeinterface/extractors/cellexplorersortingextractor.py
- spikeinterface/extractors/extractorlist.py
- spikeinterface/extractors/tests/test_neoextractors.py
Implements #1157 
@CodyCBakerPhD
> [feat-extractors] Add CellExplorerSortingExtractor

- spikeinterface/extractors/phykilosortextractors.py
Optimizing Phy-based extractors for faster loading.
There are still 2 steps which take up ~90% of the loading time (I've labeled the steps with comments in the code).
I'm trying to think if I can find good alternatives.
I'm working on this because for a thing I'm doing, I need to load 324 phy folders, which right now takes around 11 minutes.
> [feat-exp] Optimizing Phy-based extractors

- spikeinterface/extractors/phykilosortextractors.py
- spikeinterface/preprocessing/phase_shift.py
- spikeinterface/preprocessing/tests/test_phase_shift.py
and a typo in phy extractor
fixs #1125
> [bug-preprocessing] Fix phase-shift dtype

- spikeinterface/sortingcomponents/motion_estimation.py
- spikeinterface/sortingcomponents/tests/test_motion_estimation.py
> [feat-sc] Refactor motion_estimate

- examples/modules/core/plot_4_waveform_extractor.py
- spikeinterface/core/__init__.py
- spikeinterface/core/sparsity.py
- spikeinterface/core/template_tools.py
- spikeinterface/core/tests/test_template_tools.py
- spikeinterface/core/tests/test_waveform_extractor.py
- spikeinterface/core/waveform_extractor.py
- spikeinterface/exporters/to_phy.py
- spikeinterface/postprocessing/template_metrics.py
Add `estimate_sparsity()` and deprecate `get_template_channel_sparsity()`
> [sparsity] Add estimate_sparsity function

- installation_tips/check_your_install.py
> [bug-installation] Fix check install

- spikeinterface/postprocessing/__init__.py
- spikeinterface/postprocessing/noise_level.py
- spikeinterface/postprocessing/tests/common_extension_tests.py
- spikeinterface/postprocessing/tests/test_noise_levels.py
@TomBugnon @alejoe91 
This is something I wanted to do since several month.
> Noise level as a waveform extractor extention

- conftest.py
- spikeinterface/extractors/nwbextractors.py
- spikeinterface/extractors/tests/test_nwb_s3_extractor.py
I am trying to pin down the errors in #1227
> Testing `test_s3_nwb_fsspec` caching

- .github/workflows/full-test.yml
- spikeinterface/qualitymetrics/quality_metric_list.py
- spikeinterface/widgets/tests/test_widgets.py
The widgets tests are failing on master. I think I know where the bug is coming from. Testing here. 
Also, looking at the setup of the widgets tests, it seems that they depend heavily on post-processing and quality metrics. Changes on those modules should trigger the widgets tests. Adding that here to the CI.
> Fix widget tests of quality metrics 

- spikeinterface/preprocessing/correct_lsb.py
- spikeinterface/preprocessing/preprocessinglist.py
- spikeinterface/preprocessing/tests/test_correct_lsb.py
- spikeinterface/preprocessing/whiten.py
The `correct_lsb` function is needed to pre-process some recordings (e.g. Open Ephys) that do not have unitary LSB.
It is an important preprocessing step for compression.
Also removed some randomization in whitening and improve kwargs.
> Add `correct_lsb` function

- pyproject.toml
- spikeinterface/extractors/iblstreamingrecording.py
Issue https://github.com/int-brain-lab/ibllib/issues/560 appears to have been resolved and so we can update the `IblStreamingRecordingExtractor` correspondingly
> Ibl streaming dtype fix

- spikeinterface/preprocessing/highpass_spatial_filter.py
@samuelgarcia can you merge this?
> Missing parent init in HighPassSpatialFilterSegment

- .github/workflows/caches_cron_job.yml
I got the name of the branch wrong (I used main instead of master).
> Run cache generation on merge (II)

- spikeinterface/preprocessing/tests/test_whiten.py
- spikeinterface/preprocessing/whiten.py
@samuelgarcia I think we forgot to push this fix!
fixes #1336
> Fix whiten: add M to parameters and kwargs

- .gitignore
- spikeinterface/sortingcomponents/peak_selection.py
- spikeinterface/sortingcomponents/tests/test_peak_selection.py
> Add optional selection indices to ``select_peaks`` function

- .github/workflows/core-test.yml
- .github/workflows/s3-nwb-test.yml
Small PR so the core and streaming tests also run in chained PRs. For some reason only the full tests run in chained PRs right now (see #1339). 
This makes all the PRs equal on the eyes of the CI .
> Run core and streaming tests on chained PRs.

- spikeinterface/sortingcomponents/peak_selection.py
- spikeinterface/sortingcomponents/tests/test_peak_selection.py
Updated the select peaks function to use the new -and recommended - features of numpy for random generator and container operations.
> new numpy features for peak selection

- .github/workflows/caches_cron_job.yml
- .github/workflows/core-test.yml
- .github/workflows/full-test-with-codecov.yml
- .github/workflows/full-test.yml
- .github/workflows/s3-nwb-test.yml
- spikeinterface/core/datasets.py
- spikeinterface/core/tests/test_datasets.py
For some reason the test for the function `download_dataset`  is taking too long on the full tests (see this [summary](https://github.com/SpikeInterface/spikeinterface/actions/runs/4211526876)). I think it is not accessing the cached data for mearec. I think sorting this is low-hanging fruit for making the tests faster.
I am testing here if this is the case.
> `download_dataset` function not accessing cached data on CI

- spikeinterface/preprocessing/correct_lsb.py
- spikeinterface/preprocessing/tests/test_correct_lsb.py
Fixed the logic of LSB correction case channels are not centered at 0.
> Fix LSB correction

- doc/index.rst
- doc/install_sorters.rst
- doc/installation.rst
- doc/viewers.rst
I'll try to go folder by folder. If in the future you'd prefer me to just make a pull request when done with a bigger set of files I can, but I prefer making a small set of changes at time, so not too many files need to be reviewed. Happy to adjust though.
> Improve documentation - I

- .github/workflows/test_containers_singularity.yml
- spikeinterface/sorters/external/combinato.py
- spikeinterface/sorters/external/tests/test_singularity_containers.py
- spikeinterface/sorters/runsorter.py
Porting singularity-based tests from https://github.com/SpikeInterface/spikeinterface-dockerfiles
> Add manual sorter tests in singularity

- doc/modules/comparison.rst
- doc/modules/core.rst
- doc/modules/curation.rst
- doc/modules/exporters.rst
- doc/modules/extractors.rst
- doc/modules/postprocessing.rst
- doc/modules/preprocessing.rst
- doc/modules/qualitymetrics.rst
- doc/modules/sorters.rst
- doc/modules/sortingcomponents.rst
- doc/overview.rst
Review of files in the doc/modules folder.
I mainly fixed typos. In a few commits I marked line numbers that need to be reviewed (either missing words or meaning was unclear). If it is easier I can collate that info and put into an issue in the future. Just let me know :). 
I'll work on unifying spikeinterface capitalization as discussed in #1380 after this first pass of edits.
> Improve Documentation - II

- spikeinterface/sorters/runsorter.py
See https://github.com/SpikeInterface/spikeinterface/pull/1373#discussion_r1123116199
> Remove CI options from runsorter

- spikeinterface/core/generate.py
Quick PR to improve and refactor this function a bit. Does not change functionality.
> Added type annotation and docstring to `generate_recording`

- .github/workflows/full-test-with-codecov.yml
The solution that @alejoe91  requested for #1392.
Should close #1392 when completed.
> Remove external sorters test from code coverage tests

- spikeinterface/widgets/matplotlib/spikes_on_traces.py
This PR fixes a bug in spike_on_traces, that can not handle sparse waveforms yet
> Fix for handling sparsity in spikes_on_traces

- spikeinterface/sortingcomponents/benchmark/benchmark_motion_correction.py
- spikeinterface/sortingcomponents/benchmark/benchmark_motion_estimation.py
- spikeinterface/sortingcomponents/motion_estimation.py
> Benchmark motion : small important detail

- spikeinterface/sortingcomponents/tests/test_waveforms/test_savgol_denoiser.py
- spikeinterface/sortingcomponents/waveforms/neural_network_denoiser.py
- spikeinterface/sortingcomponents/waveforms/savgol_denoiser.py
I just made a simple (but efficient) savgol denoiser to smooth waveforms on-the-fly. I also fixed some typos in neuralnet denoiser
https://en.wikipedia.org/wiki/Savitzky%E2%80%93Golay_filter
> Adding a savgol denoiser for the waveforms

- spikeinterface/curation/sortingview_curation.py
- spikeinterface/curation/tests/sv-sorting-curation.json
- spikeinterface/curation/tests/test_sortingview_curation.py
- get rid of legacy `JOT`
- use `GH` handle instead
> Update SV curation mechanism

- spikeinterface/extractors/neoextractors/blackrock.py
- spikeinterface/extractors/neoextractors/neobaseextractor.py
- spikeinterface/extractors/tests/test_neoextractors.py
- spikeinterface/sorters/runsorter.py
- spikeinterface/widgets/_legacy_mpl_widgets/probemap.py
Some various small fix that prement me to make a clear demo on spikeinterface.
* improve blackrock speed (depend on https://github.com/NeuralEnsemble/python-neo/pull/1231) by skiping the nev
* auto select the blacrock stream id (nx2 o, nx6, nx2) using the file suffix
* use neo channel_names optionaly when possible
* improve plot_probe_map when sevral probes
> Some various small fix

- spikeinterface/qualitymetrics/misc_metrics.py
Hi,
Another little PR!
All the metrics support units with N=0 spikes (which could happen eg when slicing a sorting), and in general return np.nan, except the slidingRP_violations which errors.
To avoid the error and for consistency with other metrics I added this `min_spikes` parameter
Best
> Add min_spikes to slidingRP_violations (support unit with no spike)

- .github/workflows/core-test.yml
- pyproject.toml
Post #1391 fixes. 
Adds a new set of extra dependencies in the toml files to test core.
> Add core testing deendencies

- spikeinterface/extractors/neoextractors/openephys.py
> Fix in OpenEphysBinaryRecordingExtractor doc

- spikeinterface/extractors/phykilosortextractors.py
> Fix in PhyKilosortSortingExtractor

- spikeinterface/core/baserecording.py
- spikeinterface/core/core_tools.py
- spikeinterface/core/generate.py
- spikeinterface/core/job_tools.py
- spikeinterface/core/tests/test_generate.py
> Add memory to recording `__repr__`

- spikeinterface/core/core_tools.py
> Allow a None value for paths

- spikeinterface/curation/curationsorting.py
- spikeinterface/curation/mergeunitssorting.py
- spikeinterface/curation/remove_duplicated_spikes.py
- spikeinterface/curation/remove_excess_spikes.py
- spikeinterface/curation/splitunitsorting.py
Moving forward with #1235 with the curation module.
> Remove `to_dict` mechanism in curation module

- doc/modules/core.rst
- spikeinterface/core/__init__.py
- spikeinterface/core/basesorting.py
- spikeinterface/core/segmentutils.py
- spikeinterface/core/testing.py
- spikeinterface/core/tests/test_basesorting.py
- spikeinterface/core/tests/test_segmentutils.py
Hi,
Sorry the tests are not very well written, but it works !
The `ignore_times` kwarg is effectively forced to be True  in all cases in ConcatenateRecordings (I think?), but if behavior changes for the recording concatenation, `ignore_times=False` should work out of the box for the sorting concatenation.
Let me know if you have comments!
Best
> Implement sorting concatenation

- spikeinterface/core/channelsaggregationrecording.py
- spikeinterface/core/channelslice.py
- spikeinterface/core/core_tools.py
- spikeinterface/core/frameslicerecording.py
- spikeinterface/core/frameslicesorting.py
- spikeinterface/core/injecttemplates.py
- spikeinterface/core/segmentutils.py
- spikeinterface/core/waveform_tools.py
First attempt at removing the mechanism from the root. As there a lot of places I will break down this in two steps. Also, easier to review and fix if something goes wrong.
Related to https://github.com/SpikeInterface/spikeinterface/issues/1235
> Remove `to_dict` mechanism from core module I

- .github/workflows/core-test.yml
- .github/workflows/s3-nwb-test.yml
- src/spikeinterface/core/segmentutils.py
Testing using src directory for new branch main.
I am testing here that the CI tests work in the intended way. 
First that the tests run: which should work
Second, that they pass: which shoul fail. I think that the test will clone from master meanwile.
> Testing merging to main instead of master

- doc/modules/core.rst
Noticed this when checking it out just now
> [Docs]: typo in aggregation section

- src/spikeinterface/widgets/matplotlib/timeseries.py
Changes from #1475 from master to main.
> Merge #1475 to main

- doc/api.rst
- doc/index.rst
- doc/install_sorters.rst
- doc/modules/comparison.rst
- doc/modules/core.rst
- doc/modules/curation.rst
- doc/modules/exporters.rst
- doc/modules/extractors.rst
- doc/modules/postprocessing.rst
- doc/modules/preprocessing.rst
- doc/modules/sorters.rst
- doc/modules/sortingcomponents.rst
- doc/modules/widgets.rst
Moving on with #1344. This time for #1477 and #1471
> Add 1477 and 1471 to main

- doc/install_sorters.rst
The changes in #1479 but to main. This is a contribution by @JoeZiminski .
> update `set_kilosort2_path` to `set_kilosort2_5_path` to main

- src/spikeinterface/preprocessing/common_reference.py
- src/spikeinterface/preprocessing/normalize_scale.py
- src/spikeinterface/preprocessing/preprocessinglist.py
- src/spikeinterface/preprocessing/tests/test_normalize_scale.py
- src/spikeinterface/preprocessing/tests/test_whiten.py
- src/spikeinterface/preprocessing/whiten.py
Another one for #1344. This time is about #1437. Note that #1483 needs this before to go.
> Add PR 1437 to main

- src/spikeinterface/curation/curation_tools.py
- src/spikeinterface/curation/curationsorting.py
- src/spikeinterface/curation/mergeunitssorting.py
- src/spikeinterface/curation/remove_duplicated_spikes.py
- src/spikeinterface/curation/remove_excess_spikes.py
- src/spikeinterface/curation/remove_redundant.py
- src/spikeinterface/curation/sortingview_curation.py
- src/spikeinterface/curation/splitunitsorting.py
Hey all, with the change to main->main I wanted to do a small test before I do any bigger sweeps of docstrings, asserts, errors etc for generating the API documentation. Still just fixing minor typos and trying to clarify a few minor points-no code changes.
> Improve Documentation VI (Docstrings + Asserts)

- src/spikeinterface/widgets/utils.py
The scalebar value in the `plot_timeseries` sortingview backend was hard-coded to 10ms...
This PR fixes it and it further improves the estimation and location of the scalebar and text for different timeranges.
The rule of thumb is: the scalebar is 1/5 of the row in ms. If the row is more than 5ms, then the scale bar is a multiple of 5.
Example time ranges in seconds:
- [[0, 0.01]](https://figurl.org/f?v=gs://figurl/spikesortingview-10&d=sha1://50431e6818839296793212fb1d55ae5893d9b141&label=SpikeInterface%20-%20Timeseries&zone=aind)
- [[0, 0.03]](https://figurl.org/f?v=gs://figurl/spikesortingview-10&d=sha1://0d74916b5ad42fe70aabb38290f87664351d1160&label=SpikeInterface%20-%20Timeseries&zone=aind)
- [[0, 0.5]](https://figurl.org/f?v=gs://figurl/spikesortingview-10&d=sha1://e6f4632cb7e1eae7d …
> Fix Sortingview scalebar

- src/spikeinterface/core/base.py
- src/spikeinterface/core/datasets.py
At least it can be filtered :)
> Version mismatch: `print` --> `warning`

- src/spikeinterface/core/segmentutils.py
Testing if this is what is causing the memory error.
> Remove to_dict in segment_utils

- src/spikeinterface/qualitymetrics/pca_metrics.py
Hi,
Before, n_spikes and fr were recomputed for each unit.
Doing it once out of the loop boosts the PCA computation by >80% in a 2h recording with 100um radius waveforms, the gaiin is probably even much greater for longer recordings.
Best
> nn metrics performance: Compute we n_spikes/fr out of main_loop

- src/spikeinterface/postprocessing/unit_localization.py
- src/spikeinterface/sortingcomponents/peak_localization.py
- src/spikeinterface/sortingcomponents/tests/test_peak_localization.py
Similarly to what have been done with CoM, we should let the user decide which feature should be considered for monopolar triangulation. At a first glimpse (see figure below), it looks like using the norm as a feature might be better than ptp. I'll do more tests on that.
> Choices of Feature for the monopolar triangulation

- src/spikeinterface/postprocessing/unit_localization.py
Some function has been duplicated (partially) by mistake during merges
> Cleaning code duplication by mistake

- .github/run_tests.sh
- .github/workflows/full-test-with-codecov.yml
- .github/workflows/full-test.yml
This should come in top of #1532. It is a further refactor of the CI that should avoid duplication of code and make mainteance easier.
> Refactor testing scripts

- doc/installation.rst
This removes completly the advice of using setuptools and adds some relevant links.
> Improve installation instructions

- src/spikeinterface/extractors/nwbextractors.py
I was looking at #1513 and I think the diff will make this PR more annoying to review as the change to black was done there. 
I am separting this so Cody gets an easier time reading the diff. That is, this is just changes in formating and no coding.
> Format NWB extractor in black for Cody's review

- src/spikeinterface/core/basesorting.py
- src/spikeinterface/core/injecttemplates.py
- src/spikeinterface/core/snippets_tools.py
- src/spikeinterface/core/waveform_extractor.py
- src/spikeinterface/core/waveform_tools.py
- src/spikeinterface/postprocessing/spike_locations.py
- src/spikeinterface/qualitymetrics/misc_metrics.py
- src/spikeinterface/sortingcomponents/benchmark/benchmark_clustering.py
- src/spikeinterface/sortingcomponents/benchmark/benchmark_peak_selection.py
- src/spikeinterface/sortingcomponents/clustering/circus.py
- src/spikeinterface/sortingcomponents/clustering/position_and_features.py
- src/spikeinterface/sortingcomponents/clustering/position_and_pca.py
- src/spikeinterface/sortingcomponents/clustering/random_projections.py
- src/spikeinterface/sortingcomponents/clustering/sliding_hdbscan.py
- src/spikeinterface/sortingcomponents/clustering/sliding_nn.py
- src/spikeinterface/sortingcomponents/matching/circus.py
- src/spikeinterface/sortingcomponents/matching/main.py
- src/spikeinterface/sortingcomponents/matching/naive.py
- src/spikeinterface/sortingcomponents/matching/tdc.py
- src/spikeinterface/sortingcomponents/matching/wobble.py
- src/spikeinterface/sortingcomponents/peak_detection.py
- src/spikeinterface/sortingcomponents/peak_pipeline.py
Let's try to move forward with https://github.com/SpikeInterface/spikeinterface/issues/1409 which got sidestep because of the changes to main.
This PR deals with the changes for `segment_ind` to `segment_index` in a minimal way.
> Change `segment_ind` for `segment_index` 

- src/spikeinterface/core/recording_tools.py
- src/spikeinterface/core/tests/test_recording_tools.py
In some cases, it can be useful to compute noise with std instead of mad.
> Allow option to compute noise with std

- src/spikeinterface/sortingcomponents/tests/test_peak_detection.py
This is just #1553 but without the part that @alejoe91 disagrees (testing for recall). That is, it just separates the tests as much as possible right now by method.
> Refactor detect peak tests without testing recall

- src/spikeinterface/core/base.py
- src/spikeinterface/core/testing.py
- src/spikeinterface/core/tests/test_baserecording.py
- src/spikeinterface/core/tests/test_basesorting.py
Add a test to check if annotations/properties of two extractors are equal.
> Check extractor properties

- src/spikeinterface/core/basesorting.py
- src/spikeinterface/core/injecttemplates.py
- src/spikeinterface/core/snippets_tools.py
- src/spikeinterface/core/tests/test_waveform_tools.py
- src/spikeinterface/core/waveform_extractor.py
- src/spikeinterface/core/waveform_tools.py
- src/spikeinterface/postprocessing/spike_locations.py
- src/spikeinterface/preprocessing/tests/test_normalize_scale.py
- src/spikeinterface/qualitymetrics/misc_metrics.py
- src/spikeinterface/sortingcomponents/benchmark/benchmark_clustering.py
- src/spikeinterface/sortingcomponents/benchmark/benchmark_peak_selection.py
- src/spikeinterface/sortingcomponents/clustering/circus.py
- src/spikeinterface/sortingcomponents/clustering/position_and_features.py
- src/spikeinterface/sortingcomponents/clustering/position_and_pca.py
- src/spikeinterface/sortingcomponents/clustering/random_projections.py
- src/spikeinterface/sortingcomponents/clustering/sliding_hdbscan.py
- src/spikeinterface/sortingcomponents/clustering/sliding_nn.py
Moving forward with https://github.com/SpikeInterface/spikeinterface/issues/1409. This time moves `unit_ind` to `unit_index`.
> Change `unit_ind` to `unit_index`

- src/spikeinterface/sorters/internal/spyking_circus2.py
- src/spikeinterface/sorters/internal/tridesclous2.py
- src/spikeinterface/sortingcomponents/benchmark/benchmark_matching.py
- src/spikeinterface/sortingcomponents/clustering/clustering_tools.py
- src/spikeinterface/sortingcomponents/matching/circus.py
- src/spikeinterface/sortingcomponents/matching/naive.py
- src/spikeinterface/sortingcomponents/matching/tdc.py
- src/spikeinterface/sortingcomponents/matching/wobble.py
- src/spikeinterface/sortingcomponents/tests/test_template_matching.py
Final PR for #1409. This should close #1409. Changing `cluster_ind` to `cluster_index`.
> Change `cluster_ind` to `cluster_index`

- src/spikeinterface/widgets/matplotlib/unit_waveforms.py
> Fixes #1578 (widgets.plot_unit_waveforms bug)

- src/spikeinterface/core/numpyextractors.py
I have some warnings in my IDEA because there's some typing missing in the numpy extractors
> Some typing in numpy extractors

- src/spikeinterface/widgets/all_amplitudes_distributions.py
- src/spikeinterface/widgets/amplitudes.py
- src/spikeinterface/widgets/base.py
- src/spikeinterface/widgets/crosscorrelograms.py
- src/spikeinterface/widgets/metrics.py
- src/spikeinterface/widgets/quality_metrics.py
- src/spikeinterface/widgets/sorting_summary.py
- src/spikeinterface/widgets/spike_locations.py
- src/spikeinterface/widgets/spikes_on_traces.py
- src/spikeinterface/widgets/template_metrics.py
- src/spikeinterface/widgets/template_similarity.py
- src/spikeinterface/widgets/timeseries.py
- src/spikeinterface/widgets/unit_depths.py
- src/spikeinterface/widgets/unit_locations.py
- src/spikeinterface/widgets/unit_summary.py
- src/spikeinterface/widgets/unit_waveforms.py
- src/spikeinterface/widgets/unit_waveforms_density_map.py
- src/spikeinterface/widgets/utils.py
I'm starting to work on updating some of the docstrings (#1536). This will take multiple passes, but for now I tried to delete parameters not accessible and add parameters that can be set. The one thing that needs to be added for widgets is  **backend_kwargs. I couldn't find a list (in docs or in functions) so that can either be added in the docstrings for all the functions or maybe it would be better just to link to a page in the RTD that lists the possible kwargs @samuelgarcia? I'm happy to add them to this PR if you'd prefer that or add them to the docs (now or in a different PR) if you have list of them somewhere.
> Update Docstrings I (Widgets Module)

- src/spikeinterface/core/core_tools.py
- src/spikeinterface/core/job_tools.py
- src/spikeinterface/core/waveform_tools.py
- src/spikeinterface/postprocessing/principal_component.py
Removing some code that is not useful and asking some questions.
> Remove unecessary ensure_n_jobs

- src/spikeinterface/core/waveform_extractor.py
> Fixed typo in WaveformExtractor

- src/spikeinterface/core/waveform_extractor.py
- src/spikeinterface/extractors/neoextractors/mearec.py
- src/spikeinterface/extractors/neoextractors/neobaseextractor.py
- src/spikeinterface/extractors/neoextractors/plexon.py
- src/spikeinterface/sortingcomponents/matching/circus.py
- src/spikeinterface/sortingcomponents/tests/test_template_matching.py
- src/spikeinterface/widgets/tests/test_widgets.py
As discussed today, I did look into this. After looking into it, it seems that the problem is in the waveform extractor. If you look at the new assertion that I put at the beginning of the test, all the methods are failing (not just circus**). And the reason seems to be that the waveform_extractor is not returning any waveforms.** 
Why could this be? I think it is related to the changes that I did in mearec but I know less about the waveforme extractors as it is an object that I have never look into detail.
Maybe at this point something rings a bell, @alejoe91?
Otherwise, I will dig deeper.
> Template matching bug

- src/spikeinterface/sortingcomponents/peak_detection.py
- src/spikeinterface/sortingcomponents/tests/test_peak_detection.py
This is the iterative peak detection method. 
I added a basic so let's discuss if anything more is necessary.
> Add iterative peak detection

- src/spikeinterface/core/generate.py
- src/spikeinterface/core/tests/test_generate.py
- src/spikeinterface/preprocessing/tests/test_detect_bad_channels.py
When working on #1602 I realized that the generator recording was not working properly. My testing did not cover arrays large enough. I have added new tests, fix the error and introduce a technique to reduce even more the memory allocations plus some small refactoring.
> Fix generator recording

- .pre-commit-config.yaml
This PR adds the `.pre-commit-config.yaml` file to prepare for the pre-commit bot.
> Add pre-commit-config file

- .github/workflows/pre-commit-post-merge.yml
- doc/development/development.rst
As requested @alejoe91 . This adds the documentation and the post-merge action.
> Add post merge black action and black documentation

- .github/workflows/pre-commit-post-merge.yml
Added the action for pushing and condition for always.
> Fix action for post merge pre-commit round II

- .github/workflows/pre-commit-post-merge.yml
I used the wrong version of python
> Fix action for post merge pre-commit round III

- doc/development/development.rst
- doc/installation.rst
Was looking at docs and noticed a couple places where the rst wasn't formatted. Just fixed.
> Documentation-Fix RST formatting Typos

- src/spikeinterface/core/waveform_extractor.py
Added some typing in `WaveformExtractor` + fixed a typo
> Added some typing in `WaveformExtractor`

- src/spikeinterface/core/tests/test_core_tools.py
Refactoring tests for #1602. We should merge this one before.
> Refactor `write_binary_recording` tests

- environment_rtd.yml
- src/spikeinterface/widgets/_legacy_mpl_widgets/presence.py
> Install python-neo and probeinterface from main in docs

- doc/modules/sortingcomponents.rst
- src/spikeinterface/sortingcomponents/matching/main.py
Fixes #1685 by editing sortingcomponents rst file and find_spikes_from_templates docstring.
> Add wobble to the docs

- src/spikeinterface/sorters/external/kilosort.py
- src/spikeinterface/sorters/external/kilosort2.py
- src/spikeinterface/sorters/external/kilosort2_5.py
- src/spikeinterface/sorters/external/kilosort3.py
- src/spikeinterface/sorters/external/kilosortbase.py
Tested this: works for a local run but not when using container :/
Is this because I need to clear Singularity cache and rebuild?
> Added cleanup of temp files after Kilosort run

- src/spikeinterface/extractors/phykilosortextractors.py
Added an annotation with the path to the original phy folder to the phy extractors.
> Add original folder to phy extractor

- src/spikeinterface/preprocessing/tests/test_zero_padding.py
- src/spikeinterface/preprocessing/zero_channel_pad.py
Adding a preprocessing step that pads traces to the left and to the right.
> Add preprocessing for padding traces

- src/spikeinterface/exporters/to_phy.py
> Take care of BinaryFolderRecording in export_to_phy

- src/spikeinterface/curation/auto_merge.py
Little fix for people in my team who contributed :)
> Update doc `merge_units`

- src/spikeinterface/sorters/external/kilosortbase.py
See https://github.com/SpikeInterface/spikeinterface/commit/6a6c82f2cbce269f3eaaf47a931dd8bd4fc803bc#r120509954
@h-mayorquin @samuelgarcia
> Fix KS padded recording

- .github/workflows/test_containers_singularity_gpu.yml
- src/spikeinterface/sorters/external/tests/test_docker_containers.py
- src/spikeinterface/sorters/external/tests/test_singularity_containers.py
- src/spikeinterface/sorters/external/tests/test_singularity_containers_gpu.py
Moved GPU tests from [`spikeinterface-dockerfiles`](https://github.com/SpikeInterface/spikeinterface-dockerfiles/blob/main/tests/test_containers_gpu.py) here
> Add GPU container tests

- src/spikeinterface/core/segmentutils.py
Hi
This kwarg was actually not passed along for dumping/loading in https://github.com/SpikeInterface/spikeinterface/pull/416
My bad!
> Fix `sampling_frequency_max_diff` kwarg for recording concat

- src/spikeinterface/core/tests/test_generate.py
I realize that some assertions were missing in the lazy generator tests. 
This PR fixes it.
> Fix lazy generator test

- src/spikeinterface/comparison/hybrid.py
- src/spikeinterface/comparison/multicomparisons.py
- src/spikeinterface/core/base.py
- src/spikeinterface/core/baserecording.py
- src/spikeinterface/core/basesnippets.py
- src/spikeinterface/core/numpyextractors.py
- src/spikeinterface/core/old_api_utils.py
- src/spikeinterface/core/tests/test_base.py
- src/spikeinterface/core/tests/test_jsonification.py
- src/spikeinterface/core/waveform_extractor.py
- src/spikeinterface/extractors/klustaextractors.py
- src/spikeinterface/postprocessing/alignsorting.py
- src/spikeinterface/postprocessing/spike_amplitudes.py
- src/spikeinterface/preprocessing/tests/test_filter.py
- src/spikeinterface/sorters/basesorter.py
- src/spikeinterface/sorters/launcher.py
- src/spikeinterface/sortingcomponents/motion_interpolation.py
Add _is_json_serializable
is_dumpable > _is_dumpable
clean some is_dumpable at some places
> Add _is_json_serializable to extractor

- .github/workflows/test_containers_docker.yml
- src/spikeinterface/sorters/external/tests/test_docker_containers.py
Making PR internally so that I can trigger tests from branch!
> Make action more windows-friendly

- src/spikeinterface/core/base.py
- src/spikeinterface/core/binaryfolder.py
- src/spikeinterface/core/binaryrecordingextractor.py
- src/spikeinterface/core/npysnippetsextractor.py
- src/spikeinterface/core/npzfolder.py
- src/spikeinterface/core/npzsortingextractor.py
- src/spikeinterface/extractors/cbin_ibl.py
- src/spikeinterface/extractors/cellexplorersortingextractor.py
- src/spikeinterface/extractors/iblstreamingrecording.py
- src/spikeinterface/extractors/mdaextractors.py
- src/spikeinterface/extractors/neoextractors/biocam.py
- src/spikeinterface/extractors/neoextractors/maxwell.py
- src/spikeinterface/extractors/neoextractors/openephys.py
- src/spikeinterface/extractors/neoextractors/spikeglx.py
- src/spikeinterface/extractors/nwbextractors.py
- src/spikeinterface/extractors/shybridextractors.py
- src/spikeinterface/extractors/waveclussnippetstextractors.py
Long overdue and not used anywhere!
> Remove 'is_writable' and 'has_default_locations'

- src/spikeinterface/qualitymetrics/misc_metrics.py
- src/spikeinterface/qualitymetrics/pca_metrics.py
@DradeAW this should make the change back-compatible! But you SHOULD use keyworkd arguments!!
> Move unit_ids argument at the end of qm low-level functions

- src/spikeinterface/sorters/external/kilosort2.py
- src/spikeinterface/sorters/external/kilosort2_5.py
- src/spikeinterface/sorters/external/kilosort3.py
> Expose AUCpslit param in KS2+

- src/spikeinterface/extractors/neoextractors/openephys.py
> Do not load NP probe in OE if load_sync_channel=True

- src/spikeinterface/extractors/neoextractors/mearec.py
I just remembered about this. Tests were failing on neuroconv because of this.
This eliminates a bug that should disappear with the next release in neo.
> Fix neo release bug in Mearec

- docs_rtd.yml
- pyproject.toml
> Fix hdbascan installation in read the docs

- src/spikeinterface/core/recording_tools.py
- src/spikeinterface/preprocessing/depth_order.py
Otherwise dumping a tuple to json and reloading it results in a list!
> Allow order_channel_by_depth to accept dimentsions as list

- src/spikeinterface/extractors/extractorlist.py
Otherwise we can't get this extractor from `extractorlist.get_recording_extractor_from_name`
> Added `ZarrRecordingExtractor` to recording list

- src/spikeinterface/qualitymetrics/pca_metrics.py
> Fix bug in pca metrics warnings

- src/spikeinterface/core/segmentutils.py
Fixes https://github.com/SpikeInterface/spikeinterface/issues/1881
> Handle edge frames in concatenated rec

- src/spikeinterface/extractors/cbin_ibl.py
Close https://github.com/SpikeInterface/spikeinterface/issues/1926
> Add `stream_name` option to `read_cbin_ibl`

- doc/api.rst
- src/spikeinterface/extractors/neoextractors/__init__.py
- src/spikeinterface/extractors/neoextractors/neuroexplorer.py
- src/spikeinterface/extractors/tests/test_neoextractors.py
This is related to #1773 and #1093. See the discusion there.
> Add RecordingExtractor for NeuroExplorer 

- doc/api.rst
- doc/modules/extractors.rst
Added the doc references for pl2
> Doc Changes for recently added Plexon 2 support

- doc/modules/extractors.rst
As described.
I forgot to do this on:
https://github.com/SpikeInterface/spikeinterface/pull/1965
> Add NeuroExplorer to the extractor rst

- doc/conf.py
- doc/development/development.rst
- doc/how_to/analyse_neuropixels.rst
- doc/how_to/get_started.rst
- doc/how_to/handle_drift.rst
- doc/modules/motion_correction.rst
- doc/modules/qualitymetrics.rst
- doc/modules/qualitymetrics/silhouette_score.rst
- doc/modules/qualitymetrics/synchrony.rst
- doc/modules/sorters.rst
- pyproject.toml
- src/spikeinterface/postprocessing/principal_component.py
- src/spikeinterface/preprocessing/motion.py
- src/spikeinterface/qualitymetrics/pca_metrics.py
- src/spikeinterface/sortingcomponents/peak_detection.py
- src/spikeinterface/widgets/spikes_on_traces.py
- src/spikeinterface/widgets/traces.py
- src/spikeinterface/widgets/widget_list.py
This is a work in progress. I was trying to build locally for to test #1964, but when I build locally it doesn't become nested. I also wanted to add some fixes--but I need to test the with rtd build rather than local for this. 
Also the build has 97 warnings. So this is working on cleaning up those warnings just so they don't potentially cause build failures in the future.
> Sphinx Fixes

- .github/workflows/installation-tips-test.yml
I added an 's' to the folder name. This is the correct folder name for the test. 
As said in #1962, I'm terrible at making Actions.
> fix folder for installation test build

- src/spikeinterface/comparison/basecomparison.py
- src/spikeinterface/comparison/comparisontools.py
- src/spikeinterface/core/baserecording.py
- src/spikeinterface/core/basesnippets.py
- src/spikeinterface/core/basesorting.py
- src/spikeinterface/core/generate.py
- src/spikeinterface/core/tests/test_sparsity.py
- src/spikeinterface/curation/mergeunitssorting.py
- src/spikeinterface/extractors/bids.py
- src/spikeinterface/postprocessing/amplitude_scalings.py
- src/spikeinterface/postprocessing/spike_amplitudes.py
- src/spikeinterface/postprocessing/spike_locations.py
- src/spikeinterface/preprocessing/interpolate_bad_channels.py
- src/spikeinterface/qualitymetrics/misc_metrics.py
- src/spikeinterface/qualitymetrics/pca_metrics.py
- src/spikeinterface/sortingcomponents/benchmark/benchmark_matching.py
- src/spikeinterface/sortingcomponents/benchmark/benchmark_peak_selection.py
- src/spikeinterface/sortingcomponents/clustering/clustering_tools.py
- src/spikeinterface/sortingcomponents/clustering/sliding_hdbscan.py
- src/spikeinterface/widgets/unit_waveforms_density_map.py
> `np.in1d` to `np.isin` as the former will be deprecated 

- src/spikeinterface/core/generate.py
- src/spikeinterface/core/waveform_extractor.py
Fix waveform extactor reload sorting when pickle
> waveform extactor reload

- src/spikeinterface/comparison/groundtruthstudy.py
- src/spikeinterface/widgets/widget_list.py
> small fix in gtstudy

- src/spikeinterface/core/generate.py
* Add noise_level in kwargs NoiseGeneratorRecording
* Change some parameters in generate templates
> Fix  NoiseGeneratorRecording : "noise_level" in kwargs

- src/spikeinterface/comparison/groundtruthstudy.py
Should provide kargs for waveforms extraction
> Forgot extra params

- examples/modules_gallery/qualitymetrics/plot_4_curation.py
- src/spikeinterface/extractors/neoextractors/openephys.py
Fixes #2099 
@JoeZiminski can you test this out?
> Fix grouping of OpenEphys NPIX

- src/spikeinterface/sorters/tests/test_launcher.py
- src/spikeinterface/sortingcomponents/clustering/merge.py
@alejoe91 : this fix the main I think
> Fix slicing in merge.py and so tridesclous2 and so test_launcher.py

- src/spikeinterface/postprocessing/template_metrics.py
@samuelgarcia I think I forgot to push the removal of `debug_plots` from template metrics. Here it is!
> Remove debug plots from template metrics

- src/spikeinterface/sortingcomponents/benchmark/benchmark_clustering.py
- src/spikeinterface/sortingcomponents/clustering/circus.py
- src/spikeinterface/sortingcomponents/clustering/position_and_features.py
- src/spikeinterface/sortingcomponents/features_from_peaks.py
- src/spikeinterface/sortingcomponents/matching/main.py
- src/spikeinterface/sortingcomponents/matching/naive.py
- src/spikeinterface/sortingcomponents/matching/tdc.py
- src/spikeinterface/sortingcomponents/motion_estimation.py
- src/spikeinterface/sortingcomponents/peak_selection.py
- src/spikeinterface/sortingcomponents/waveforms/waveform_thresholder.py
Just editing more assert messaging in sorting components this time.
> Improve assert messaging (sortingcomponents)

- src/spikeinterface/core/tests/test_waveform_extractor.py
- src/spikeinterface/core/waveform_extractor.py
> Add sparsity_temp_folder option to extract_waveforms

- src/spikeinterface/core/generate.py
As discussed in today's meeting.
> small generation.py doc fix

- src/spikeinterface/core/waveform_extractor.py
Small quality of life improvement.
> Add folder to `FileExistsError` when creating waveforms

- .github/workflows/installation-tips-test.yml
Should fix failing test here: https://github.com/SpikeInterface/spikeinterface/actions/runs/6683202501/job/18159188881
> Fix installation-tips test CI

- src/spikeinterface/comparison/comparisontools.py
`uint16` leads to overflow and erroneous count.
> Use `uint64` for match count

- pyproject.toml
> After release

- src/spikeinterface/core/base.py
> Use python methods instead of parsing and eleminate try-except in to_dict

- src/spikeinterface/core/waveform_extractor.py
- src/spikeinterface/exporters/report.py
- src/spikeinterface/exporters/to_phy.py
- src/spikeinterface/postprocessing/principal_component.py
- src/spikeinterface/postprocessing/tests/common_extension_tests.py
- src/spikeinterface/postprocessing/tests/test_principal_component.py
- src/spikeinterface/qualitymetrics/misc_metrics.py
- src/spikeinterface/qualitymetrics/quality_metric_calculator.py
- src/spikeinterface/qualitymetrics/tests/test_quality_metric_calculator.py
- src/spikeinterface/widgets/base.py
- src/spikeinterface/widgets/unit_summary.py
> `WaveformExtractor.is_extension` --> `has_extension`

- src/spikeinterface/extractors/mdaextractors.py
- src/spikeinterface/preprocessing/deepinterpolation/generators.py
Following on https://github.com/SpikeInterface/spikeinterface/pull/2195
> Use context managers on Deep Interpolation

- src/spikeinterface/widgets/utils_sortingview.py
> Fix sortingview checks for NaN if strings

- src/spikeinterface/core/sorting_tools.py
Another one of the changes on how types are imported @CodyCBakerPhD . Ths should fix the dev branch.
> Patch for neuroconv

- src/spikeinterface/sorters/internal/spyking_circus2.py
- src/spikeinterface/sortingcomponents/clustering/random_projections.py
- src/spikeinterface/sortingcomponents/matching/circus.py
Still in the process of intensively comparing SC and SC2, addition of a debug mode to keep internal variables for further debugging
> Adding a debug mode to SC2

- src/spikeinterface/core/channelslice.py
- src/spikeinterface/core/unitsselectionsorting.py
> Assert renamed_channels/unit_ids is unique

- src/spikeinterface/core/waveform_extractor.py
> Disable writing templates modes npy in read-only mode

- src/spikeinterface/extractors/nwbextractors.py
- src/spikeinterface/extractors/tests/test_nwb_s3_extractor.py
> Add option for no caching sorting for `NWBSortingExtractor`

- src/spikeinterface/sorters/runsorter.py
run_sorter in container check json or pickle.
This close #2261.
> run_sorter in container check json or pickle

- src/spikeinterface/extractors/nwbextractors.py
- src/spikeinterface/extractors/tests/test_nwb_s3_extractor.py
As in the title
I am unifying the options between nwb sorting and extractor as I will unify them with the fast access discussed in https://github.com/SpikeInterface/spikeinterface/pull/2169
Small PR in that direction.
> Add nwb sorting rem file support

- src/spikeinterface/core/base.py
- src/spikeinterface/core/binaryfolder.py
- src/spikeinterface/core/core_tools.py
- src/spikeinterface/core/npyfoldersnippets.py
- src/spikeinterface/core/sortingfolder.py
- src/spikeinterface/core/tests/test_core_tools.py
@h-mayorquin @alejoe91 @zm711 
Refactor relative to machisim for to make it better for window.
I will make some tests for path manipulation.
This close #2219 and maybe some issues.
@zm711 : could you make some test and check on your side.
> Improve the BaseExtractor.to_dict() relative_to machanism to make it safer on windows.

- src/spikeinterface/sortingcomponents/motion_estimation.py
> Fix histogram time smoothing samekind error

- src/spikeinterface/extractors/nwbextractors.py
This is a small refactor which is a pre-amble to implement fast mode reading from Dandi.
> Refactor NWB extractor to separate reading hdf5 file from reading nwb

- src/spikeinterface/sorters/basesorter.py
- src/spikeinterface/sorters/utils/shellscript.py
> Close ShellScript process at deletion

- src/spikeinterface/core/numpyextractors.py
- src/spikeinterface/sortingcomponents/waveforms/temporal_pca.py
> NumpySorting.from_peaks make unit_ids mandatory.

- src/spikeinterface/core/base.py
From the discussion of #2280.
I am not sure I would like to add a check @alejoe91 . If someone passes and int or a string we could coerce that to a list with one element but I dislike that as well.
> improve `ids_to_indices` docstring

- src/spikeinterface/extractors/cbin_ibl.py
> Add `.stream.cbin` compatibility to `CompressedBinaryIblExtractor`

- src/spikeinterface/sorters/utils/shellscript.py
> Close stdout and stderr in ShellScript upon deletion

- src/spikeinterface/core/zarrrecordingextractor.py
- src/spikeinterface/preprocessing/common_reference.py
Plus some default values in common ref docstrings
> Add zarrrecordingextractor.py for backward compatibility

- src/spikeinterface/preprocessing/silence_periods.py
> Fix for Silence periods (saving noise levels)

- src/spikeinterface/preprocessing/filter_gaussian.py
Add the option to change the margins for the gaussian filter.
> Add `margin_sd` to gaussian filtering

- src/spikeinterface/comparison/basecomparison.py
Was doing a comparison and noticed a couple small typos :) .
> Typo fix for verbose setting in Multicomparison

- src/spikeinterface/core/tests/test_zarrextractors.py
- src/spikeinterface/core/zarrextractors.py
Add option for ZarrSortingExtractor to read in sub group.
> Improve ZarrSortingExtractor

- src/spikeinterface/core/generate.py
Should fix a randomly occurring error: https://github.com/SpikeInterface/spikeinterface/actions/runs/7726818932/job/21063882437
> Fix spikes generation on borders

- src/spikeinterface/extractors/neoextractors/neuralynx.py
Added the possibility when loading from neuralynx to give a list of files to ignore to match Neo's arguments.
> [IO] added exclude_filename argument to NeuralynxRecordingExtractor

- src/spikeinterface/core/__init__.py
- src/spikeinterface/core/core_tools.py
- src/spikeinterface/core/tests/test_core_tools.py
- src/spikeinterface/preprocessing/filter_gaussian.py
Computing the Gaussian pdf from scipy is surprisingly slow,
Removed scipy import and implemented the pdf from the formula.
> Faster Gaussian filter implementation

- README.md
- doc/api.rst
- doc/modules/preprocessing.rst
- doc/releases/0.100.0.rst
- doc/whatisnew.rst
- pyproject.toml
- src/spikeinterface/__init__.py
- src/spikeinterface/sortingcomponents/motion_estimation.py
> Prepare release 0.100.0

- .github/workflows/caches_cron_job.yml
- .github/workflows/core-test.yml
- .github/workflows/deepinterpolation.yml
- .github/workflows/full-test-with-codecov.yml
- .github/workflows/full-test.yml
- .github/workflows/installation-tips-test.yml
- .github/workflows/issue-on-change-matlab.yml
- .github/workflows/publish-to-pypi.yml
- .github/workflows/streaming-extractor-test.yml
- .github/workflows/test_containers_docker.yml
- .github/workflows/test_containers_singularity.yml
- .github/workflows/test_containers_singularity_gpu.yml
- .github/workflows/test_imports.yml
Probably should be done after the release just to avoid a potential hedache who will point at me : P
> update all CI actions

- src/spikeinterface/core/sortinganalyzer.py
I figure it is better just to add some updates live so that it will be easier to do small chunks rather than giant edits of the docstrings. But if you want me to close this and wait until later to do this that's fine too. Also (pre-weekend @samuelgarcia :).
> Fix `SorterAnalyzer` docstrings

- src/spikeinterface/sorters/internal/simplesorter.py
- src/spikeinterface/sorters/internal/tests/test_simplesorter.py
- src/spikeinterface/sorters/sorterlist.py
- src/spikeinterface/sortingcomponents/waveforms/temporal_pca.py
rebirth of simple_sorter in spikeinterface
This will be super usefull for teaching basic of spike sorting
This replace #1405
> simple_sorter in spikeinterface

- src/spikeinterface/core/job_tools.py
- src/spikeinterface/core/tests/test_job_tools.py
@yger : can you check this and tell me if it fixes your bug ?
@alejoe91 : this should go also in the bug fix release
> Fix mutually exclusive keys in job_kwargs

- src/spikeinterface/core/__init__.py
- src/spikeinterface/core/analyzer_extension_core.py
- src/spikeinterface/core/sortinganalyzer.py
Fixes #2557 
@alejoe91's fix for writing the sorting_provenance
> Add `check_json` to `zarr` for `SortingAnalyzer` for sorting_provenance file writing

- doc/releases/0.100.1.rst
- doc/whatisnew.rst
- pyproject.toml
> Prepare minor 0.100.1 release

- src/spikeinterface/sorters/external/kilosort4.py
> Add batch size to KS4 wrapper

- src/spikeinterface/sorters/internal/simplesorter.py
Update exclude_sweep_ms for SimpleSortersimplesorter
> Simple sorter better params

- doc/how_to/get_started.rst
- examples/how_to/get_started.py
Main tutorial update to clarify confusion in #2619
> Update get_started.rst with info for reloading saved binaries

- src/spikeinterface/extractors/nwbextractors.py
As in the title. That was an experiment that Alessio indulge me on but does not makes sense to keep this complication I feel.
> Remove lazy typing in nwb

- src/spikeinterface/extractors/nwbextractors.py
> Add extra_requirements for nwb extractors

- doc/releases/0.100.4.rst
- doc/whatisnew.rst
- pyproject.toml
- src/spikeinterface/core/base.py
- src/spikeinterface/core/tests/test_zarrextractors.py
- src/spikeinterface/core/zarrextractors.py
Minor release with this PR:
- #2643
> Prepare 0.100.4

- src/spikeinterface/postprocessing/tests/test_unit_localization.py
- src/spikeinterface/postprocessing/unit_localization.py
> Revert change in set_params for unit locations

- src/spikeinterface/core/__init__.py
- src/spikeinterface/core/analyzer_extension_core.py
- src/spikeinterface/core/sorting_tools.py
- src/spikeinterface/core/tests/test_analyzer_extension_core.py
- src/spikeinterface/core/waveforms_extractor_backwards_compatibility.py
- src/spikeinterface/postprocessing/principal_component.py
- src/spikeinterface/postprocessing/template_similarity.py
Also changed:
- `compute_select_random_spikes` to `compute_random_spikes` 
- `some_spikes()` function to `random_spikes()`
> Analyzer core extension: improve docstrings

- src/spikeinterface/core/base.py
- src/spikeinterface/core/channelsaggregationrecording.py
- src/spikeinterface/core/channelslice.py
- src/spikeinterface/core/frameslicerecording.py
- src/spikeinterface/core/frameslicesorting.py
- src/spikeinterface/core/tests/test_channelslicerecording.py
- src/spikeinterface/core/tests/test_frameslicerecording.py
- src/spikeinterface/core/tests/test_frameslicesorting.py
- src/spikeinterface/core/tests/test_unitsselectionsorting.py
- src/spikeinterface/core/unitsselectionsorting.py
- src/spikeinterface/curation/remove_duplicated_spikes.py
- src/spikeinterface/curation/remove_excess_spikes.py
- src/spikeinterface/postprocessing/alignsorting.py
- src/spikeinterface/preprocessing/align_snippets.py
- src/spikeinterface/preprocessing/basepreprocessor.py
- src/spikeinterface/preprocessing/zero_channel_pad.py
Fixes #2596
This is super useful for example to plot different processing layers!
> Implement `get_parent()` function

- src/spikeinterface/extractors/neoextractors/openephys.py
Fixes #2654
@rcpeene can you test if you can load the "problematic" dataset by installing from source from this branch?
> Open Ephys: Use discovered recording ids to load sync timestamps

- pyproject.toml
Full tests are failling. I think this is related to this issue here:
https://github.com/int-brain-lab/ibllib/issues/753
> Fix full tests

- .github/workflows/core-test.yml
- .github/workflows/full-test.yml
- doc/releases/0.100.5.rst
- doc/whatisnew.rst
- pyproject.toml
- src/spikeinterface/extractors/neoextractors/openephys.py
- src/spikeinterface/extractors/nwbextractors.py
- src/spikeinterface/widgets/spikes_on_traces.py
Inlcuding:
* #2655
* #2661
* #2676
> Preprare 0.100.5

- src/spikeinterface/widgets/spikes_on_traces.py
> Fix depth location in spikes on traces map

- src/spikeinterface/comparison/tests/test_templatecomparison.py
- src/spikeinterface/core/__init__.py
- src/spikeinterface/core/analyzer_extension_core.py
- src/spikeinterface/core/sortinganalyzer.py
- src/spikeinterface/core/sparsity.py
- src/spikeinterface/core/template_tools.py
- src/spikeinterface/core/tests/test_analyzer_extension_core.py
- src/spikeinterface/core/tests/test_node_pipeline.py
- src/spikeinterface/core/tests/test_sparsity.py
- src/spikeinterface/core/tests/test_template_tools.py
- src/spikeinterface/curation/auto_merge.py
- src/spikeinterface/exporters/to_phy.py
- src/spikeinterface/postprocessing/amplitude_scalings.py
- src/spikeinterface/postprocessing/spike_amplitudes.py
- src/spikeinterface/postprocessing/spike_locations.py
- src/spikeinterface/postprocessing/template_metrics.py
- src/spikeinterface/postprocessing/template_similarity.py
- src/spikeinterface/postprocessing/unit_localization.py
- src/spikeinterface/qualitymetrics/misc_metrics.py
- src/spikeinterface/qualitymetrics/pca_metrics.py
- src/spikeinterface/sortingcomponents/benchmark/benchmark_clustering.py
- src/spikeinterface/sortingcomponents/benchmark/benchmark_peak_detection.py
- src/spikeinterface/sortingcomponents/benchmark/benchmark_peak_localization.py
- src/spikeinterface/sortingcomponents/benchmark/benchmark_peak_selection.py
- src/spikeinterface/sortingcomponents/tests/test_template_matching.py
- src/spikeinterface/widgets/unit_probe_map.py
- src/spikeinterface/widgets/unit_waveforms.py
- src/spikeinterface/widgets/unit_waveforms_density_map.py
"templates" and "fast_templates" extension have been merge together.
Done with Alessio.
> Death of "fast_templates" extention

- src/spikeinterface/widgets/unit_waveforms.py
> Enable waveform-less plot templates

- src/spikeinterface/core/analyzer_extension_core.py
- src/spikeinterface/core/sorting_tools.py
- src/spikeinterface/core/tests/test_sorting_tools.py
> Seepdup random_spikes_selection() and put "all" method in it.

- src/spikeinterface/extractors/iblextractors.py
> Fix EID in IBL

- src/spikeinterface/comparison/groundtruthstudy.py
- src/spikeinterface/sortingcomponents/benchmark/benchmark_tools.py
> Some fixes for GTStudy

- src/spikeinterface/core/sortinganalyzer.py
@samuelgarcia 
Fixes a bug when pipelining extensions
> Fix pipelining of extensions

- src/spikeinterface/core/template.py
As in the title. See here for how it looks. Feel free to make recommendations on how this should be.
> Add basic repr to `Templates` object

- src/spikeinterface/core/waveform_tools.py
- src/spikeinterface/curation/remove_excess_spikes.py
- src/spikeinterface/curation/tests/test_remove_excess_spikes.py
See [this comment](https://github.com/SpikeInterface/spikeinterface/issues/2710#issuecomment-2061077666)
> Make sure `has_exceeding_spikes` also checks for negative spikes.

- doc/releases/0.100.6.rst
- doc/whatisnew.rst
- pyproject.toml
- src/spikeinterface/core/core_tools.py
- src/spikeinterface/core/waveform_tools.py
- src/spikeinterface/sorters/external/kilosort4.py
@zm711 added #2774 , that still needs merging
> Prepare release 0.100.6

- src/spikeinterface/core/baserecording.py
- src/spikeinterface/core/channelslice.py
- src/spikeinterface/core/tests/test_baserecording.py
In analogy to `select_units` to make the API more consistent.
> Add `select_channels` method to base recording

- src/spikeinterface/core/numpyextractors.py
- src/spikeinterface/core/sortinganalyzer.py
After some discuss with @alejoe91 we remove the sharedmem from analyzer because it fails inside docker and finally the sharedmem was not used.
> Remove SharedMemory from SortingAnalyzer and use NumpySorting instead.

- src/spikeinterface/core/analyzer_extension_core.py
- src/spikeinterface/core/generate.py
- src/spikeinterface/core/sortinganalyzer.py
- src/spikeinterface/core/template.py
- src/spikeinterface/core/tests/test_template_tools.py
- src/spikeinterface/generation/drifting_generator.py
- src/spikeinterface/generation/tests/test_drift_tools.py
- src/spikeinterface/sorters/internal/spyking_circus2.py
- src/spikeinterface/sorters/internal/tridesclous2.py
- src/spikeinterface/sortingcomponents/benchmark/tests/common_benchmark_testing.py
- src/spikeinterface/sortingcomponents/clustering/circus.py
- src/spikeinterface/sortingcomponents/clustering/position_and_features.py
- src/spikeinterface/sortingcomponents/clustering/random_projections.py
- src/spikeinterface/sortingcomponents/tools.py
Shouod solve https://github.com/SpikeInterface/spikeinterface/issues/2831
Draft because I don't know what will fail : )
> Add `is_scaled` to `Templates` object

- src/spikeinterface/core/template_tools.py
- src/spikeinterface/core/tests/test_template_tools.py
@samuelgarcia @yger I think we need this option urgently for amplitudes!
> Add peak_to_peak mode to get_templates_amplitude

- src/spikeinterface/widgets/tests/test_widgets.py
- src/spikeinterface/widgets/unit_depths.py
- src/spikeinterface/widgets/unit_summary.py
- src/spikeinterface/widgets/unit_templates.py
- src/spikeinterface/widgets/unit_waveforms.py
- src/spikeinterface/widgets/unit_waveforms_density_map.py
- src/spikeinterface/widgets/utils.py
- src/spikeinterface/widgets/utils_ipywidgets.py
As discussed, starting to break #2436 down into small pieces :)
> Extend plot waveforms/templates to Templates object

- src/spikeinterface/core/analyzer_extension_core.py
- src/spikeinterface/core/sortinganalyzer.py
- src/spikeinterface/core/sparsity.py
- src/spikeinterface/core/tests/test_sortinganalyzer.py
- src/spikeinterface/widgets/utils_matplotlib.py
@alejoe91 
Various but important that prevent demo to be run:
* zarr in analyzer
* matplotlib
> Important fixes

- src/spikeinterface/sorters/internal/simplesorter.py
@samuelgarcia / @yger
This is just a quick write up of the params. Edit this whenever you have time!
Related to #2890.
> Add `_params_descriptions` for simple sorter

- src/spikeinterface/core/analyzer_extension_core.py
- src/spikeinterface/core/node_pipeline.py
- src/spikeinterface/core/sortinganalyzer.py
- src/spikeinterface/core/waveform_tools.py
- src/spikeinterface/extractors/iblextractors.py
- src/spikeinterface/postprocessing/amplitude_scalings.py
- src/spikeinterface/postprocessing/correlograms.py
- src/spikeinterface/postprocessing/isi.py
- src/spikeinterface/postprocessing/principal_component.py
- src/spikeinterface/postprocessing/spike_amplitudes.py
- src/spikeinterface/postprocessing/spike_locations.py
- src/spikeinterface/postprocessing/template_metrics.py
- src/spikeinterface/postprocessing/template_similarity.py
- src/spikeinterface/postprocessing/unit_localization.py
- src/spikeinterface/sortingcomponents/matching/main.py
- src/spikeinterface/sortingcomponents/peak_detection.py
> Fix more verbosity propagation

- src/spikeinterface/qualitymetrics/misc_metrics.py
- src/spikeinterface/qualitymetrics/pca_metrics.py
- src/spikeinterface/qualitymetrics/quality_metric_calculator.py
- src/spikeinterface/qualitymetrics/utils.py
This pull request standardises the quality metrics module docstrings to numpydoc standard. I went through each function in the module and ran the numpydoc validator and made edits to docstrings where appropriate.
> Standardise qualitymetrics docstrings to numpydocs standard

- src/spikeinterface/preprocessing/deepinterpolation/deepinterpolation.py
- src/spikeinterface/preprocessing/deepinterpolation/generators.py
- src/spikeinterface/preprocessing/deepinterpolation/tests/test_deepinterpolation.py
- src/spikeinterface/preprocessing/deepinterpolation/train.py
Updated deepinterpolation code to use v0.2.0
Should fix failing tests in https://github.com/SpikeInterface/spikeinterface/pull/2927
> Fix deepinterpolation tests

- src/spikeinterface/core/baserecordingsnippets.py
- src/spikeinterface/extractors/neoextractors/spikegadgets.py
Currently without a deprecation. Do we want a deprecation just to be safe for this one? Again it is not documented but someone could be using it...?
> Make _set_probes private

- src/spikeinterface/generation/tests/test_template_database.py
The template ilbrary is being rebuilt!
@h-mayorquin can you check and merge?
> Update tests against template library

- src/spikeinterface/widgets/amplitudes.py
- src/spikeinterface/widgets/potential_merges.py
- src/spikeinterface/widgets/unit_waveforms.py
- src/spikeinterface/widgets/utils_ipywidgets.py
- src/spikeinterface/widgets/utils_matplotlib.py
- src/spikeinterface/widgets/widget_list.py
> Plot potential merges

- src/spikeinterface/__init__.py
> Set DEV=True until release

- src/spikeinterface/widgets/potential_merges.py
> Fix bug in plot_potential_merges

- pyproject.toml
From the discussion in https://github.com/SpikeInterface/spikeinterface/issues/3033#issuecomment-2179275980 with @samuelgarcia 
I will do a brief check if we are saving to pickle and not using it as multiprocessing and then we should merge this before the release.
> Relax numpy

- src/spikeinterface/core/sorting_tools.py
- src/spikeinterface/postprocessing/spike_amplitudes.py
- src/spikeinterface/postprocessing/spike_locations.py
Hi @chrishalcrow
This a better change than #2981 I think becaus the cause was deepp inside.
Can you test if it fixes the sapike amplitude ?
> fix spike_vector_to_indices()

- src/spikeinterface/core/base.py
- src/spikeinterface/core/baserecordingsnippets.py
- src/spikeinterface/core/basesorting.py
- src/spikeinterface/core/binaryfolder.py
- src/spikeinterface/core/binaryrecordingextractor.py
- src/spikeinterface/core/core_tools.py
- src/spikeinterface/core/frameslicerecording.py
- src/spikeinterface/core/generate.py
- src/spikeinterface/core/numpyextractors.py
- src/spikeinterface/core/recording_tools.py
- src/spikeinterface/core/sortinganalyzer.py
- src/spikeinterface/core/waveform_tools.py
- src/spikeinterface/sorters/basesorter.py
Was waiting for a sorting to finish up so added bool type hints to core.
Couple docstring additions.
> Add `bool` type hint to functions in core module

- pyproject.toml
Follow up on #3084, which was missing one preprocessing dependency
> Add ibllib to test requirements

- pyproject.toml
Just realized a few examples in the docs are broken!
> Add pooch to docs extra

- .gitignore
Removed a bunch of stuff we no logner used as the tests do not produce output anymore. Other stuff we did not really use.
> Clean gitignore

- src/spikeinterface/sortingcomponents/peak_selection.py
@samuelgarcia @yger
This is a fix for https://github.com/SpikeInterface/spikeinterface/pull/2980 :
The spikes need to be lexsorted based on segment and sample indices
sample indices start from 0 for each segment, so you don't need an offset!
> Fix select peaks

- doc/api.rst
- src/spikeinterface/core/__init__.py
- src/spikeinterface/core/sorting_tools.py
- src/spikeinterface/core/tests/test_sorting_tools.py
- src/spikeinterface/curation/mergeunitssorting.py
Theses two PR need `apply_merges_to_sorting()` but I was not happy with behavior and implementation.
#3043
#2934
Here a new implementation of the same idea but normally faster.
@alejoe91 
This should be merge before #3043  #2934
> Implement apply_merges_to_sorting()

- src/spikeinterface/core/segmentutils.py
- src/spikeinterface/core/tests/test_segmentutils.py
> Fix segment start/end frame None in concatenate_recordings

- src/spikeinterface/extractors/extractorlist.py
- src/spikeinterface/extractors/neoextractors/__init__.py
> Build extractor dicts automatically

- .github/workflows/all-tests.yml
@h-mayorquin 
One typo in your test heading. This just fixes that.
> Fix typo in CI testing heading

- doc/modules/comparison.rst
- doc/modules/core.rst
- doc/modules/postprocessing.rst
Fixes #3177.
@alejoe91 I think I hit the ones you were mentioning, but it required a rewriting of sparsity a bit so could you carefully read that to make sure I didn't mess it up.
Made in another PR we mention the estimate_sparsity function?
> Convert doc references from `wf_extractor` -> `sorting_analyzer`

- src/spikeinterface/core/tests/test_generate.py
- src/spikeinterface/preprocessing/tests/test_silence.py
Related to #3186, but not closing because we should investigate the nature of the failures
> Add a couple of seeds in tests

- src/spikeinterface/core/base.py
- src/spikeinterface/preprocessing/align_snippets.py
- src/spikeinterface/preprocessing/average_across_direction.py
- src/spikeinterface/preprocessing/basepreprocessor.py
- src/spikeinterface/preprocessing/clip.py
- src/spikeinterface/preprocessing/common_reference.py
- src/spikeinterface/preprocessing/decimate.py
- src/spikeinterface/preprocessing/deepinterpolation/deepinterpolation.py
- src/spikeinterface/preprocessing/depth_order.py
- src/spikeinterface/preprocessing/directional_derivative.py
- src/spikeinterface/preprocessing/filter.py
- src/spikeinterface/preprocessing/filter_gaussian.py
- src/spikeinterface/preprocessing/filter_opencl.py
- src/spikeinterface/preprocessing/highpass_spatial_filter.py
- src/spikeinterface/preprocessing/interpolate_bad_channels.py
- src/spikeinterface/preprocessing/normalize_scale.py
- src/spikeinterface/preprocessing/phase_shift.py
- src/spikeinterface/preprocessing/preprocessinglist.py
- src/spikeinterface/preprocessing/rectify.py
- src/spikeinterface/preprocessing/remove_artifacts.py
- src/spikeinterface/preprocessing/resample.py
- src/spikeinterface/preprocessing/silence_periods.py
- src/spikeinterface/preprocessing/unsigned_to_signed.py
- src/spikeinterface/preprocessing/whiten.py
- src/spikeinterface/preprocessing/zero_channel_pad.py
Related and progresses on  #2784
Should close #3199
> Remove name class attribute in preprocessing module

- src/spikeinterface/postprocessing/principal_component.py
I have actually encountered #3166 a few times, and it should be fixed with this simple solution. We were a bit too strict with the exception type.
Fixes #3166
> Fix pca transform error

- src/spikeinterface/extractors/neoextractors/neobaseextractor.py
So this is related to #2784.
There, we made `name` an attribute for representation purposes which is great.
However, this clashes with the use of `all_annotations=True` for neo based extractors that load the stream_name as an annotation wose key is "name". This means that you get these monsters in the repr:
(see, the strem name is displayed because the annotation was loaded by neo as name).
This PR corrects that by setting the neo annotation called name as stream_name which is what it actually is.
Another minor fix is to avoid loding ids again as a property and channel_names when the latter are used as ids.
> Fix naming when `all_annotations=True` in neo base extractors

- src/spikeinterface/widgets/unit_templates.py
@samuelgarcia little left over bug in plot_unit_templates found after testing in sortingview
> Channel ids sortingview

- src/spikeinterface/curation/auto_merge.py
- src/spikeinterface/postprocessing/tests/common_extension_tests.py
- src/spikeinterface/sorters/internal/spyking_circus2.py
Some behaviour of SC2 is broken with the refactoring of auto_merges, and we need to remove empty units also. This PR will restore the old behaviour
> Patch for SC2 after release AND bugs in auto merge

- src/spikeinterface/core/core_tools.py
> Fix bug in extractor_dict_iterator if element is not str/Path

- src/spikeinterface/sortingcomponents/motion/motion_utils.py
- src/spikeinterface/sortingcomponents/motion/tests/test_motion_estimation.py
@samuelgarcia 
Also added tests
> Fix estimate_motion when time_vector is set

- src/spikeinterface/postprocessing/principal_component.py
> PCA: Extend try-except to fit in run_for_all_spikes

- src/spikeinterface/sorters/external/kilosortbase.py
> Fix KS2/2.5/3 skip_kilosort_preprocessing

- doc/modules/qualitymetrics.rst
> Fix name of principal_components ext in qm docs (take 2)

- doc/modules/postprocessing.rst
> Fix postprocessing docs

- src/spikeinterface/postprocessing/spike_amplitudes.py
> Fix docstring and error for spike_amplitudes

- src/spikeinterface/comparison/basecomparison.py
- src/spikeinterface/comparison/comparisontools.py
- src/spikeinterface/curation/curation_format.py
- src/spikeinterface/curation/curation_tools.py
- src/spikeinterface/curation/splitunitsorting.py
- src/spikeinterface/sorters/container_tools.py
- src/spikeinterface/sorters/external/kilosort.py
- src/spikeinterface/sorters/external/kilosort2.py
- src/spikeinterface/sorters/external/kilosort2_5.py
- src/spikeinterface/sorters/external/kilosort3.py
- src/spikeinterface/sorters/external/kilosortbase.py
@chrishalcrow, just doing a few files as well. You shouldn't shoulder all of this! Please review. Happy to make docstring fixes, but this submission was just for the colon spacing so up to the reviewers if we want to just merge or touch-up at the same time :)
> More numpydoc fixes

- src/spikeinterface/sorters/container_tools.py
- src/spikeinterface/sorters/external/kilosort4.py
Previous code failed when docker could not be run on the host system. Now getting the docker image via spython.
> fix: download apptainer images without docker client

- src/spikeinterface/core/sortinganalyzer.py
Proposal to address #3255. AFAICT, splitting the kwargs is never an issue, even if there aren't any job kwargs passed / even if they're passed and not needed.
> Job kwargs fix

- src/spikeinterface/sortingcomponents/motion/motion_interpolation.py
> Make InterpolateMotionRecording not JSON-serializable

- src/spikeinterface/curation/auto_merge.py
> Clean-up identity merges in `get_potential_auto_merges`

- src/spikeinterface/extractors/phykilosortextractors.py
> Load phy channel_group as group

- src/spikeinterface/generation/drift_tools.py
I think that this small change is necessary to handle interpolating templates from one probe to another when they have different channel counts
> Handle case where channel count changes from probeA to probeB

- src/spikeinterface/core/baserecording.py
- src/spikeinterface/core/tests/test_baserecording.py
Thanks @JoeZiminski 
This is an amazing catch!
> Reset times 3: fix case when no time vector

- src/spikeinterface/widgets/motion.py
> Fix plot motion for multi-segment

- .github/workflows/all-tests.yml
- .github/workflows/full-test-with-codecov.yml
- src/spikeinterface/widgets/tests/test_widgets.py
@magland suggested we upload kachery data to a `temporary` zone that he created and will be disposable.
Updated secrets and testing new behavior
> Add kachery_zone secret

- pyproject.toml
- src/spikeinterface/__init__.py
@alejoe91 @h-mayorquin we forgot the after-release. Am I missing anything?
> After release 0.101.1

- src/spikeinterface/extractors/iblextractors.py
The PID in the IBL database uniquely identifies an insertion. Currently, we cannot instantiate an extractor inly with the PID because there are multiple streams. This PR adds the `stream_type` argument so that one can load an IBL recording with the PID+stream_type (ap or lf).
> Improve IBL recording extractors by PID

- src/spikeinterface/sorters/utils/shellscript.py
> Get default encoding for Popen

- src/spikeinterface/core/sorting_tools.py
- src/spikeinterface/core/tests/test_sorting_tools.py
fix random_spikes_selection()
fix #3450
@borrepp could you check this please ?
> fix random_spikes_selection()

- src/spikeinterface/postprocessing/localization_tools.py
- src/spikeinterface/postprocessing/tests/test_unit_locations.py
1. Use existing sparsity for unit location
2. Add location with max channel
> Unit localization

- src/spikeinterface/core/template_tools.py
Loading templates whatever the operator in the `get_dense_templates_array` function. 
Following #3494.
> Template loading average or median

- src/spikeinterface/preprocessing/silence_periods.py
This is an attempt to fix #3554, despite the fact that I can not reproduce per se the bug
> Fix silence periods

- src/spikeinterface/extractors/nwbextractors.py
> Add `stream_mode` as extra_requirements for NWB when streaming

- src/spikeinterface/sorters/external/kilosort4.py
Closes https://github.com/SpikeInterface/spikeinterface/issues/3611
> Change to default value `use_binary_file=True` for KS4

- doc/conf.py
I included our options in a comment to make it easier to edit in the future.
Fixes #3603
> Switch RTD build to fail on gallery example failure

- src/spikeinterface/extractors/neoextractors/openephys.py
> Add experiment_name annotation to open ephys

- doc/how_to/benchmark_with_hybrid_recordings.rst
- examples/how_to/benchmark_with_hybrid_recordings.py
> Fix precision/recall in hybrid example

- doc/development/development.rst
Noticed a typo I wanted to fix and then realized the doc links were all to 0.96.1 so updated to the main link so it should auto update as long as we don't change the file name itself.
> Dev Doc touchup

- src/spikeinterface/sorters/external/kilosort.py
- src/spikeinterface/sorters/external/kilosortbase.py
np.Inf with a capital has been removed for numpy 2.0, so this is a patch
> np 2.0 compatibility

- pyproject.toml
Need a fix in neo: https://github.com/holgern/pyedflib/releases/tag/v0.1.39
> Pin pyedflib version after breaking change in annotations

- src/spikeinterface/sortingcomponents/motion/motion_utils.py
- src/spikeinterface/sortingcomponents/motion/tests/test_motion_interpolation.py
> Multi segment handling in ensure_time_bins

- src/spikeinterface/core/sortingfolder.py
> Remove mmap mode in numpy folder

- src/spikeinterface/core/base.py
- src/spikeinterface/core/sortinganalyzer.py
- src/spikeinterface/core/tests/test_sortinganalyzer.py
Helper function to add properties to `SortingAnalyzer.sorting` and make them persistent to disk
> Add `SortingAnalyzer.set_sorting_property()/get_sorting_property()` functions

- src/spikeinterface/core/recording_tools.py
> Fix `chunk_size_limit` in `get_random_recording_slices`

- src/spikeinterface/widgets/crosscorrelograms.py
Minor PR to slightly enhance the CC plots for matplotlib, going from
To
> Enhance the CC plots

- src/spikeinterface/core/binaryrecordingextractor.py
- src/spikeinterface/core/tests/test_binaryrecordingextractor.py
- src/spikeinterface/extractors/neoextractors/openephys.py
> Deprecate num channels in BinaryRecordingExtractor

- src/spikeinterface/core/node_pipeline.py
- src/spikeinterface/sortingcomponents/clustering/peak_svd.py
- src/spikeinterface/sortingcomponents/motion/__init__.py
- src/spikeinterface/sortingcomponents/motion/motion_interpolation.py
- src/spikeinterface/sortingcomponents/tests/test_clustering.py
- src/spikeinterface/sortingcomponents/tools.py
- src/spikeinterface/sortingcomponents/waveforms/temporal_pca.py
This implements sparse svd decompostion which has the option of "motion aware".
The decompostion are interpolated back to stable position using cubic interpolation.
This should help the clustering for SC2 or TDC2 in case of motion.
@yger
Note:
* To achieve this a small hack to node_pipeline has been done optionaly for node computation to be aware of the true time.
* a small bugfix also in `correct_motion_on_peaks()` when using multi segments.
> Peak SVD motion extraction

- src/spikeinterface/extractors/neoextractors/neobaseextractor.py
This pull request fixes issue #3727.
> Fix gain inference for "Volts" unit in Plexon2 files

- src/spikeinterface/core/node_pipeline.py
This PR adds the option to provide a custom mask for SparseWaveform extraction
> Explicit sparsity mask for SparseWaveform

- pyproject.toml
Should fix https://github.com/SpikeInterface/spikeinterface/actions/runs/13764736915/job/38502430794
> Add psutil to [test]

- pyproject.toml
Sortingview has been updated, so we need some modifications to the CI to make it work with the latest versiobn
> Pin sortingview version

- src/spikeinterface/widgets/sorting_summary.py
> In sorting_summary: `rp_violation` -> `rp_violations`

- .github/scripts/check_kilosort4_releases.py
- .github/scripts/test_kilosort4_ci.py
- src/spikeinterface/sorters/external/kilosort4.py
Versions 4.0.26/27 are buggy. v4.0.28 added a new `verbose` param ot some functions!
> Fix KS4 tests

- .github/workflows/deepinterpolation.yml
- doc/api.rst
- doc/how_to/process_by_channel_group.rst
- doc/modules/preprocessing.rst
- src/spikeinterface/core/core_tools.py
- src/spikeinterface/preprocessing/astype.py
- src/spikeinterface/preprocessing/average_across_direction.py
- src/spikeinterface/preprocessing/clip.py
- src/spikeinterface/preprocessing/common_reference.py
- src/spikeinterface/preprocessing/decimate.py
- src/spikeinterface/preprocessing/deepinterpolation/deepinterpolation.py
- src/spikeinterface/preprocessing/depth_order.py
- src/spikeinterface/preprocessing/directional_derivative.py
- src/spikeinterface/preprocessing/filter.py
- src/spikeinterface/preprocessing/filter_gaussian.py
- src/spikeinterface/preprocessing/highpass_spatial_filter.py
- src/spikeinterface/preprocessing/interpolate_bad_channels.py
- src/spikeinterface/preprocessing/normalize_scale.py
- src/spikeinterface/preprocessing/phase_shift.py
- src/spikeinterface/preprocessing/preprocessinglist.py
- src/spikeinterface/preprocessing/rectify.py
- src/spikeinterface/preprocessing/remove_artifacts.py
- src/spikeinterface/preprocessing/resample.py
- src/spikeinterface/preprocessing/silence_periods.py
- src/spikeinterface/preprocessing/tests/test_clip.py
- src/spikeinterface/preprocessing/tests/test_grouped_preprocessing.py
- src/spikeinterface/preprocessing/unsigned_to_signed.py
- src/spikeinterface/preprocessing/whiten.py
- src/spikeinterface/preprocessing/zero_channel_pad.py
Copy of #3711, before I somehow made a mess of it.
See #3711 for information and discussion.
Edit: read the new docs here: https://spikeinterface--3773.org.readthedocs.build/en/3773/how_to/process_by_channel_group.html#preprocessing-a-recording-by-channel-group
> Allow preprocessing on dicts of recordings (again)

- .github/workflows/all-tests.yml
- .github/workflows/deepinterpolation.yml
- .github/workflows/issue-on-change-matlab.yml
Here. After we do this we should change the keys.
> Update tj-actions changes-files for security

- src/spikeinterface/sorters/external/kilosort4.py
> Add job kwargs to KS4

- src/spikeinterface/extractors/neoextractors/neobaseextractor.py
@chrishalcrow 
Discussed on the meeting of 20 of March 2025
> Better naming for SI units 

- .github/scripts/determine_testing_environment.py
- pyproject.toml
- src/spikeinterface/extractors/tests/test_iblextractors.py
Let's see what the CI says. All the tests work locally for now !
> Make sure to use the latest ibllib version - ONE will come along

- doc/api.rst
> Add nwb extractors to API docs

- src/spikeinterface/sortingcomponents/clustering/peak_svd.py
Here we can handle the mask (needed if we want this function to be used by KS-like clustering and compare), and clean the outliers while collecting the peaks
> Minor improvements to extract_peak_svd

- pyproject.toml
See https://github.com/zarr-developers/numcodecs/issues/721
> pin numcodecs

- src/spikeinterface/extractors/neoextractors/biocam.py
see https://github.com/NeuralEnsemble/python-neo/pull/1446
> neoextractor biocam: add paramaters for sparse event based recordings

- src/spikeinterface/extractors/neoextractors/openephys.py
Should fix #3837
As requested by @chrishalcrow and @alejoe91
> Backwards compatibility for sync stream in OpenEphysBinary

- .github/workflows/all-tests.yml
Let's test if this works. Will fix #3876 if it does.
> Change datalad installation in the CI for linux

- pyproject.toml
- src/spikeinterface/__init__.py
> After relase 102.0.3

- src/spikeinterface/sorters/runsorter.py
> Add in missing `get_nvidia_docker_dependencies`

- src/spikeinterface/benchmark/benchmark_base.py
smal fix in benchmark class
@yger
> fix benchmark load with partial result

- src/spikeinterface/extractors/nwbextractors.py
From the discussion https://github.com/SpikeInterface/spikeinterface/issues/3909#issuecomment-2882053335 in #3909
> Fix timestamps None in NWBRecordingExtractor

- src/spikeinterface/core/analyzer_extension_core.py
- src/spikeinterface/core/baserecording.py
- src/spikeinterface/curation/splitunitsorting.py
- src/spikeinterface/curation/tests/test_remove_redundant.py
- src/spikeinterface/extractors/hdsortextractors.py
- src/spikeinterface/extractors/iblextractors.py
- src/spikeinterface/extractors/klustaextractors.py
- src/spikeinterface/extractors/matlabhelpers.py
- src/spikeinterface/extractors/mcsh5extractors.py
- src/spikeinterface/extractors/neoextractors/blackrock.py
- src/spikeinterface/extractors/neoextractors/neobaseextractor.py
- src/spikeinterface/extractors/neoextractors/neuronexus.py
- src/spikeinterface/extractors/nwbextractors.py
- src/spikeinterface/extractors/shybridextractors.py
- src/spikeinterface/extractors/tests/test_bidsextractors.py
- src/spikeinterface/extractors/tests/test_combinatoextractors.py
- src/spikeinterface/extractors/tests/test_hdsortextractors.py
- src/spikeinterface/extractors/tests/test_klustaextractors.py
- src/spikeinterface/extractors/tests/test_spykingcircusextractors.py
- src/spikeinterface/extractors/tests/test_tridesclousextractors.py
- src/spikeinterface/extractors/tests/test_waveclustextractors.py
- src/spikeinterface/extractors/tests/test_whitematterrecordingextractor.py
- src/spikeinterface/extractors/tests/test_yassextractors.py
- src/spikeinterface/generation/template_database.py
- src/spikeinterface/generation/tests/test_splitting_tools.py
- src/spikeinterface/generation/tests/test_template_database.py
- src/spikeinterface/postprocessing/tests/test_isi.py
- src/spikeinterface/postprocessing/tests/test_template_similarity.py
- src/spikeinterface/postprocessing/unit_locations.py
Part of my ongoing efforts to cleanup things up and reduce potential tech debt. Let's see if I messed anything up :)
> Cleanup unused import across codebase

- src/spikeinterface/extractors/neoextractors/__init__.py
- src/spikeinterface/extractors/neoextractors/neo_utils.py
> Fix get_neo_* functions

- src/spikeinterface/preprocessing/tests/test_average_across_direction.py
- src/spikeinterface/preprocessing/tests/test_depth_order.py
Came up after merging this in probeinterface: https://github.com/SpikeInterface/probeinterface/pull/352
> Fix uniqueness of locations in test_average_across_directions

- pyproject.toml
Hopefully this will address #4016
> Fix IBL tests using ibllib hotfix

- src/spikeinterface/core/core_tools.py
Fixes #4045 
@jacobpennington can you check if this fixes your Windows issue?
> Check for remote paths in check_paths_relative

- src/spikeinterface/benchmark/benchmark_plot_tools.py
small bug in plot benchmark label order when grouping
> Small bug in plot benchmark label order when grouping

- doc/whatisnew.rst
@zm711 can we merge this before release so we have a clean doc in stable?
> Fix main changes in whatisnew for 0.103.0

- src/spikeinterface/sorters/external/rt_sort.py
This is needed to propagate to docker/apptainer images
> Add gpu requirements to rtsort

- doc/api.rst
- doc/conf.py
- pyproject.toml
- src/spikeinterface/core/sorting_tools.py
- src/spikeinterface/core/sortinganalyzer.py
- src/spikeinterface/curation/auto_merge.py
- src/spikeinterface/curation/curation_format.py
- src/spikeinterface/curation/curation_model.py
- src/spikeinterface/curation/tests/sv-sorting-curation-int.json
- src/spikeinterface/curation/tests/sv-sorting-curation-str.json
- src/spikeinterface/curation/tests/test_sortingview_curation.py
- src/spikeinterface/extractors/neoextractors/openephys.py
Added `autodoc_pydantic`, looks sweet!
> Improve docs for curation module and model
